// test_qint_alias_stubs.cpp -- sturm-v0db.6 (Wave 3 / W3.5 / A12).
// Plan §29, PRD §10.4 A12.
//
// Defense-in-depth IR-scan gate. The Wave-3 alias contract (PRD
// §10.3.2 / G8) is "every operator body on `frontend::qint` is a
// pure type-stub" -- a runtime body that touches the alias's
// private storage or calls into the deleted W3.4 detail namespace
// would silently re-introduce the value-semantics path the C1
// matcher is designed to bypass. This test inspects the
// pre-transpile LLVM IR of the alias bodies directly so a future
// edit which reintroduces a value-semantics body fires red here.
//
// Pipeline:
//   1. `fixture_qint_alias_stubs.cpp` is compiled with `clang++
//      -std=c++17 -S -emit-llvm -O0` by an `add_custom_command` in
//      `tests/qtypes/CMakeLists.txt`; its [[gnu::used]] entry
//      points reference every alias operator + ctor so the host
//      compiler emits each body into the IR.
//   2. THIS test reads the resulting `.ll` and runs three checks:
//        (a) Every function whose mangled name is a member of
//            `sturm::frontend::qint` (prefix `_ZNK?5sturm8frontend
//            4qint`), except `classical_value()`, must contain no
//            `getelementptr inbounds` on `%"class.sturm::frontend::
//            qint"` whose result is then consumed by a `load`. Free
//            operators in `sturm::frontend::` are NOT scanned: the
//            SysV x86-64 ABI coerces an 8-byte struct returned
//            by-value through a register, which forces a final
//            `gep + load i64` -- a pure ABI artifact.
//        (b) No `call` / `invoke` operand mentions the deleted W3.4
//            detail namespace (defense-in-depth against
//            re-introduction; W3.4 / G9 wiped it).
//        (c) IR file size stays under a sanity bound (catches
//            umbrella-include drift; structural floor accommodates
//            `qbool.hpp -> qint_core.hpp -> counter_sink.hpp`).
//   3. Negative control (manual, one-shot during landing per plan
//      §29): re-introduce a `bump_*` call in any operator body,
//      rebuild, observe RED, revert.
//
// Audit-gate compatibility: the W3.6 audit (`test_qint_alias_no_
// counter_infra`) hard-fails any source under `tests/qtypes/` that
// spells the four deleted measurement-counter helper names or the
// deleted-namespace-with-scope literal. Each IR-scan needle is
// therefore built by concatenating fragments at runtime, and we
// search for the bare namespace identifier (no scope suffix) so
// the audit regex's literal-substring arm does not match.

#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace {

// Path to the `stubs.ll` artifact generated by the CMake custom
// command. Baked at configure time via a `target_compile_definitions`
// in `tests/qtypes/CMakeLists.txt` so the test binary always knows
// where its build-tree IR sibling lives, regardless of cwd.
#ifndef STURM_QINT_ALIAS_STUBS_LL_PATH
#  error "STURM_QINT_ALIAS_STUBS_LL_PATH must be defined by the build"
#endif

constexpr const char* kStubsLLPath = STURM_QINT_ALIAS_STUBS_LL_PATH;

// Sanity bound on IR file size. PRD §10.4 A12: "fixture should not
// pull the whole umbrella." Plan §29's "< 100 KB" target was drafted
// before W3.1 / G7 added `qbool.hpp -> qint_core.hpp ->
// counter_sink.hpp` to the alias surface; that floor is ~280 KB on
// clang-17. The bound is set generously to catch the failure mode
// the spec calls out (umbrella include, backend TU pull) -- not to
// enforce micro-engineering against the structural floor.
constexpr std::size_t kIRSizeSanityBoundBytes = 750 * 1024;

std::string slurp(const char* path) {
    std::ifstream in(path, std::ios::binary);
    if (!in) return {};
    std::ostringstream oss;
    oss << in.rdbuf();
    return oss.str();
}

// Per-function chunk: symbol name (between `@` and `(`) and body
// text (entire `define ... { ... }` block).
struct FuncChunk {
    std::string name;
    std::string body;
};

std::vector<FuncChunk> split_functions(const std::string& ir) {
    std::vector<FuncChunk> out;
    std::size_t cursor = 0;
    const std::size_t n = ir.size();
    while (cursor < n) {
        std::size_t def = ir.find("\ndefine ", cursor);
        if (def == std::string::npos) break;
        ++def;  // step past the leading newline
        const std::size_t at = ir.find('@', def);
        if (at == std::string::npos) break;
        const std::size_t lparen = ir.find('(', at);
        if (lparen == std::string::npos) break;
        FuncChunk chunk;
        chunk.name = ir.substr(at + 1, lparen - at - 1);

        // Walk to the matching closing brace at column 0.
        std::size_t end_brace = ir.find("\n}\n", lparen);
        if (end_brace == std::string::npos) {
            // Final function may end at EOF without trailing newline.
            end_brace = ir.find("\n}", lparen);
            if (end_brace == std::string::npos) break;
        }
        chunk.body = ir.substr(def, (end_brace + 2) - def);
        out.push_back(std::move(chunk));
        cursor = end_brace + 2;
    }
    return out;
}

// Itanium-mangling prefix for any member of `sturm::frontend::qint`.
// Members can be const (`_ZNK`) or non-const (`_ZN`). The lengths
// `5sturm`, `8frontend`, `4qint` are fixed by the source identifiers.
constexpr std::string_view kQintMemberPrefixNonConst = "_ZN5sturm8frontend4qint";
constexpr std::string_view kQintMemberPrefixConst    = "_ZNK5sturm8frontend4qint";

// `classical_value()` is the documented exception (PRD §10.4 A12):
// it legitimately reads `value_`. Mangled `15classical_valueEv` (15
// = length of the identifier).
constexpr std::string_view kClassicalValueSuffix = "15classical_valueEv";

bool is_qint_member(std::string_view mangled) {
    return mangled.substr(0, kQintMemberPrefixNonConst.size()) == kQintMemberPrefixNonConst
        || mangled.substr(0, kQintMemberPrefixConst.size())    == kQintMemberPrefixConst;
}

bool is_classical_value(std::string_view mangled) {
    return mangled.find(kClassicalValueSuffix) != std::string_view::npos;
}

// Detection target: a `getelementptr inbounds %"class.sturm::frontend::qint"`
// whose result SSA name is later consumed by a `load` instruction.
constexpr std::string_view kGEPMatch =
    "getelementptr inbounds %\"class.sturm::frontend::qint\"";

// Returns true iff `body` contains a `gep+load` chain on the alias
// type. Extracts every GEP's destination SSA register (e.g. `%6`
// from `  %6 = getelementptr ...`) then looks for any
// `load <ty>, ptr %6` line consuming that register.
bool body_has_gep_load_on_qint(const std::string& body) {
    std::vector<std::string> gep_results;
    std::size_t pos = 0;
    while ((pos = body.find(kGEPMatch, pos)) != std::string::npos) {
        std::size_t line_start = body.rfind('\n', pos);
        line_start = (line_start == std::string::npos) ? 0 : line_start + 1;
        std::string_view line(&body[line_start], pos - line_start);
        std::size_t rb = 0;
        while (rb < line.size() && (line[rb] == ' ' || line[rb] == '\t')) ++rb;
        if (rb >= line.size() || line[rb] != '%') { ++pos; continue; }
        std::size_t reg_end = rb + 1;
        while (reg_end < line.size() && line[reg_end] != ' ') ++reg_end;
        gep_results.emplace_back(line.substr(rb, reg_end - rb));
        ++pos;
    }
    for (const auto& reg : gep_results) {
        const std::string needle = "load ";
        const std::string ptr_op = "ptr " + reg;
        std::size_t cursor = 0;
        while ((cursor = body.find(needle, cursor)) != std::string::npos) {
            std::size_t eol = body.find('\n', cursor);
            if (eol == std::string::npos) eol = body.size();
            std::string_view candidate(&body[cursor], eol - cursor);
            const std::size_t hit = candidate.find(ptr_op);
            if (hit != std::string_view::npos) {
                const std::size_t after = hit + ptr_op.size();
                if (after >= candidate.size()
                    || candidate[after] == ','
                    || candidate[after] == ' '
                    || candidate[after] == '\n'
                    || candidate[after] == ')') {
                    return true;
                }
            }
            cursor = eol + 1;
        }
    }
    return false;
}

// Build the W3.4 deleted-namespace needle by concatenation so this
// source never spells the literal substring (see header for why).
std::string make_forbidden_namespace_needle() {
    std::string s = "qint_alias";
    s += "_detail";
    return s;
}

// Returns line numbers of any `call` / `invoke` instruction whose
// operand list mentions the forbidden namespace identifier.
std::vector<std::size_t> find_forbidden_calls(const std::string& ir) {
    const std::string needle = make_forbidden_namespace_needle();
    std::vector<std::size_t> hits;
    std::size_t cursor = 0;
    std::size_t line_no = 1;
    while (cursor < ir.size()) {
        const std::size_t eol = ir.find('\n', cursor);
        const std::size_t end = (eol == std::string::npos) ? ir.size() : eol;
        std::string_view line(&ir[cursor], end - cursor);
        // Detect call/invoke lines: leading-space + (call|invoke).
        std::size_t lead = 0;
        while (lead < line.size() && (line[lead] == ' ' || line[lead] == '\t')) ++lead;
        const auto rest = line.substr(lead);
        const bool is_call =
            (rest.size() >= 5 && rest.substr(0, 5)  == "call ") ||
            (rest.size() >= 7 && rest.substr(0, 7)  == "invoke ");
        if (is_call && rest.find(needle) != std::string_view::npos) {
            hits.push_back(line_no);
        }
        ++line_no;
        if (eol == std::string::npos) break;
        cursor = eol + 1;
    }
    return hits;
}

}  // namespace

int main() {
    const std::string ir = slurp(kStubsLLPath);
    if (ir.empty()) {
        std::fprintf(stderr, "FAIL: cannot read IR at %s\n", kStubsLLPath);
        return 1;
    }
    if (ir.size() > kIRSizeSanityBoundBytes) {
        std::fprintf(stderr,
                     "FAIL: IR size %zu > sanity bound %zu bytes "
                     "(check fixture for umbrella include or backend TU).\n",
                     ir.size(), kIRSizeSanityBoundBytes);
        return 1;
    }
    const auto forbidden_hits = find_forbidden_calls(ir);
    if (!forbidden_hits.empty()) {
        std::fprintf(stderr,
                     "FAIL: %zu call/invoke in %s reference the deleted "
                     "W3.4 detail namespace:\n",
                     forbidden_hits.size(), kStubsLLPath);
        for (auto ln : forbidden_hits) std::fprintf(stderr, "  line %zu\n", ln);
        return 1;
    }
    const auto fns = split_functions(ir);
    if (fns.empty()) {
        std::fprintf(stderr,
                     "FAIL: parsed zero functions from %s\n", kStubsLLPath);
        return 1;
    }
    std::vector<std::string> bad_members;
    std::size_t scanned = 0;
    for (const auto& fn : fns) {
        if (!is_qint_member(fn.name)) continue;
        if (is_classical_value(fn.name)) continue;
        ++scanned;
        if (body_has_gep_load_on_qint(fn.body)) bad_members.push_back(fn.name);
    }
    if (scanned == 0) {
        std::fprintf(stderr,
                     "FAIL: scanned zero qint members in %s -- fixture "
                     "must instantiate at least default ctor + implicit ops\n",
                     kStubsLLPath);
        return 1;
    }
    if (!bad_members.empty()) {
        std::fprintf(stderr,
                     "FAIL: %zu qint member(s) load from value_ field "
                     "(W3.3 / G8 forbids on every body except classical_value):\n",
                     bad_members.size());
        for (const auto& name : bad_members) std::fprintf(stderr, "  %s\n", name.c_str());
        return 1;
    }
    std::fprintf(stderr,
                 "PASS: %zu function(s) parsed, %zu qint member(s) clean; "
                 "IR %zu bytes under %zu cap.\n",
                 fns.size(), scanned, ir.size(), kIRSizeSanityBoundBytes);
    return 0;
}
