// emitter.cpp — implementation of the M9 C++ emitter.
//
// Flow
// ----
// 1. For each UncomputeInsertion in the list, call InsertTextBefore on the
//    Rewriter. We iterate in REVERSE of M8's output order; see the "Why
//    reverse iteration?" block below for the Rewriter-semantics reasoning.
// 2. Ask the Rewriter for the main file's buffer and serialize it into a
//    std::string via raw_string_ostream.
// 3. Prepend the two-line idempotency header so the transpiler can
//    recognize its own output on a subsequent run (PRD AC #5).
// 4. Write the final bytes to disk via the M4 io helpers, mirroring the
//    source subtree under `output_dir` exactly as the identity copy path
//    in main.cpp already does for non-transpiled files.
//
// Why reverse iteration?
// ----------------------
// M8 hands us insertions in LIFO order: for a scope with forward ops
// [op0, op1, ..., opN] the list is [opN_ins, ..., op1_ins, op0_ins]. The
// reason is correctness — at runtime, the most recently computed
// intermediate must be uncomputed first.
//
// clang::Rewriter::InsertTextBefore places NEW text before any other text
// previously inserted at the same SourceLocation. So if we iterated the
// M8 list in forward order:
//
//     InsertTextBefore(close_brace, "uncompute opN")   // buffer: ...opN}
//     InsertTextBefore(close_brace, "uncompute opN-1") // buffer: ...opN-1 opN}
//     ...
//     InsertTextBefore(close_brace, "uncompute op0")   // buffer: ...op0 op1 ... opN}
//
// the final source-text order would be `op0, op1, ..., opN` — forward
// order, which is the opposite of what uncomputation requires.
//
// Iterating M8's list in REVERSE fixes this:
//
//     InsertTextBefore(close_brace, "uncompute op0")   // buffer: ...op0}
//     InsertTextBefore(close_brace, "uncompute op1")   // buffer: ...op1 op0}
//     ...
//     InsertTextBefore(close_brace, "uncompute opN")   // buffer: ...opN ... op1 op0}
//
// Final source order: `opN, ..., op1, op0` — reverse of forward, which is
// the exact LIFO execution order the uncompute pass is built around.
//
// For the MVP single-op-per-scope case this distinction is invisible;
// the reverse iteration is a future-proofing step so the moment M8 feeds
// us two ops in one scope the test immediately catches an ordering bug.

#include "sturm/transpile/emitter.hpp"

#include "sturm/transpile/io.hpp"

#include "clang/Basic/FileEntry.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Rewrite/Core/RewriteBuffer.h"
#include "clang/Rewrite/Core/Rewriter.h"
#include "llvm/Support/raw_os_ostream.h"
#include "llvm/Support/raw_ostream.h"

#include <cctype>
#include <cstdio>
#include <filesystem>
#include <sstream>
#include <string>
#include <string_view>
#include <vector>

namespace fs = std::filesystem;

namespace sturm::transpile {

// ── Pure string helpers (logically belong to M5 skip module) ─────────────────

std::string idempotency_header(std::string_view source_path) {
    // Exact two-line canonical format. See header doc for rationale and
    // the ASCII-hyphen rendering of the em-dash.
    std::string out;
    out.reserve(80 + source_path.size());
    out.append("// AUTO-GENERATED by sturm-transpile -- do not edit\n");
    out.append("// Source: ");
    out.append(source_path);
    out.push_back('\n');
    return out;
}

namespace {

// Return true if `line` is empty or contains only ASCII whitespace.
bool is_blank_line(std::string_view line) {
    for (char c : line) {
        // unsigned char cast avoids UB on platforms where char is signed.
        if (!std::isspace(static_cast<unsigned char>(c))) return false;
    }
    return true;
}

// Split `head` into lines on '\n' and return a view over the first
// non-blank line. Returns empty string_view if every line is blank.
std::string_view first_nonblank_line(std::string_view head) {
    std::size_t pos = 0;
    while (pos < head.size()) {
        std::size_t nl = head.find('\n', pos);
        std::size_t end = (nl == std::string_view::npos) ? head.size() : nl;
        std::string_view line = head.substr(pos, end - pos);
        if (!is_blank_line(line)) return line;
        if (nl == std::string_view::npos) break;
        pos = nl + 1;
    }
    return {};
}

} // namespace

bool should_skip(std::string_view head) {
    // The two recognized sentinels. Exact line-prefix match (no trailing
    // whitespace tolerated beyond what starts the match); partial or
    // garbled markers are treated as non-skip so users don't get mystery
    // pass-throughs.
    static constexpr std::string_view kSkipMarker =
        "// sturm-transpile: skip";
    static constexpr std::string_view kAutoGen =
        "// AUTO-GENERATED by sturm-transpile";

    std::string_view line = first_nonblank_line(head);
    if (line.empty()) return false;
    if (line.substr(0, kSkipMarker.size()) == kSkipMarker) return true;
    if (line.substr(0, kAutoGen.size()) == kAutoGen) return true;
    return false;
}

// ── emit() ────────────────────────────────────────────────────────────────────

bool emit(const clang::SourceManager& sm,
          clang::Rewriter& rw,
          const std::vector<UncomputeInsertion>& insertions,
          std::string_view source_path,
          std::string_view output_dir) {
    // Step 1: apply every insertion. Reverse iteration — see file-level
    // comment for why this is correct and why forward iteration would be
    // wrong for multi-op scopes.
    for (auto it = insertions.rbegin(); it != insertions.rend(); ++it) {
        const auto& ins = *it;
        if (!ins.insert_before.isValid()) {
            // Defensive: a malformed M8 output with an invalid location is
            // not representable by the Rewriter. Skip rather than abort so
            // a single bad insertion doesn't discard the whole run.
            continue;
        }
        // InsertTextBefore puts `ins.code` directly before the anchor loc.
        // Returns true on failure (unrewritable location) — we ignore the
        // return so partial insertions still propagate to disk; an
        // unrewritable location is already a bug elsewhere and swallowing
        // the specific record here keeps the rest of the output intact.
        (void)rw.InsertTextBefore(ins.insert_before, ins.code);
    }

    // Step 2: serialize the rewritten main-file buffer into a string.
    clang::FileID main_id = sm.getMainFileID();
    const clang::RewriteBuffer* buf = rw.getRewriteBufferFor(main_id);

    std::string body;
    if (buf) {
        llvm::raw_string_ostream os(body);
        buf->write(os);
        os.flush();
    } else {
        // No edits recorded (insertions empty or all filtered) — fall back
        // to the original main-file contents so we still emit a valid copy.
        clang::OptionalFileEntryRef fe = sm.getFileEntryRefForID(main_id);
        llvm::StringRef contents = sm.getBufferData(main_id);
        body.assign(contents.data(), contents.size());
        (void)fe;
    }

    // Step 3: prepend the idempotency header.
    std::string out;
    out.reserve(body.size() + 128);
    out.append(idempotency_header(source_path));
    out.append(body);

    // Step 4: write to <output_dir>/<resolved path>. Resolve via the same
    // helper the identity-copy path uses so the layout rules are identical.
    fs::path dst = sturm::transpile::resolve_output_path(
        fs::path(source_path), fs::path(output_dir));
    if (!sturm::transpile::write_file(dst, out)) {
        std::fprintf(stderr,
                     "sturm-transpile: error: could not write output %s\n",
                     dst.string().c_str());
        return false;
    }
    return true;
}

} // namespace sturm::transpile
