// skip.cpp — implementation of the M5 skip / idempotency helpers.
//
// Pure string manipulation, zero LibTooling dependency. See skip.hpp for
// the contract and the rationale for the two-ASCII-hyphen rendering of
// the PRD's em-dash.

#include "sturm/transpile/skip.hpp"

#include <cctype>
#include <cstddef>
#include <string>
#include <string_view>

namespace sturm::transpile {

std::string idempotency_header(std::string_view source_path) {
    // Exact canonical two-line format. Any change here must be mirrored in
    // the skip detection sentinel below and in the M9 golden snapshot.
    std::string out;
    out.reserve(80 + source_path.size());
    out.append("// AUTO-GENERATED by sturm-transpile -- do not edit\n");
    out.append("// Source: ");
    out.append(source_path);
    out.push_back('\n');
    return out;
}

namespace {

// Return true if `line` is empty or contains only ASCII whitespace.
bool is_blank_line(std::string_view line) {
    for (char c : line) {
        // unsigned char cast avoids UB on platforms where char is signed.
        if (!std::isspace(static_cast<unsigned char>(c))) return false;
    }
    return true;
}

// Split `head` into lines on '\n' and return a view over the first
// non-blank line. Returns empty string_view if every line is blank.
std::string_view first_nonblank_line(std::string_view head) {
    std::size_t pos = 0;
    while (pos < head.size()) {
        std::size_t nl = head.find('\n', pos);
        std::size_t end = (nl == std::string_view::npos) ? head.size() : nl;
        std::string_view line = head.substr(pos, end - pos);
        if (!is_blank_line(line)) return line;
        if (nl == std::string_view::npos) break;
        pos = nl + 1;
    }
    return {};
}

} // namespace

bool should_skip(std::string_view head) {
    // The two recognized sentinels. Exact line-prefix match (no trailing
    // whitespace tolerated beyond what starts the match); partial or
    // garbled markers are treated as non-skip so users don't get mystery
    // pass-throughs.
    static constexpr std::string_view kSkipMarker =
        "// sturm-transpile: skip";
    static constexpr std::string_view kAutoGen =
        "// AUTO-GENERATED by sturm-transpile";

    std::string_view line = first_nonblank_line(head);
    if (line.empty()) return false;
    if (line.substr(0, kSkipMarker.size()) == kSkipMarker) return true;
    if (line.substr(0, kAutoGen.size()) == kAutoGen) return true;
    return false;
}

} // namespace sturm::transpile
