# verify_artifacts.cmake — M10 ctest probe for build-time invariants.
#
# Invoked by tests/transpiler/test_cmake_glue/CMakeLists.txt with:
#   -DGEN_FILE=<abs path>       — where the transpiler is expected to write
#                                 (under ${CMAKE_BINARY_DIR}/sturm_gen/...)
#   -DSOURCE_FILE=<abs path>    — the original fixture source
#
# Contract:
#   - GEN_FILE must exist.
#   - Its first line must start with "// AUTO-GENERATED by sturm-transpile".
#   - It must preserve the STURM_GLUE_FIXTURE_MARKER identifier somewhere
#     in its body (proves the transpiler does not drop user code even when
#     no quantum ops were matched).
#
# Script exits 0 on success, 1 on any contract violation.

if(NOT DEFINED GEN_FILE)
    message(FATAL_ERROR "verify_artifacts: GEN_FILE not set")
endif()
if(NOT DEFINED SOURCE_FILE)
    message(FATAL_ERROR "verify_artifacts: SOURCE_FILE not set")
endif()

# Sanity: the source must always exist.
if(NOT EXISTS "${SOURCE_FILE}")
    message(FATAL_ERROR
        "verify_artifacts: SOURCE_FILE does not exist: ${SOURCE_FILE}")
endif()

if(NOT EXISTS "${GEN_FILE}")
    message(FATAL_ERROR
        "verify_artifacts: generated file is missing at ${GEN_FILE}. "
        "The add_quantum_executable() helper did not emit a transpile "
        "custom-command, or it emitted one with the wrong output path.")
endif()

# Read the generated file and verify the AUTO-GENERATED header and
# preservation of the fixture body.
file(READ "${GEN_FILE}" gen_contents)

string(FIND "${gen_contents}"
            "// AUTO-GENERATED by sturm-transpile" hdr_pos)
if(hdr_pos LESS 0)
    message(FATAL_ERROR
        "verify_artifacts: generated file ${GEN_FILE} is missing the "
        "AUTO-GENERATED sentinel. Contents begin with:\n"
        "${gen_contents}")
endif()

# The sentinel must be at the very top (modulo optional leading blank
# lines) — otherwise a future re-run of the transpiler on this output
# would double-emit the header and break PRD AC #5 (idempotency).
# We accept a zero-offset match as the canonical case.
if(NOT hdr_pos EQUAL 0)
    message(WARNING
        "verify_artifacts: AUTO-GENERATED sentinel is not at offset 0 "
        "(found at ${hdr_pos}). This may break idempotency.")
endif()

string(FIND "${gen_contents}"
            "sturm_glue_fixture_marker" marker_pos)
if(marker_pos LESS 0)
    message(FATAL_ERROR
        "verify_artifacts: generated file ${GEN_FILE} is missing the "
        "STURM_GLUE_FIXTURE_MARKER token. Transpiler dropped the "
        "fixture body.")
endif()

message(STATUS
    "verify_artifacts: OK — ${GEN_FILE} has header and body.")
