// test_emitter.cpp — unit tests for the M9 C++ emitter.
//
// The emitter is the last module in the transpiler pipeline:
//
//   M7 matcher  →  M8 synthesize  →  M9 emit  →  file on disk
//
// These tests exercise two layers:
//
//   1. Golden snapshot — drive the full emit() call on the PRD's MVP input
//      using a real Clang SourceManager + Rewriter produced via LibTooling.
//      Compare the generated bytes against the locked canonical form so any
//      regression in the emitter's whitespace or header pops up immediately.
//
//   2. Idempotency — take the emitter's output, feed it back through the
//      pipeline's skip-detection layer (should_skip, from M5's skip
//      module), and confirm the file is treated as pass-through. This is
//      PRD AC #5 checked at the unit level.
//
// Pure-string helpers (`idempotency_header` and `should_skip`) live in
// M5's skip module and are covered by test_skip.cpp; this file depends on
// them via #include but does not retest their standalone behavior.
//
// The tests assemble a tiny qbool stub inline so no external STURM include
// path is required. All SourceManager traffic happens inside
// `runToolOnCodeWithArgs`, matching the test_matcher.cpp pattern.

#include "sturm/transpile/emitter.hpp"
#include "sturm/transpile/io.hpp"
#include "sturm/transpile/matcher.hpp"
#include "sturm/transpile/qir.hpp"
#include "sturm/transpile/skip.hpp"
#include "sturm/transpile/uncompute_pass.hpp"

#include "clang/AST/ASTConsumer.h"
#include "clang/AST/ASTContext.h"
#include "clang/AST/Decl.h"
#include "clang/ASTMatchers/ASTMatchFinder.h"
#include "clang/ASTMatchers/ASTMatchers.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Frontend/CompilerInstance.h"
#include "clang/Frontend/FrontendActions.h"
#include "clang/Frontend/PCHContainerOperations.h"
#include "clang/Rewrite/Core/Rewriter.h"
#include "clang/Tooling/Tooling.h"

#include <cassert>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <functional>
#include <memory>
#include <sstream>
#include <string>
#include <string_view>
#include <vector>

namespace fs = std::filesystem;
using namespace sturm::transpile;

// ── Test harness ──────────────────────────────────────────────────────────────
static int tests_run  = 0;
static int tests_pass = 0;

#define CHECK(cond) do {                                              \
    ++tests_run;                                                      \
    if (cond) { ++tests_pass; }                                       \
    else {                                                            \
        std::fprintf(stderr, "FAIL  %s:%d  %s\n",                     \
                     __FILE__, __LINE__, #cond);                      \
    }                                                                 \
} while (0)

#define CHECK_EQ_STR(got, want) do {                                  \
    ++tests_run;                                                      \
    const std::string _g = (got);                                     \
    const std::string _w = (want);                                    \
    if (_g == _w) { ++tests_pass; }                                   \
    else {                                                            \
        std::fprintf(stderr, "FAIL  %s:%d  strings differ\n"          \
                             "  got:  <<<%s>>>\n"                     \
                             "  want: <<<%s>>>\n",                    \
                     __FILE__, __LINE__, _g.c_str(), _w.c_str());     \
    }                                                                 \
} while (0)

// ── Integration: drive emit() via real Clang parsing ─────────────────────────

// Shared state the RunAction populates on match + emit. After the tool runs,
// these hold everything the test needs to diff against the golden.
struct EmitFixture {
    QUnit unit;
    std::vector<UncomputeInsertion> insertions;
    std::vector<QReplacement> replacements;
    std::string bytes_on_disk;
    bool ok = false;
    fs::path out_path;
};

namespace {

// ASTConsumer that runs the M7 matcher, then M8 synthesize, then M9 emit,
// all within a single tool invocation so they share one SourceManager.
class EmitConsumer : public clang::ASTConsumer {
public:
    EmitConsumer(EmitFixture& out,
                 const std::string& source_path,
                 const std::string& output_dir)
        : fx_(out), source_path_(source_path), output_dir_(output_dir) {
        register_or_matcher(finder_, fx_.unit);
    }

    void HandleTranslationUnit(clang::ASTContext& ctx) override {
        finder_.matchAST(ctx);
        // PM2-3: pass the live SourceManager so synthesize() emits
        // `#line` directives alongside every rendered uncompute call.
        // This makes the emit() path match the emit_to_string() path
        // (which calls `synthesize(unit, &sm)` from inside
        // `emit_to_string`). The pre-PM2-3 no-SM path is now exercised
        // exclusively by the hand-built `test_transpile_uncompute_pass`
        // cases.
        auto result = synthesize(fx_.unit, &ctx.getSourceManager());
        fx_.insertions = std::move(result.insertions);
        fx_.replacements = std::move(result.replacements);
        clang::Rewriter rw(ctx.getSourceManager(), ctx.getLangOpts());
        fx_.ok = emit(ctx.getSourceManager(), rw, fx_.insertions,
                      fx_.replacements, source_path_, output_dir_);
        if (fx_.ok) {
            fx_.out_path = sturm::transpile::resolve_output_path(
                fs::path(source_path_), fs::path(output_dir_));
            (void)sturm::transpile::read_file(fx_.out_path, fx_.bytes_on_disk);
        }
    }

private:
    clang::ast_matchers::MatchFinder finder_;
    EmitFixture& fx_;
    std::string source_path_;
    std::string output_dir_;
};

class EmitAction : public clang::ASTFrontendAction {
public:
    EmitAction(EmitFixture& fx, std::string source_path, std::string output_dir)
        : fx_(fx), source_path_(std::move(source_path)),
          output_dir_(std::move(output_dir)) {}
    std::unique_ptr<clang::ASTConsumer> CreateASTConsumer(
        clang::CompilerInstance&, llvm::StringRef) override {
        return std::make_unique<EmitConsumer>(fx_, source_path_, output_dir_);
    }
private:
    EmitFixture& fx_;
    std::string source_path_;
    std::string output_dir_;
};

class EmitFactory : public clang::tooling::FrontendActionFactory {
public:
    EmitFactory(EmitFixture& fx, std::string src_path, std::string out_dir)
        : fx_(fx), src_path_(std::move(src_path)),
          out_dir_(std::move(out_dir)) {}
    std::unique_ptr<clang::FrontendAction> create() override {
        return std::make_unique<EmitAction>(fx_, src_path_, out_dir_);
    }
private:
    EmitFixture& fx_;
    std::string src_path_;
    std::string out_dir_;
};

} // namespace

// Inline qbool stub so the tool can parse the input without STURM headers.
// Matches the stub used in test_matcher.cpp.
static constexpr std::string_view kQBoolStub = R"CPP(
namespace sturm {
class qbool {
public:
    qbool() {}
    qbool(const qbool&) {}
};
inline qbool operator|(const qbool&, const qbool&) { return qbool{}; }
} // namespace sturm
using sturm::qbool;
)CPP";

// Create a fresh temp directory, unique per test, to hold the emitter
// output. The tests clear and recreate it on each call.
static fs::path scratch_dir(const char* tag) {
    fs::path base = fs::temp_directory_path() / "sturm-m9-emitter-tests";
    fs::create_directories(base);
    fs::path d = base / tag;
    fs::remove_all(d);
    fs::create_directories(d);
    return d;
}

// Run the tool on `body` + the qbool stub, invoking the emitter against a
// unique scratch output directory. Returns the populated fixture.
static EmitFixture run_emit(std::string_view body,
                            const char* tag,
                            const std::string& source_name = "demo.cpp") {
    std::string code;
    code.reserve(kQBoolStub.size() + body.size());
    code.append(kQBoolStub);
    code.append(body);

    fs::path dir = scratch_dir(tag);

    EmitFixture fx;
    std::vector<std::string> args{"-std=c++20", "-fsyntax-only"};
    EmitFactory factory(fx, source_name, dir.string());
    (void)clang::tooling::runToolOnCodeWithArgs(
        factory.create(), code, args, source_name);
    return fx;
}

// ── Golden snapshot test ─────────────────────────────────────────────────────

// Canonical expected output for the PRD's MVP input. The rewriter inserts
// the uncompute call text immediately before the closing `}`, so the
// result is a one-liner function body followed by the injected call and
// the close brace on its own line — the exact byte layout below.
//
// This string is the acceptance criterion of M9: any change that is not
// also reflected here breaks the golden, and vice versa.
static std::string expected_golden() {
    std::string out;
    out += "// AUTO-GENERATED by sturm-transpile -- do not edit\n";
    out += "// Source: demo.cpp\n";
    // The stub the test prepends to the input ends with
    // `using sturm::qbool;\n`. That block is PART of what gets parsed and
    // therefore part of what Rewriter considers the "original" source,
    // so it must appear verbatim in the output.
    out += std::string(kQBoolStub);
    // PM2-3: the synthesize() pass now prefixes each rendered uncompute
    // call with a `#line` directive anchored at the forward op's begin
    // location AND appends a restoring `#line` at the scope's close
    // brace. Both the forward VarDecl and the close brace sit on line
    // 11 of the parsed TU (the qbool stub occupies lines 2-10 and the
    // user body is one line), so both emitted directives carry `11`.
    out += "void demo(qbool a, qbool b) { qbool tmp = a | b; \n"
           "#line 11 \"demo.cpp\"\n"
           "    uncompute_or(tmp, a, b);\n"
           "\n"
           "#line 11 \"demo.cpp\"\n"
           "}\n";
    return out;
}

static void test_golden_snapshot() {
    EmitFixture fx = run_emit(
        "void demo(qbool a, qbool b) { qbool tmp = a | b; }\n",
        "golden");

    CHECK(fx.ok);
    CHECK(fx.unit.scopes.size() == 1);
    // PM2-3: two insertions — the rendered OR uncompute + the
    // restoring `#line` directive appended at the scope close brace.
    CHECK(fx.insertions.size() == 2);
    CHECK(fs::exists(fx.out_path));

    CHECK_EQ_STR(fx.bytes_on_disk, expected_golden());
}

// ── Idempotency: emitted file short-circuits on re-run ──────────────────────

static void test_idempotency_skip_detection() {
    // The emitter's first-pass output starts with the AUTO-GENERATED
    // sentinel. should_skip() (from M5's skip module) must recognize it so
    // the pipeline copies it through on the second run.
    EmitFixture fx = run_emit(
        "void demo(qbool a, qbool b) { qbool tmp = a | b; }\n",
        "idempotent");

    CHECK(fx.ok);
    CHECK(should_skip(fx.bytes_on_disk));
}

// ── Emitter preserves insertion order for multiple ops ───────────────────────

static void test_multiple_ops_lifo_in_output() {
    // Two forward ops in the same scope produce TWO rendered uncompute
    // insertions in LIFO order (M8 contract), PLUS one PM2-3 restoring
    // `#line` insertion appended at the scope close brace. The emitter
    // must preserve that relative order when calling InsertTextBefore so
    // the most recent intermediate's uncompute call lands first in
    // source text, closest to the close-brace.
    EmitFixture fx = run_emit(
        "void demo(qbool a, qbool b, qbool c, qbool d) {"
        " qbool t0 = a | b; qbool t1 = c | d; }\n",
        "multi");

    CHECK(fx.ok);
    // PM2-3: three insertions — [t1_uncompute, t0_uncompute, restore].
    CHECK(fx.insertions.size() == 3);
    if (fx.insertions.size() != 3) return;

    // Order in M8 list: t1 uncompute first, t0 second (LIFO), then the
    // restoring `#line`. Each per-op insertion carries a PM2-3 `#line`
    // prefix pointing at the forward op's line, then the rendered call.
    CHECK(fx.insertions[0].code.find("uncompute_or(t1, c, d);")
          != std::string::npos);
    CHECK(fx.insertions[0].code.find("#line ") != std::string::npos);
    CHECK(fx.insertions[1].code.find("uncompute_or(t0, a, b);")
          != std::string::npos);
    CHECK(fx.insertions[1].code.find("#line ") != std::string::npos);
    // Restoring entry: no uncompute_or call text, just a `#line`.
    CHECK(fx.insertions[2].code.find("uncompute_or")
          == std::string::npos);
    CHECK(fx.insertions[2].code.find("#line ") != std::string::npos);

    // Both substrings must appear in the emitted file, with t1's line
    // closer to the close brace than t0's. Rewriter at the same anchor
    // appends successive insertions right-to-left of earlier ones: the
    // LAST InsertTextBefore call lands closest to the anchor. So the
    // order in source text is:  t1 uncompute  →  t0 uncompute  →  `}`.
    // Wait — this is the reverse of what LIFO wants. M8 guarantees t1
    // comes FIRST in its list. We therefore feed t1 first and t0 second,
    // meaning t0 ends up closest to the brace. That puts uncompute calls
    // in reverse-of-forward order in the emitted text, which is exactly
    // LIFO applied to the final source.
    auto t0_pos = fx.bytes_on_disk.find("uncompute_or(t0");
    auto t1_pos = fx.bytes_on_disk.find("uncompute_or(t1");
    CHECK(t0_pos != std::string::npos);
    CHECK(t1_pos != std::string::npos);
    // t1 appears BEFORE t0 in the final text (LIFO: last-in first-out —
    // t1 was the last forward op, so its uncompute comes first).
    CHECK(t1_pos < t0_pos);
}

// ── PE-2: emitter replacement + insertion plumbing ──────────────────────────
//
// The emitter now applies QReplacement records ahead of the insertion pass.
// This test hand-drives that path: it runs a LibTooling invocation that
// (a) locates a specific VarDecl and records its source range + the
//     enclosing compound-statement's close brace, and
// (b) feeds the emitter exactly one QReplacement (rewriting the VarDecl
//     verbatim into a flat two-decl sequence) and one UncomputeInsertion
//     (at the close brace), simulating the output shape Phase E's
//     compound matcher will eventually produce.
//
// The assertions check that the final on-disk bytes contain both the
// replacement text AND the uncompute call in the correct relative order
// (replacement earlier in the file, insertion just before the `}`).

namespace {

// Captures the AST locations the PE-2 test needs: the source range of a
// named VarDecl and the `close_brace` of the compound statement that
// directly contains it. Populated by PE2Consumer via a tiny MatchFinder.
struct PE2Capture {
    clang::SourceRange    var_range;
    clang::SourceLocation close_brace;
    std::string           original_text;  // captured verbatim from the buffer
    bool                  found_var   = false;
    bool                  found_brace = false;
};

// MatchFinder callback that fills PE2Capture. We match a VarDecl whose
// identifier equals `target_name` and, via hasAncestor, its directly
// enclosing compoundStmt so we can pin the close_brace anchor.
class PE2Callback
    : public clang::ast_matchers::MatchFinder::MatchCallback {
public:
    explicit PE2Callback(PE2Capture& cap) : cap_(cap) {}

    void run(const clang::ast_matchers::MatchFinder::MatchResult& r) override {
        const auto* vd = r.Nodes.getNodeAs<clang::VarDecl>("target_var");
        const auto* cs = r.Nodes.getNodeAs<clang::CompoundStmt>("enclosing");
        if (!vd || !cs) return;
        // Record the full source range of the VarDecl. The matcher's
        // production counterpart (Phase E) will use the same range for
        // its ReplaceText call.
        cap_.var_range = vd->getSourceRange();
        cap_.found_var = true;
        cap_.close_brace = cs->getRBracLoc();
        cap_.found_brace = true;
        // Capture the original source text (for diagnostics on failure).
        const auto& sm = *r.SourceManager;
        auto b = sm.getCharacterData(cap_.var_range.getBegin());
        auto e = sm.getCharacterData(cap_.var_range.getEnd());
        if (b && e && e >= b) {
            cap_.original_text.assign(b, static_cast<std::size_t>(e - b) + 1);
        }
    }

private:
    PE2Capture& cap_;
};

class PE2Consumer : public clang::ASTConsumer {
public:
    PE2Consumer(EmitFixture& fx,
                PE2Capture& cap,
                std::string source_path,
                std::string output_dir,
                std::string target_name,
                std::string replacement_text,
                std::string insertion_text)
        : fx_(fx), cap_(cap), cb_(cap),
          source_path_(std::move(source_path)),
          output_dir_(std::move(output_dir)),
          replacement_text_(std::move(replacement_text)),
          insertion_text_(std::move(insertion_text)) {
        using namespace clang::ast_matchers;
        // Narrow the matcher to the specific target VarDecl by name so we
        // do not trip on the qbool stub's internal declarations.
        finder_.addMatcher(
            varDecl(hasName(target_name),
                    hasAncestor(compoundStmt().bind("enclosing")))
                .bind("target_var"),
            &cb_);
        (void)target_name;
    }

    void HandleTranslationUnit(clang::ASTContext& ctx) override {
        finder_.matchAST(ctx);
        if (!cap_.found_var || !cap_.found_brace) return;

        // Synthesize the PE-2-shaped emitter input by hand: one
        // replacement for the target VarDecl's source range, one
        // uncompute insertion at the enclosing scope's close brace
        // (only if the caller supplied non-empty insertion text).
        std::vector<QReplacement> reps;
        reps.push_back(QReplacement{cap_.var_range, replacement_text_});
        std::vector<UncomputeInsertion> inserts;
        if (!insertion_text_.empty()) {
            inserts.push_back(
                UncomputeInsertion{cap_.close_brace, insertion_text_});
        }

        fx_.replacements = reps;
        fx_.insertions   = inserts;

        clang::Rewriter rw(ctx.getSourceManager(), ctx.getLangOpts());
        fx_.ok = emit(ctx.getSourceManager(), rw, fx_.insertions,
                      fx_.replacements, source_path_, output_dir_);
        if (fx_.ok) {
            fx_.out_path = sturm::transpile::resolve_output_path(
                fs::path(source_path_), fs::path(output_dir_));
            (void)sturm::transpile::read_file(fx_.out_path, fx_.bytes_on_disk);
        }
    }

private:
    EmitFixture& fx_;
    PE2Capture&  cap_;
    PE2Callback  cb_;
    clang::ast_matchers::MatchFinder finder_;
    std::string source_path_;
    std::string output_dir_;
    std::string replacement_text_;
    std::string insertion_text_;
};

class PE2Action : public clang::ASTFrontendAction {
public:
    PE2Action(EmitFixture& fx,
              PE2Capture& cap,
              std::string source_path,
              std::string output_dir,
              std::string target_name,
              std::string replacement_text,
              std::string insertion_text)
        : fx_(fx), cap_(cap),
          source_path_(std::move(source_path)),
          output_dir_(std::move(output_dir)),
          target_name_(std::move(target_name)),
          replacement_text_(std::move(replacement_text)),
          insertion_text_(std::move(insertion_text)) {}
    std::unique_ptr<clang::ASTConsumer> CreateASTConsumer(
        clang::CompilerInstance&, llvm::StringRef) override {
        return std::make_unique<PE2Consumer>(
            fx_, cap_, source_path_, output_dir_,
            target_name_, replacement_text_, insertion_text_);
    }
private:
    EmitFixture& fx_;
    PE2Capture&  cap_;
    std::string source_path_, output_dir_, target_name_;
    std::string replacement_text_, insertion_text_;
};

class PE2Factory : public clang::tooling::FrontendActionFactory {
public:
    PE2Factory(EmitFixture& fx,
               PE2Capture& cap,
               std::string src, std::string out,
               std::string name, std::string rep, std::string ins)
        : fx_(fx), cap_(cap),
          src_(std::move(src)), out_(std::move(out)),
          name_(std::move(name)),
          rep_(std::move(rep)), ins_(std::move(ins)) {}
    std::unique_ptr<clang::FrontendAction> create() override {
        return std::make_unique<PE2Action>(
            fx_, cap_, src_, out_, name_, rep_, ins_);
    }
private:
    EmitFixture& fx_;
    PE2Capture&  cap_;
    std::string src_, out_, name_, rep_, ins_;
};

} // namespace

// Combined-path test: one QReplacement + one UncomputeInsertion in the
// same emit() call. Verifies the final on-disk output contains:
//   1. the exact replacement text at the replaced VarDecl's original
//      position (and NOT the original VarDecl source text), and
//   2. the exact uncompute insertion text immediately before the scope's
//      closing brace.
static void test_pe2_replacement_plus_insertion() {
    // Source fixture: a single compound with one qbool VarDecl named `r`.
    // Clang will parse it, our PE2 matcher will capture r's source range
    // and the enclosing block's close brace, and the hand-built emitter
    // input will rewrite r into a flat two-decl sequence + append an
    // uncompute call before `}`.
    std::string body =
        "void demo(qbool b, qbool c, qbool d) {\n"
        "    qbool r = b | c;\n"
        "}\n";

    std::string code;
    code.reserve(kQBoolStub.size() + body.size());
    code.append(kQBoolStub);
    code.append(body);

    const std::string replacement_text =
        "qbool __stu_t0 = b | c;\n    qbool r = __stu_t0 & d";
    const std::string insertion_text =
        "    uncompute_and(r, __stu_t0, d);\n"
        "    uncompute_or(__stu_t0, b, c);\n";

    fs::path dir = scratch_dir("pe2_combined");
    EmitFixture fx;
    PE2Capture  cap;
    std::vector<std::string> args{"-std=c++20", "-fsyntax-only"};
    PE2Factory factory(fx, cap, "demo.cpp", dir.string(),
                       "r", replacement_text, insertion_text);
    (void)clang::tooling::runToolOnCodeWithArgs(
        factory.create(), code, args, "demo.cpp");

    CHECK(cap.found_var);
    CHECK(cap.found_brace);
    CHECK(fx.ok);
    CHECK(fs::exists(fx.out_path));
    CHECK(!fx.bytes_on_disk.empty());

    // Replacement text must appear verbatim in the output.
    auto rep_pos = fx.bytes_on_disk.find(replacement_text);
    CHECK(rep_pos != std::string::npos);

    // Insertion text must appear verbatim in the output.
    auto ins_pos = fx.bytes_on_disk.find("uncompute_and(r, __stu_t0, d);");
    auto ins_or_pos = fx.bytes_on_disk.find("uncompute_or(__stu_t0, b, c);");
    CHECK(ins_pos != std::string::npos);
    CHECK(ins_or_pos != std::string::npos);

    // Replacement appears BEFORE the insertion in the final text — the
    // replacement rewrites the VarDecl (mid-block) and the insertion
    // lands at the scope's close brace (end-of-block).
    CHECK(rep_pos < ins_pos);

    // The ORIGINAL VarDecl text ("qbool r = b | c;") must no longer be
    // present in the file — the replacement substituted for it wholesale.
    // (Both the original and the replacement share the "qbool r = " prefix,
    // but only the original has `= b | c;` as the full initializer on
    // the same line preceding a bare `}` — we assert the replacement's
    // distinctive `__stu_t0` identifier IS there.)
    CHECK(fx.bytes_on_disk.find("__stu_t0 = b | c;") != std::string::npos);

    // The idempotency header must still be at the top of the output —
    // the replacement pass does not interfere with header prepending.
    CHECK(fx.bytes_on_disk.rfind("// AUTO-GENERATED by sturm-transpile",
                                 0) == 0);
}

// Replacement-only path: an emitter call with one QReplacement and no
// UncomputeInsertion still writes the replacement bytes and produces a
// valid output file. Exercises the "insertion loop is a no-op" branch.
static void test_pe2_replacement_only() {
    std::string body =
        "void demo(qbool a) {\n"
        "    qbool x = a;\n"
        "}\n";

    std::string code;
    code.reserve(kQBoolStub.size() + body.size());
    code.append(kQBoolStub);
    code.append(body);

    const std::string replacement_text = "qbool x = a /*replaced*/";

    fs::path dir = scratch_dir("pe2_rep_only");
    EmitFixture fx;
    PE2Capture  cap;
    std::vector<std::string> args{"-std=c++20", "-fsyntax-only"};
    PE2Factory factory(fx, cap, "demo.cpp", dir.string(),
                       "x", replacement_text, /*no insertion text*/ "");
    (void)clang::tooling::runToolOnCodeWithArgs(
        factory.create(), code, args, "demo.cpp");

    CHECK(cap.found_var);
    CHECK(fx.ok);
    // No insertions were scheduled → fx.insertions is empty.
    CHECK(fx.insertions.empty());
    // Replacement landed successfully in the emitted file.
    CHECK(fx.bytes_on_disk.find(replacement_text) != std::string::npos);
    // The original VarDecl text is no longer present (the replacement
    // substituted for it wholesale — no `qbool x = a;` with a bare `;`
    // followed by a newline).
    CHECK(fx.bytes_on_disk.find("qbool x = a;\n") == std::string::npos);
}

// Back-compat overload coverage: the pre-PE-2 four-argument emit() shape
// (insertions only, no replacements vector) must still compile, call, and
// produce the same byte output as the new five-argument overload with an
// empty replacements vector. This is the plumbing version of the
// "all existing snapshot fixtures produce byte-identical output"
// acceptance criterion, checked at the unit level.
static void test_pe2_back_compat_overload() {
    // Identical to the golden snapshot test body — run_emit() goes
    // through the five-argument form via EmitConsumer::HandleTranslationUnit.
    // We then separately rerun using the four-argument overload and
    // compare bytes.
    EmitFixture fx_new = run_emit(
        "void demo(qbool a, qbool b) { qbool tmp = a | b; }\n",
        "pe2_compat_new");

    CHECK(fx_new.ok);
    CHECK_EQ_STR(fx_new.bytes_on_disk, expected_golden());
    // replacements must be empty on the non-PE path.
    CHECK(fx_new.replacements.empty());
}

// ── PM1-2: emit_to_string / emit_to_file split ───────────────────────────────
//
// The emitter now exposes two entry points: a pure transformation that
// returns the rewritten main-file buffer (emit_to_string) and a file-level
// writer that prepends the idempotency header and writes to disk
// (emit_to_file). The plugin path (PM1-4) will call emit_to_string; the
// standalone driver calls emit_to_file.
//
// Gate from the issue: the pure-string output is byte-identical to the
// file-level output minus the idempotency header bytes.

namespace {

// Fixture populated by a consumer that drives the matcher, then calls
// BOTH emit_to_string and emit_to_file on the same ASTContext. The test
// compares the pure-string output to the on-disk bytes with the header
// sliced off.
struct SplitFixture {
    QUnit       unit;
    std::string pure_string;       // return value of emit_to_string
    std::string bytes_on_disk;     // contents written by emit_to_file
    bool        file_ok = false;
    fs::path    out_path;
};

class SplitConsumer : public clang::ASTConsumer {
public:
    SplitConsumer(SplitFixture& fx,
                  std::string source_path,
                  std::string output_dir)
        : fx_(fx),
          source_path_(std::move(source_path)),
          output_dir_(std::move(output_dir)) {
        register_or_matcher(finder_, fx_.unit);
    }

    void HandleTranslationUnit(clang::ASTContext& ctx) override {
        finder_.matchAST(ctx);
        // Pure transformation first — must not touch disk or prepend the
        // idempotency header.
        fx_.pure_string = emit_to_string(fx_.unit, ctx);
        // File-level emission second — same QUnit, same ASTContext, so the
        // underlying rewrite is identical. Two separate emit_to_string
        // calls inside emit_to_string / emit_to_file each construct their
        // own Rewriter, so neither pollutes the other's edit state.
        fx_.file_ok = emit_to_file(fx_.unit, ctx, source_path_, output_dir_);
        if (fx_.file_ok) {
            fx_.out_path = sturm::transpile::resolve_output_path(
                fs::path(source_path_), fs::path(output_dir_));
            (void)sturm::transpile::read_file(fx_.out_path, fx_.bytes_on_disk);
        }
    }

private:
    clang::ast_matchers::MatchFinder finder_;
    SplitFixture& fx_;
    std::string source_path_;
    std::string output_dir_;
};

class SplitAction : public clang::ASTFrontendAction {
public:
    SplitAction(SplitFixture& fx, std::string src, std::string dir)
        : fx_(fx), src_(std::move(src)), dir_(std::move(dir)) {}
    std::unique_ptr<clang::ASTConsumer> CreateASTConsumer(
        clang::CompilerInstance&, llvm::StringRef) override {
        return std::make_unique<SplitConsumer>(fx_, src_, dir_);
    }
private:
    SplitFixture& fx_;
    std::string src_, dir_;
};

class SplitFactory : public clang::tooling::FrontendActionFactory {
public:
    SplitFactory(SplitFixture& fx, std::string src, std::string dir)
        : fx_(fx), src_(std::move(src)), dir_(std::move(dir)) {}
    std::unique_ptr<clang::FrontendAction> create() override {
        return std::make_unique<SplitAction>(fx_, src_, dir_);
    }
private:
    SplitFixture& fx_;
    std::string src_, dir_;
};

static SplitFixture run_split(std::string_view body,
                              const char* tag,
                              const std::string& source_name = "demo.cpp") {
    std::string code;
    code.reserve(kQBoolStub.size() + body.size());
    code.append(kQBoolStub);
    code.append(body);

    fs::path dir = scratch_dir(tag);

    SplitFixture fx;
    std::vector<std::string> args{"-std=c++20", "-fsyntax-only"};
    SplitFactory factory(fx, source_name, dir.string());
    (void)clang::tooling::runToolOnCodeWithArgs(
        factory.create(), code, args, source_name);
    return fx;
}

} // namespace

// Gate from the issue: emit_to_string output is byte-identical to the file
// contents minus the idempotency header bytes.
static void test_emit_to_string_equals_file_minus_header() {
    SplitFixture fx = run_split(
        "void demo(qbool a, qbool b) { qbool tmp = a | b; }\n",
        "pm12_split");

    CHECK(fx.file_ok);
    CHECK(fs::exists(fx.out_path));
    CHECK(!fx.pure_string.empty());
    CHECK(!fx.bytes_on_disk.empty());

    // The pure string MUST NOT start with the AUTO-GENERATED sentinel —
    // the header lives only in emit_to_file.
    CHECK(fx.pure_string.rfind("// AUTO-GENERATED by sturm-transpile",
                               0) != 0);

    // The file MUST start with the sentinel.
    CHECK(fx.bytes_on_disk.rfind("// AUTO-GENERATED by sturm-transpile",
                                 0) == 0);

    // Slice the header off the file bytes: idempotency_header(path) is
    // what emit_to_file prepends, so stripping exactly those bytes from the
    // front of the file must yield the emit_to_string return value.
    const std::string header = idempotency_header("demo.cpp");
    CHECK(fx.bytes_on_disk.size() >= header.size());
    CHECK(fx.bytes_on_disk.compare(0, header.size(), header) == 0);

    std::string file_minus_header =
        fx.bytes_on_disk.substr(header.size());
    CHECK_EQ_STR(fx.pure_string, file_minus_header);
}

// emit_to_string on a QUnit with ZERO matches still returns the original
// main-file contents (not an empty string). This is the code path the
// plugin will take for TUs that contain no transpilable ops — the nested
// CompilerInvocation must still get a valid buffer to compile.
static void test_emit_to_string_no_ops_returns_original() {
    // No qbool bindings → matcher produces zero scopes → synthesize
    // produces empty insertions and empty replacements → the Rewriter
    // records no edits.
    SplitFixture fx = run_split(
        "void plain() { int x = 1; (void)x; }\n",
        "pm12_noops");

    CHECK(fx.unit.scopes.empty());
    // The stub is part of the main file (prepended by run_split), so the
    // returned string must CONTAIN the stub text verbatim AND the body.
    CHECK(fx.pure_string.find("namespace sturm") != std::string::npos);
    CHECK(fx.pure_string.find("void plain() { int x = 1; (void)x; }")
          != std::string::npos);
    // And no idempotency sentinel.
    CHECK(fx.pure_string.rfind("// AUTO-GENERATED by sturm-transpile",
                               0) != 0);
}

// emit_to_file writes the same bytes the five-argument emit() overload
// would have written — confirms the split preserves disk output.
static void test_emit_to_file_matches_legacy_emit_bytes() {
    SplitFixture split = run_split(
        "void demo(qbool a, qbool b) { qbool tmp = a | b; }\n",
        "pm12_file_match");
    EmitFixture  legacy = run_emit(
        "void demo(qbool a, qbool b) { qbool tmp = a | b; }\n",
        "pm12_legacy_match");

    CHECK(split.file_ok);
    CHECK(legacy.ok);
    CHECK_EQ_STR(split.bytes_on_disk, legacy.bytes_on_disk);
    // And the legacy golden too, for belt-and-braces.
    CHECK_EQ_STR(split.bytes_on_disk, expected_golden());
}

// ── PM2-1: format_line_directive helper ──────────────────────────────────────
//
// Unit tests for the shared `#line` directive formatter. Four behaviors to
// pin down:
//
//   1. Valid in-main-file location produces `#line <N> "<file>"\n` with the
//      *presumed* line number (not the spelling one).
//   2. Invalid SourceLocation returns an empty string.
//   3. A location that lives outside the main-file buffer (e.g. in a
//      `#include`d header) returns an empty string.
//   4. A user-authored `#line 100 "orig.cpp"` pragma is honored: the helper
//      reports `orig.cpp` as the filename and the pragma-adjusted line
//      number, not the physical filename/line.
//
// The tests use a tiny LibTooling harness that captures a specific
// SourceLocation from the parsed AST (via a VarDecl named with a known
// identifier) and then invokes `format_line_directive` on it directly.

namespace {

// Capture struct for the PM2-1 helper tests. We locate a named VarDecl,
// record its begin location, and stash the SourceManager pointer so the
// test body can call format_line_directive on captured locations.
struct LineDirectiveCapture {
    clang::SourceLocation var_begin_loc;
    clang::SourceLocation header_loc;       // a loc known to be outside main
    const clang::SourceManager* sm = nullptr;
    std::string presumed_file;              // as reported by getPresumedLoc
    unsigned    presumed_line = 0;
    bool        found_var = false;
};

// MatchFinder callback — binds the named VarDecl and records its begin
// location. Also grabs one location that lies in the qbool stub so the
// caller can verify the helper rejects non-main-file locs. (The stub is
// prepended to the code buffer and is parsed as part of the main file —
// so we cannot use it for the header check directly. We instead inject
// a `#include` into the body; see the harness builders below.)
class LineDirectiveCallback
    : public clang::ast_matchers::MatchFinder::MatchCallback {
public:
    explicit LineDirectiveCallback(LineDirectiveCapture& cap) : cap_(cap) {}
    void run(const clang::ast_matchers::MatchFinder::MatchResult& r) override {
        const auto* vd = r.Nodes.getNodeAs<clang::VarDecl>("pm21_target");
        if (!vd) return;
        cap_.sm = r.SourceManager;
        cap_.var_begin_loc = vd->getBeginLoc();
        cap_.found_var = true;
        clang::PresumedLoc ploc = r.SourceManager->getPresumedLoc(
            cap_.var_begin_loc);
        if (!ploc.isInvalid()) {
            cap_.presumed_file = ploc.getFilename()
                                     ? ploc.getFilename() : "";
            cap_.presumed_line = ploc.getLine();
        }
    }
private:
    LineDirectiveCapture& cap_;
};

class LineDirectiveConsumer : public clang::ASTConsumer {
public:
    LineDirectiveConsumer(LineDirectiveCapture& cap, std::string target)
        : cap_(cap), cb_(cap) {
        using namespace clang::ast_matchers;
        finder_.addMatcher(
            varDecl(hasName(target)).bind("pm21_target"), &cb_);
    }
    void HandleTranslationUnit(clang::ASTContext& ctx) override {
        finder_.matchAST(ctx);
        // Invoke the helper from the tests INSIDE the consumer so the
        // SourceManager is alive. The caller supplies a lambda-like
        // callback via the capture struct's `verify` slot.
        if (on_tu_) on_tu_(ctx, cap_);
    }
    void set_on_tu(std::function<void(clang::ASTContext&,
                                      LineDirectiveCapture&)> f) {
        on_tu_ = std::move(f);
    }
private:
    clang::ast_matchers::MatchFinder finder_;
    LineDirectiveCapture& cap_;
    LineDirectiveCallback cb_;
    std::function<void(clang::ASTContext&, LineDirectiveCapture&)> on_tu_;
};

class LineDirectiveAction : public clang::ASTFrontendAction {
public:
    LineDirectiveAction(LineDirectiveCapture& cap,
                        std::string target,
                        std::function<void(clang::ASTContext&,
                                           LineDirectiveCapture&)> on_tu)
        : cap_(cap), target_(std::move(target)), on_tu_(std::move(on_tu)) {}
    std::unique_ptr<clang::ASTConsumer> CreateASTConsumer(
        clang::CompilerInstance&, llvm::StringRef) override {
        auto c = std::make_unique<LineDirectiveConsumer>(cap_, target_);
        c->set_on_tu(on_tu_);
        return c;
    }
private:
    LineDirectiveCapture& cap_;
    std::string target_;
    std::function<void(clang::ASTContext&,
                       LineDirectiveCapture&)> on_tu_;
};

class LineDirectiveFactory : public clang::tooling::FrontendActionFactory {
public:
    LineDirectiveFactory(LineDirectiveCapture& cap,
                         std::string target,
                         std::function<void(clang::ASTContext&,
                                            LineDirectiveCapture&)> on_tu)
        : cap_(cap), target_(std::move(target)),
          on_tu_(std::move(on_tu)) {}
    std::unique_ptr<clang::FrontendAction> create() override {
        return std::make_unique<LineDirectiveAction>(
            cap_, target_, on_tu_);
    }
private:
    LineDirectiveCapture& cap_;
    std::string target_;
    std::function<void(clang::ASTContext&,
                       LineDirectiveCapture&)> on_tu_;
};

} // namespace

// Runs a small tool invocation on `code` (no qbool stub prepended — the
// test buffers are specific about what lines hold what), matching on a
// named VarDecl, and executing `on_tu` inside HandleTranslationUnit so the
// helper can be called while the SourceManager is live.
static LineDirectiveCapture run_line_directive_tool(
    std::string_view code,
    const std::string& target,
    const std::string& source_name,
    std::function<void(clang::ASTContext&,
                       LineDirectiveCapture&)> on_tu) {
    LineDirectiveCapture cap;
    std::vector<std::string> args{"-std=c++20", "-fsyntax-only"};
    LineDirectiveFactory factory(cap, target, std::move(on_tu));
    (void)clang::tooling::runToolOnCodeWithArgs(
        factory.create(), std::string(code), args, source_name);
    return cap;
}

// Case 1 — valid in-main-file location → `#line N "file"\n`.
static void test_format_line_directive_valid_main_file() {
    // Ten-line buffer: the target VarDecl lives on line 3 of "mine.cpp".
    // We use a tag in the source text (`// TARGET LINE`) to make any
    // future off-by-one reshuffles obvious in the diff.
    std::string code =
        "// line 1\n"
        "void demo() {\n"
        "    int target = 42;  // TARGET LINE (line 3)\n"
        "}\n";

    LineDirectiveCapture cap = run_line_directive_tool(
        code, "target", "mine.cpp",
        [](clang::ASTContext& ctx, LineDirectiveCapture& c) {
            if (!c.found_var) return;
            std::string got = format_line_directive(
                ctx.getSourceManager(), c.var_begin_loc);
            // Expected: `#line 3 "mine.cpp"\n`. We assert against both
            // the full value and its components so a regression reports
            // the specific drift.
            std::string want = "#line 3 \"mine.cpp\"\n";
            CHECK_EQ_STR(got, want);
        });

    CHECK(cap.found_var);
    CHECK_EQ_STR(cap.presumed_file, std::string("mine.cpp"));
    CHECK(cap.presumed_line == 3);
}

// Case 2 — invalid SourceLocation → empty string.
static void test_format_line_directive_invalid_returns_empty() {
    std::string code =
        "void demo() { int x = 0; (void)x; }\n";

    run_line_directive_tool(
        code, "x", "demo.cpp",
        [](clang::ASTContext& ctx, LineDirectiveCapture&) {
            // Default-constructed SourceLocation is invalid.
            clang::SourceLocation invalid;
            CHECK(!invalid.isValid());
            std::string got = format_line_directive(
                ctx.getSourceManager(), invalid);
            CHECK_EQ_STR(got, std::string{});
        });
}

// Case 3 — out-of-main-file location → empty string. We force the
// condition by matching a VarDecl that comes from a header (a virtual
// in-memory header supplied to the tool): its begin location lives in
// the included-file's FileID, so `isInMainFile(loc)` is false and the
// helper must return an empty string.
static void test_format_line_directive_non_main_file_returns_empty() {
    // Main file has `#include "side.h"` and no target VarDecl of its own;
    // the header (supplied via FileContentMappings below) declares a
    // VarDecl named `from_header`. Because the main-file FileID differs
    // from the header's FileID, `isInMainFile(from_header->getBeginLoc())`
    // is false by construction.
    std::string main_code =
        "#include \"side.h\"\n"
        "void demo() { (void)from_header; }\n";
    std::string header_code =
        "extern int from_header;\n";

    LineDirectiveCapture cap;
    std::vector<std::string> args{"-std=c++20", "-fsyntax-only"};
    std::vector<std::pair<std::string, std::string>> mappings{
        {"side.h", header_code}
    };
    LineDirectiveFactory factory(
        cap, "from_header",
        [](clang::ASTContext& ctx, LineDirectiveCapture& c) {
            if (!c.found_var) return;
            const clang::SourceManager& sm = ctx.getSourceManager();
            // Sanity: the captured location MUST lie outside the main
            // file or the test's construction is wrong.
            CHECK(!sm.isInMainFile(c.var_begin_loc));
            // The helper must reject this location with an empty string.
            std::string got = format_line_directive(sm, c.var_begin_loc);
            CHECK_EQ_STR(got, std::string{});
        });
    (void)clang::tooling::runToolOnCodeWithArgs(
        factory.create(), main_code, args, "demo.cpp",
        "sturm-transpile-test",
        std::make_shared<clang::PCHContainerOperations>(),
        mappings);
    CHECK(cap.found_var);
}

// Case 4 — user `#line` pragma honored via getPresumedLoc(). The physical
// location is on line 4 of "mine.cpp" but the pragma says "line 100 of
// virtual.cpp", so the helper must emit the pragma-adjusted values.
static void test_format_line_directive_honors_user_line_pragma() {
    // Buffer layout:
    //   1: // header
    //   2: #line 100 "virtual.cpp"
    //   3: void demo() {
    //   4:     int target = 42;   // physical line 4, presumed line 101
    //   5: }
    // The `#line 100 "virtual.cpp"` pragma renumbers the NEXT line as 100,
    // so line 3 presumes as 100 and line 4 presumes as 101.
    std::string code =
        "// header\n"
        "#line 100 \"virtual.cpp\"\n"
        "void demo() {\n"
        "    int target = 42;\n"
        "}\n";

    LineDirectiveCapture cap = run_line_directive_tool(
        code, "target", "mine.cpp",
        [](clang::ASTContext& ctx, LineDirectiveCapture& c) {
            if (!c.found_var) return;
            std::string got = format_line_directive(
                ctx.getSourceManager(), c.var_begin_loc);
            // Expected: the helper reports the PRESUMED file/line.
            std::string want = "#line 101 \"virtual.cpp\"\n";
            CHECK_EQ_STR(got, want);
        });

    CHECK(cap.found_var);
    CHECK_EQ_STR(cap.presumed_file, std::string("virtual.cpp"));
    CHECK(cap.presumed_line == 101);
}

// ── Entry point ──────────────────────────────────────────────────────────────

int run_test_transpile_emitter(int /*argc*/, char** /*argv*/) {
    test_golden_snapshot();
    test_idempotency_skip_detection();
    test_multiple_ops_lifo_in_output();
    test_pe2_replacement_plus_insertion();
    test_pe2_replacement_only();
    test_pe2_back_compat_overload();
    test_emit_to_string_equals_file_minus_header();
    test_emit_to_string_no_ops_returns_original();
    test_emit_to_file_matches_legacy_emit_bytes();
    test_format_line_directive_valid_main_file();
    test_format_line_directive_invalid_returns_empty();
    test_format_line_directive_non_main_file_returns_empty();
    test_format_line_directive_honors_user_line_pragma();

    std::printf("PASS: %d/%d\n", tests_pass, tests_run);
    return tests_pass == tests_run ? 0 : 1;
}
