// test_sturm_gen_clean.cpp -- sturm-7t85.4 (Beat G4) backend-script gate,
// extended in sturm-8a2q to also catch bare-spelling `qint` residue.
//
// Plan §19e, PRD §9.3.3 / G6 / A10. Operationalises wave-1 G3 ("full
// alias erasure") as a permanent regression gate: any file under
// `${CMAKE_BINARY_DIR}/sturm_gen/` produced by the transpile build step
// containing a forbidden pattern fails the build, with file:line for
// every offending site printed in one run.
//
// Hard-fail families (full implementation in
// `test_sturm_gen_clean_scan.hpp`):
//   * qualified: `sturm::frontend::qint`, `using qint = (::)?
//     sturm::frontend::qint`. Plain-substring scan over the raw file.
//   * bare: residue from a wave-2 matcher arm regression where
//     `qint a[4];` (carrier-imported via `using sturm::qint;`)
//     survives unrewritten. Comment-and-string-stripped scan with
//     allow-listing of the import line and `#include` directives.
//
// Local typedefs `using qint = sturm::qint_t<W>;` remain PERMITTED;
// the qualified scan keys on `frontend::qint`, and the bare scan
// keys on `\bqint\b` not followed by `_`.
//
// LoC budget: <= 200 (plan §19e). Scan logic factored to a sibling
// header so this driver stays small.
//
// Risk R7 (path drift across build/ build_mac/ build_linux/):
// `<sturm_gen_path.hpp>` is generated by `configure_file` and records
// the exact configured `sturm_gen/` directory. A stale path fails to
// compile here, not silently at run time.

#include <sturm_gen_path.hpp>

#include "test_sturm_gen_clean_scan.hpp"

#include <algorithm>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <system_error>
#include <vector>

namespace fs = std::filesystem;

namespace {

using sturm::transpile::testing::Offense;
using sturm::transpile::testing::scan_text;

// Slurp file into memory; on I/O error, return empty (caller observes
// the file as `clean` — the directory walk's per-file listing still
// makes the omission visible. We do not file-fail on I/O.).
std::string slurp(const fs::path& p) {
    std::ifstream in(p, std::ios::binary);
    if (!in) return {};
    std::ostringstream oss;
    oss << in.rdbuf();
    return oss.str();
}

// Walk the sturm_gen tree once, collecting `*.cpp` and `*.hpp` paths.
// Returns sorted (deterministic CI output) list of files visited.
std::vector<fs::path> collect_targets(const fs::path& root) {
    std::vector<fs::path> targets;
    if (!fs::exists(root)) return targets;
    std::error_code ec;
    for (auto it = fs::recursive_directory_iterator(
             root, fs::directory_options::skip_permission_denied, ec);
         !ec && it != fs::recursive_directory_iterator{};
         it.increment(ec)) {
        if (!it->is_regular_file(ec)) continue;
        const auto& path = it->path();
        const auto ext   = path.extension().string();
        if (ext == ".cpp" || ext == ".hpp") {
            targets.push_back(path);
        }
    }
    std::sort(targets.begin(), targets.end());
    return targets;
}

}  // namespace

int main() {
    const fs::path root(sturm::transpile::testing::kSturmGenDir);

    std::fprintf(stderr,
                 "test_sturm_gen_clean: scanning %s\n", root.string().c_str());

    if (!fs::exists(root)) {
        // The transpile build step has not produced any output yet.
        // Configure-time `add_dependencies` should have made this
        // impossible at ctest invocation time; treat the missing
        // directory as a hard error so the gate cannot silently pass.
        std::fprintf(stderr,
                     "FAIL: sturm_gen directory does not exist at %s\n"
                     "      (CMake `add_dependencies(test_sturm_gen_clean ...)`"
                     " is wired wrong, or no `add_quantum_executable()`"
                     " target ran.)\n",
                     root.string().c_str());
        return 1;
    }

    const auto targets = collect_targets(root);
    std::fprintf(stderr,
                 "test_sturm_gen_clean: %zu file(s) to scan\n",
                 targets.size());

    std::vector<Offense> offenses;
    for (const auto& path : targets) {
        const std::string content = slurp(path);
        if (content.empty()) continue;
        scan_text(path, content, offenses);
    }

    if (offenses.empty()) {
        std::fprintf(stderr,
                     "PASS: %zu file(s) clean (no qualified or bare-spelling"
                     " `qint` residue).\n", targets.size());
        return 0;
    }

    // Print ALL offenses in one pass so a single CI run yields the
    // complete inventory; debugging cycles benefit from not having to
    // rebuild between fixes.
    std::fprintf(stderr,
                 "FAIL: %zu offending site(s) under %s:\n",
                 offenses.size(), root.string().c_str());
    for (const auto& o : offenses) {
        // Format: <file>:<line>: matched `<pattern>`
        //     <line text>
        std::fprintf(stderr,
                     "  %s:%zu: matched `%.*s`\n      %s\n",
                     o.file.string().c_str(), o.line,
                     static_cast<int>(o.pat.size()), o.pat.data(),
                     o.text.c_str());
    }
    std::fprintf(stderr,
                 "test_sturm_gen_clean: failing on %zu offense(s).\n",
                 offenses.size());
    return 1;
}
