// test_skip.cpp — unit + integration tests for the M5 skip / idempotency
// helpers.
//
// Scope
// -----
// 1. Unit tests for `should_skip()` and `idempotency_header()`. Pure
//    string-level checks — no LibTooling, no subprocess, no filesystem
//    (other than the harness boilerplate).
//
// 2. Integration test: drive the compiled sturm-transpile binary against
//    two locked fixtures under `transpiler/tests/fixtures/`:
//      - skip_marker.cpp        — first non-blank line is the magic
//                                 comment `// sturm-transpile: skip`.
//      - already_generated.cpp  — first non-blank line is the
//                                 AUTO-GENERATED sentinel.
//    For each fixture we invoke the driver with `--output-dir <tmp>` and
//    assert byte-identical equality against the paired `.expected.cpp`.
//    This is the direct check of PRD AC #5 (idempotency) and AC #6 (skip
//    marker) at the driver level.
//
// The fixtures directory is located relative to CMake's
// `CMAKE_CURRENT_SOURCE_DIR` at configure time and threaded in as the
// compile-definition STURM_TRANSPILE_FIXTURES_DIR so the test does not
// have to guess where the source tree lives.

#include "sturm/transpile/skip.hpp"

#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <string_view>
#include <utility>

namespace fs = std::filesystem;
using namespace sturm::transpile;

#ifndef STURM_TRANSPILE_BIN
#  error "STURM_TRANSPILE_BIN must be defined by the CMake build (path to the sturm-transpile binary)."
#endif
#ifndef STURM_TRANSPILE_FIXTURES_DIR
#  error "STURM_TRANSPILE_FIXTURES_DIR must be defined by the CMake build (path to the tests/fixtures directory)."
#endif

// ── Test harness ──────────────────────────────────────────────────────────────
static int tests_run  = 0;
static int tests_pass = 0;

#define CHECK(cond) do {                                              \
    ++tests_run;                                                      \
    if (cond) { ++tests_pass; }                                       \
    else {                                                            \
        std::fprintf(stderr, "FAIL  %s:%d  %s\n",                     \
                     __FILE__, __LINE__, #cond);                      \
    }                                                                 \
} while (0)

#define CHECK_EQ_STR(got, want) do {                                  \
    ++tests_run;                                                      \
    const std::string _g = (got);                                     \
    const std::string _w = (want);                                    \
    if (_g == _w) { ++tests_pass; }                                   \
    else {                                                            \
        std::fprintf(stderr, "FAIL  %s:%d  strings differ\n"          \
                             "  got:  <<<%s>>>\n"                     \
                             "  want: <<<%s>>>\n",                    \
                     __FILE__, __LINE__, _g.c_str(), _w.c_str());     \
    }                                                                 \
} while (0)

// ── Unit: idempotency_header ─────────────────────────────────────────────────

static void test_header_format() {
    // Locked canonical format. Two lines, both start with `// `, terminated
    // by `\n`. The second line carries the source path verbatim.
    std::string got = idempotency_header("src/demo.cpp");
    CHECK_EQ_STR(got,
                 std::string("// AUTO-GENERATED by sturm-transpile"
                             " -- do not edit\n"
                             "// Source: src/demo.cpp\n"));
}

static void test_header_path_passthrough() {
    // Absolute paths embed verbatim — no basename extraction, no rewriting.
    std::string got = idempotency_header("/tmp/full/path/user.cpp");
    CHECK(got.find("// Source: /tmp/full/path/user.cpp\n")
          != std::string::npos);
}

// ── Unit: should_skip ────────────────────────────────────────────────────────

static void test_should_skip_auto_generated() {
    // The file we just emitted must be recognized as pass-through on a
    // second pipeline pass. This is the idempotency contract.
    std::string head = idempotency_header("src/demo.cpp");
    head += "void demo(qbool a, qbool b) { qbool tmp = a | b; }\n";
    CHECK(should_skip(head));
}

static void test_should_skip_explicit_marker() {
    CHECK(should_skip("// sturm-transpile: skip\n"
                      "void anything(qbool a, qbool b) {"
                      " qbool tmp = a | b; }\n"));
}

static void test_should_skip_leading_blank_lines() {
    // Blank / whitespace-only lines ahead of the marker are tolerated.
    CHECK(should_skip("\n"
                      "   \n"
                      "\n"
                      "// sturm-transpile: skip\n"
                      "// anything else\n"));
}

static void test_should_skip_leading_blank_before_auto_gen() {
    // Symmetry: leading blanks are also tolerated before the
    // AUTO-GENERATED sentinel, not just the skip marker.
    CHECK(should_skip("\n\n"
                      "// AUTO-GENERATED by sturm-transpile -- do not edit\n"
                      "// Source: anywhere.cpp\n"));
}

static void test_should_not_skip_plain_source() {
    CHECK(!should_skip("#include <sturm/sturm.hpp>\n"
                       "void demo(qbool a, qbool b) { qbool tmp = a | b; }\n"));
}

static void test_should_not_skip_regular_comment() {
    // A normal `// comment` line does NOT trigger skip, only the two exact
    // sentinels do. Prevents accidental pass-through of user files that
    // happen to start with a file-header comment.
    CHECK(!should_skip("// My nice hand-written header\n"
                       "#include <sturm/sturm.hpp>\n"));
}

static void test_should_not_skip_empty_head() {
    // An empty head (all-blank or truly empty) must not trigger skip;
    // should_skip only returns true when it has actually seen a sentinel.
    CHECK(!should_skip(""));
    CHECK(!should_skip("\n\n   \n\t\n"));
}

static void test_should_not_skip_near_miss_marker() {
    // A near-miss on the skip marker (wrong capitalization) is NOT a
    // sentinel. Exact line-prefix match is required.
    CHECK(!should_skip("// Sturm-Transpile: skip\n"
                       "int main() { return 0; }\n"));
}

// ── Integration: drive sturm-transpile on fixtures ───────────────────────────

// Run a shell command, returning (exit_code, stdout+stderr).
static std::pair<int, std::string> run_cmd(const std::string& cmd) {
    std::string full = cmd + " 2>&1";
    FILE* pipe = ::popen(full.c_str(), "r");
    if (!pipe) return {-1, ""};
    std::string out;
    char buf[512];
    while (std::fgets(buf, sizeof(buf), pipe)) out += buf;
    int rc = ::pclose(pipe);
    if (WIFEXITED(rc)) return {WEXITSTATUS(rc), out};
    return {rc, out};
}

static std::string read_file_contents(const fs::path& p) {
    std::ifstream in(p, std::ios::binary);
    std::ostringstream oss;
    oss << in.rdbuf();
    return oss.str();
}

static fs::path make_scratch_dir(const char* tag) {
    fs::path base = fs::temp_directory_path() / "sturm-m5-skip-tests";
    fs::create_directories(base);
    fs::path dir = base / tag;
    fs::remove_all(dir);
    fs::create_directories(dir);
    return dir;
}

static fs::path quote(const fs::path& p) {
    return fs::path("'" + p.string() + "'");
}

// Drive the sturm-transpile binary on `fixture_basename` under the
// fixtures dir, asserting that the output file is byte-identical to
// `<basename>.expected.cpp` and that the binary exits 0.
static void run_fixture_roundtrip(const char* fixture_basename,
                                  const char* scratch_tag) {
    fs::path fixtures = fs::path(STURM_TRANSPILE_FIXTURES_DIR);
    fs::path input    = fixtures / fixture_basename;
    std::string expected_name = std::string(fixture_basename);
    // Replace trailing ".cpp" with ".expected.cpp".
    auto dot = expected_name.rfind(".cpp");
    if (dot != std::string::npos) {
        expected_name.replace(dot, 4, ".expected.cpp");
    }
    fs::path expected = fixtures / expected_name;

    CHECK(fs::exists(input));
    CHECK(fs::exists(expected));

    fs::path dir    = make_scratch_dir(scratch_tag);
    fs::path outdir = dir / "gen";
    fs::create_directories(outdir);

    // The driver copies the input to <outdir>/<basename of input> when
    // given an absolute path (resolve_output_path behavior).
    std::string cmd = std::string(STURM_TRANSPILE_BIN) +
        " " + quote(input).string() +
        " --output-dir " + quote(outdir).string();
    auto [rc, out] = run_cmd(cmd);
    if (rc != 0) std::fprintf(stderr, "driver stderr:\n%s\n", out.c_str());
    CHECK(rc == 0);

    fs::path landed = outdir / fs::path(fixture_basename);
    CHECK(fs::exists(landed));
    CHECK_EQ_STR(read_file_contents(landed),
                 read_file_contents(expected));
}

static void test_driver_skip_marker_fixture() {
    // PRD AC #6: magic comment suppresses the pipeline, preserving the
    // file byte-for-byte.
    run_fixture_roundtrip("skip_marker.cpp", "fixture_skip_marker");
}

static void test_driver_already_generated_fixture() {
    // PRD AC #5: running on an AUTO-GENERATED file yields a byte-identical
    // copy; the pipeline must not re-prepend a second header or otherwise
    // mutate the body.
    run_fixture_roundtrip("already_generated.cpp",
                          "fixture_already_generated");
}

// ── Entry point ──────────────────────────────────────────────────────────────

int main() {
    test_header_format();
    test_header_path_passthrough();

    test_should_skip_auto_generated();
    test_should_skip_explicit_marker();
    test_should_skip_leading_blank_lines();
    test_should_skip_leading_blank_before_auto_gen();
    test_should_not_skip_plain_source();
    test_should_not_skip_regular_comment();
    test_should_not_skip_empty_head();
    test_should_not_skip_near_miss_marker();

    test_driver_skip_marker_fixture();
    test_driver_already_generated_fixture();

    std::printf("PASS: %d/%d\n", tests_pass, tests_run);
    return tests_pass == tests_run ? 0 : 1;
}
