// test_sturm_gen_clean.cpp -- sturm-7t85.4 (Beat G4) backend-script gate.
//
// Plan §19e, PRD §9.3.3 / G6 / A10. Operationalises wave-1 G3 ("full
// alias erasure") as a permanent regression gate: any file under
// `${CMAKE_BINARY_DIR}/sturm_gen/` produced by the transpile build step
// containing a `sturm::frontend::qint` mention (in any spelling) fails
// the build, with file:line for every offending site printed in one run.
//
// Hard-fail patterns (any-spelling substring scan, NOT regex):
//   1. `sturm::frontend::qint`   (covers `::sturm::frontend::qint` too)
//   2. `using qint = ::sturm::frontend::qint`
//   3. `using qint = sturm::frontend::qint`
//
// Local typedefs `using qint = sturm::qint_t<W>;` are PERMITTED — the
// scan deliberately keys on `frontend::qint`, not bare `qint`.
//
// LoC budget: <= 200 (plan §19e).
//
// Risk R7 (path drift across build/ build_mac/ build_linux/):
// `<sturm_gen_path.hpp>` is generated by `configure_file` and records
// the exact configured `sturm_gen/` directory. A stale path fails to
// compile here, not silently at run time.

#include <sturm_gen_path.hpp>

#include <algorithm>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <string_view>
#include <system_error>
#include <vector>

namespace fs = std::filesystem;

namespace {

// ── Patterns ────────────────────────────────────────────────────────────────
// Each pattern is matched as a plain substring so the gate is robust
// against whitespace and qualifier variation (e.g. `::sturm::frontend
// ::qint` would still match pattern 1 because the substring
// `sturm::frontend::qint` appears verbatim — every spelling we want to
// catch contains the namespace-qualified `sturm::frontend::qint` token).
constexpr std::string_view kPatterns[] = {
    "sturm::frontend::qint",
    "using qint = ::sturm::frontend::qint",
    "using qint = sturm::frontend::qint",
};

struct Offense {
    fs::path file;
    std::size_t line;
    std::string text;       // The offending line, trimmed of trailing \r/\n.
    std::string_view pat;   // Which pattern matched.
};

// Slurp file into memory; on I/O error, return empty (caller observes
// the file as `clean` — but the directory walk also reports the file
// listing above, so this is harmless. We do not file-fail on I/O.).
std::string slurp(const fs::path& p) {
    std::ifstream in(p, std::ios::binary);
    if (!in) return {};
    std::ostringstream oss;
    oss << in.rdbuf();
    return oss.str();
}

// Trim a trailing CR/LF pair so the diagnostic line prints cleanly on
// Windows-line-ending sources.
std::string rstrip_eol(std::string_view s) {
    while (!s.empty() && (s.back() == '\n' || s.back() == '\r')) {
        s.remove_suffix(1);
    }
    return std::string(s);
}

// Scan one file for every pattern hit. Pushes one Offense per (line,
// pattern) pair. We do NOT bail on first hit — debugging cycles benefit
// from seeing the complete inventory of offending sites in a single run.
void scan_file(const fs::path& path, std::vector<Offense>& out) {
    const std::string content = slurp(path);
    if (content.empty()) return;
    std::size_t line_no = 1;
    std::size_t cursor  = 0;
    while (cursor <= content.size()) {
        const std::size_t eol = content.find('\n', cursor);
        const std::size_t end = (eol == std::string::npos)
                                    ? content.size()
                                    : eol;
        const std::string_view line(content.data() + cursor, end - cursor);
        for (std::string_view pat : kPatterns) {
            if (line.find(pat) != std::string_view::npos) {
                out.push_back(Offense{path, line_no, rstrip_eol(line), pat});
            }
        }
        if (eol == std::string::npos) break;
        cursor = eol + 1;
        ++line_no;
    }
}

// Walk the sturm_gen tree once, collecting `*.cpp` and `*.hpp` paths.
// Returns sorted (deterministic CI output) list of files visited.
std::vector<fs::path> collect_targets(const fs::path& root) {
    std::vector<fs::path> targets;
    if (!fs::exists(root)) return targets;
    std::error_code ec;
    for (auto it = fs::recursive_directory_iterator(
             root, fs::directory_options::skip_permission_denied, ec);
         !ec && it != fs::recursive_directory_iterator{};
         it.increment(ec)) {
        if (!it->is_regular_file(ec)) continue;
        const auto& path = it->path();
        const auto ext   = path.extension().string();
        if (ext == ".cpp" || ext == ".hpp") {
            targets.push_back(path);
        }
    }
    std::sort(targets.begin(), targets.end());
    return targets;
}

}  // namespace

int main() {
    const fs::path root(sturm::transpile::testing::kSturmGenDir);

    std::fprintf(stderr,
                 "test_sturm_gen_clean: scanning %s\n", root.string().c_str());

    if (!fs::exists(root)) {
        // The transpile build step has not produced any output yet.
        // Configure-time `add_dependencies` should have made this
        // impossible at ctest invocation time; treat the missing
        // directory as a hard error so the gate cannot silently pass.
        std::fprintf(stderr,
                     "FAIL: sturm_gen directory does not exist at %s\n"
                     "      (CMake `add_dependencies(test_sturm_gen_clean ...)`"
                     " is wired wrong, or no `add_quantum_executable()`"
                     " target ran.)\n",
                     root.string().c_str());
        return 1;
    }

    const auto targets = collect_targets(root);
    std::fprintf(stderr,
                 "test_sturm_gen_clean: %zu file(s) to scan\n",
                 targets.size());

    std::vector<Offense> offenses;
    for (const auto& path : targets) {
        scan_file(path, offenses);
    }

    if (offenses.empty()) {
        std::fprintf(stderr,
                     "PASS: %zu file(s) clean (no `sturm::frontend::qint`"
                     " mentions).\n", targets.size());
        return 0;
    }

    // Print ALL offenses in one pass so a single CI run yields the
    // complete inventory; debugging cycles benefit from not having to
    // rebuild between fixes.
    std::fprintf(stderr,
                 "FAIL: %zu offending site(s) under %s:\n",
                 offenses.size(), root.string().c_str());
    for (const auto& o : offenses) {
        // Format: <file>:<line>: matched `<pattern>`
        //     <line text>
        std::fprintf(stderr,
                     "  %s:%zu: matched `%.*s`\n      %s\n",
                     o.file.string().c_str(), o.line,
                     static_cast<int>(o.pat.size()), o.pat.data(),
                     o.text.c_str());
    }
    std::fprintf(stderr,
                 "test_sturm_gen_clean: failing on %zu offense(s).\n",
                 offenses.size());
    return 1;
}
