// test_emitter.cpp — unit tests for the M9 C++ emitter.
//
// The emitter is the last module in the transpiler pipeline:
//
//   M7 matcher  →  M8 synthesize  →  M9 emit  →  file on disk
//
// These tests exercise three layers:
//
//   1. Pure helpers — idempotency_header() and should_skip() are string-only
//      functions with no LibTooling dependency. They are checked directly
//      to lock in the canonical header format and the skip-detection rules.
//
//   2. Golden snapshot — drive the full emit() call on the PRD's MVP input
//      using a real Clang SourceManager + Rewriter produced via LibTooling.
//      Compare the generated bytes against the locked canonical form so any
//      regression in the emitter's whitespace or header pops up immediately.
//
//   3. Idempotency — take the emitter's output, feed it back through the
//      pipeline's skip-detection layer, and confirm the file is treated as
//      pass-through. This is PRD AC #5 checked at the unit level.
//
// The tests assemble a tiny qbool stub inline so no external STURM include
// path is required. All SourceManager traffic happens inside
// `runToolOnCodeWithArgs`, matching the test_matcher.cpp pattern.

#include "sturm/transpile/emitter.hpp"
#include "sturm/transpile/io.hpp"
#include "sturm/transpile/matcher.hpp"
#include "sturm/transpile/qir.hpp"
#include "sturm/transpile/uncompute_pass.hpp"

#include "clang/AST/ASTConsumer.h"
#include "clang/AST/ASTContext.h"
#include "clang/ASTMatchers/ASTMatchFinder.h"
#include "clang/Basic/SourceLocation.h"
#include "clang/Basic/SourceManager.h"
#include "clang/Frontend/CompilerInstance.h"
#include "clang/Frontend/FrontendActions.h"
#include "clang/Rewrite/Core/Rewriter.h"
#include "clang/Tooling/Tooling.h"

#include <cassert>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <memory>
#include <sstream>
#include <string>
#include <string_view>
#include <vector>

namespace fs = std::filesystem;
using namespace sturm::transpile;

// ── Test harness ──────────────────────────────────────────────────────────────
static int tests_run  = 0;
static int tests_pass = 0;

#define CHECK(cond) do {                                              \
    ++tests_run;                                                      \
    if (cond) { ++tests_pass; }                                       \
    else {                                                            \
        std::fprintf(stderr, "FAIL  %s:%d  %s\n",                     \
                     __FILE__, __LINE__, #cond);                      \
    }                                                                 \
} while (0)

#define CHECK_EQ_STR(got, want) do {                                  \
    ++tests_run;                                                      \
    const std::string _g = (got);                                     \
    const std::string _w = (want);                                    \
    if (_g == _w) { ++tests_pass; }                                   \
    else {                                                            \
        std::fprintf(stderr, "FAIL  %s:%d  strings differ\n"          \
                             "  got:  <<<%s>>>\n"                     \
                             "  want: <<<%s>>>\n",                    \
                     __FILE__, __LINE__, _g.c_str(), _w.c_str());     \
    }                                                                 \
} while (0)

// ── Unit: idempotency_header ─────────────────────────────────────────────────

static void test_header_format() {
    // Locked canonical format. Two lines, both start with `// `, terminated
    // by `\n`. The second line carries the source path verbatim.
    std::string got = idempotency_header("src/demo.cpp");
    CHECK_EQ_STR(got,
                 std::string("// AUTO-GENERATED by sturm-transpile"
                             " -- do not edit\n"
                             "// Source: src/demo.cpp\n"));
}

static void test_header_path_passthrough() {
    // Absolute paths embed verbatim — no basename extraction, no rewriting.
    std::string got = idempotency_header("/tmp/full/path/user.cpp");
    CHECK(got.find("// Source: /tmp/full/path/user.cpp\n") != std::string::npos);
}

// ── Unit: should_skip ────────────────────────────────────────────────────────

static void test_should_skip_auto_generated() {
    // The file we just emitted must be recognized as pass-through on a
    // second pipeline pass. This is the idempotency contract.
    std::string head = idempotency_header("src/demo.cpp");
    head += "void demo(qbool a, qbool b) { qbool tmp = a | b; }\n";
    CHECK(should_skip(head));
}

static void test_should_skip_explicit_marker() {
    CHECK(should_skip("// sturm-transpile: skip\n"
                      "void anything(qbool a, qbool b) {"
                      " qbool tmp = a | b; }\n"));
}

static void test_should_skip_leading_blank_lines() {
    // Blank / whitespace-only lines ahead of the marker are tolerated.
    CHECK(should_skip("\n"
                      "   \n"
                      "\n"
                      "// sturm-transpile: skip\n"
                      "// anything else\n"));
}

static void test_should_not_skip_plain_source() {
    CHECK(!should_skip("#include <sturm/sturm.hpp>\n"
                       "void demo(qbool a, qbool b) { qbool tmp = a | b; }\n"));
}

static void test_should_not_skip_regular_comment() {
    // A normal `// comment` line does NOT trigger skip, only the two exact
    // sentinels do. Prevents accidental pass-through of user files that
    // happen to start with a file-header comment.
    CHECK(!should_skip("// My nice hand-written header\n"
                       "#include <sturm/sturm.hpp>\n"));
}

// ── Integration: drive emit() via real Clang parsing ─────────────────────────

// Shared state the RunAction populates on match + emit. After the tool runs,
// these hold everything the test needs to diff against the golden.
struct EmitFixture {
    QUnit unit;
    std::vector<UncomputeInsertion> insertions;
    std::string bytes_on_disk;
    bool ok = false;
    fs::path out_path;
};

namespace {

// ASTConsumer that runs the M7 matcher, then M8 synthesize, then M9 emit,
// all within a single tool invocation so they share one SourceManager.
class EmitConsumer : public clang::ASTConsumer {
public:
    EmitConsumer(EmitFixture& out,
                 const std::string& source_path,
                 const std::string& output_dir)
        : fx_(out), source_path_(source_path), output_dir_(output_dir) {
        register_or_matcher(finder_, fx_.unit);
    }

    void HandleTranslationUnit(clang::ASTContext& ctx) override {
        finder_.matchAST(ctx);
        fx_.insertions = synthesize(fx_.unit);
        clang::Rewriter rw(ctx.getSourceManager(), ctx.getLangOpts());
        fx_.ok = emit(ctx.getSourceManager(), rw, fx_.insertions,
                      source_path_, output_dir_);
        if (fx_.ok) {
            fx_.out_path = sturm::transpile::resolve_output_path(
                fs::path(source_path_), fs::path(output_dir_));
            (void)sturm::transpile::read_file(fx_.out_path, fx_.bytes_on_disk);
        }
    }

private:
    clang::ast_matchers::MatchFinder finder_;
    EmitFixture& fx_;
    std::string source_path_;
    std::string output_dir_;
};

class EmitAction : public clang::ASTFrontendAction {
public:
    EmitAction(EmitFixture& fx, std::string source_path, std::string output_dir)
        : fx_(fx), source_path_(std::move(source_path)),
          output_dir_(std::move(output_dir)) {}
    std::unique_ptr<clang::ASTConsumer> CreateASTConsumer(
        clang::CompilerInstance&, llvm::StringRef) override {
        return std::make_unique<EmitConsumer>(fx_, source_path_, output_dir_);
    }
private:
    EmitFixture& fx_;
    std::string source_path_;
    std::string output_dir_;
};

class EmitFactory : public clang::tooling::FrontendActionFactory {
public:
    EmitFactory(EmitFixture& fx, std::string src_path, std::string out_dir)
        : fx_(fx), src_path_(std::move(src_path)),
          out_dir_(std::move(out_dir)) {}
    std::unique_ptr<clang::FrontendAction> create() override {
        return std::make_unique<EmitAction>(fx_, src_path_, out_dir_);
    }
private:
    EmitFixture& fx_;
    std::string src_path_;
    std::string out_dir_;
};

} // namespace

// Inline qbool stub so the tool can parse the input without STURM headers.
// Matches the stub used in test_matcher.cpp.
static constexpr std::string_view kQBoolStub = R"CPP(
namespace sturm {
class qbool {
public:
    qbool() {}
    qbool(const qbool&) {}
};
inline qbool operator|(const qbool&, const qbool&) { return qbool{}; }
} // namespace sturm
using sturm::qbool;
)CPP";

// Create a fresh temp directory, unique per test, to hold the emitter
// output. The tests clear and recreate it on each call.
static fs::path scratch_dir(const char* tag) {
    fs::path base = fs::temp_directory_path() / "sturm-m9-emitter-tests";
    fs::create_directories(base);
    fs::path d = base / tag;
    fs::remove_all(d);
    fs::create_directories(d);
    return d;
}

// Run the tool on `body` + the qbool stub, invoking the emitter against a
// unique scratch output directory. Returns the populated fixture.
static EmitFixture run_emit(std::string_view body,
                            const char* tag,
                            const std::string& source_name = "demo.cpp") {
    std::string code;
    code.reserve(kQBoolStub.size() + body.size());
    code.append(kQBoolStub);
    code.append(body);

    fs::path dir = scratch_dir(tag);

    EmitFixture fx;
    std::vector<std::string> args{"-std=c++20", "-fsyntax-only"};
    EmitFactory factory(fx, source_name, dir.string());
    (void)clang::tooling::runToolOnCodeWithArgs(
        factory.create(), code, args, source_name);
    return fx;
}

// ── Golden snapshot test ─────────────────────────────────────────────────────

// Canonical expected output for the PRD's MVP input. The rewriter inserts
// the uncompute call text immediately before the closing `}`, so the
// result is a one-liner function body followed by the injected call and
// the close brace on its own line — the exact byte layout below.
//
// This string is the acceptance criterion of M9: any change that is not
// also reflected here breaks the golden, and vice versa.
static std::string expected_golden() {
    std::string out;
    out += "// AUTO-GENERATED by sturm-transpile -- do not edit\n";
    out += "// Source: demo.cpp\n";
    // The stub the test prepends to the input ends with
    // `using sturm::qbool;\n`. That block is PART of what gets parsed and
    // therefore part of what Rewriter considers the "original" source,
    // so it must appear verbatim in the output.
    out += std::string(kQBoolStub);
    // Note the 5 spaces between `;` and `uncompute_or(`: one is the
    // single space the original source has between `;` and `}`, and
    // four are the indent on the injected `uncompute_or` line. Rewriter
    // preserves the original character stream verbatim except where it
    // inserts new text, so this whitespace pattern is deterministic.
    out += "void demo(qbool a, qbool b) { qbool tmp = a | b;"
           "     uncompute_or(tmp, a, b);\n}\n";
    return out;
}

static void test_golden_snapshot() {
    EmitFixture fx = run_emit(
        "void demo(qbool a, qbool b) { qbool tmp = a | b; }\n",
        "golden");

    CHECK(fx.ok);
    CHECK(fx.unit.scopes.size() == 1);
    CHECK(fx.insertions.size() == 1);
    CHECK(fs::exists(fx.out_path));

    CHECK_EQ_STR(fx.bytes_on_disk, expected_golden());
}

// ── Idempotency: emitted file short-circuits on re-run ──────────────────────

static void test_idempotency_skip_detection() {
    // The emitter's first-pass output starts with the AUTO-GENERATED
    // sentinel. should_skip() must recognize it so the pipeline copies it
    // through on the second run.
    EmitFixture fx = run_emit(
        "void demo(qbool a, qbool b) { qbool tmp = a | b; }\n",
        "idempotent");

    CHECK(fx.ok);
    CHECK(should_skip(fx.bytes_on_disk));
}

// ── Emitter preserves insertion order for multiple ops ───────────────────────

static void test_multiple_ops_lifo_in_output() {
    // Two forward ops in the same scope produce two insertions in LIFO
    // order (M8 contract). The emitter must preserve that order when
    // calling InsertTextBefore so the most recent intermediate's uncompute
    // call lands first in source text, closest to the close-brace.
    EmitFixture fx = run_emit(
        "void demo(qbool a, qbool b, qbool c, qbool d) {"
        " qbool t0 = a | b; qbool t1 = c | d; }\n",
        "multi");

    CHECK(fx.ok);
    CHECK(fx.insertions.size() == 2);
    if (fx.insertions.size() != 2) return;

    // Order in M8 list: t1 uncompute first, t0 second (LIFO).
    CHECK_EQ_STR(fx.insertions[0].code,
                 std::string("    uncompute_or(t1, c, d);\n"));
    CHECK_EQ_STR(fx.insertions[1].code,
                 std::string("    uncompute_or(t0, a, b);\n"));

    // Both substrings must appear in the emitted file, with t1's line
    // closer to the close brace than t0's. Rewriter at the same anchor
    // appends successive insertions right-to-left of earlier ones: the
    // LAST InsertTextBefore call lands closest to the anchor. So the
    // order in source text is:  t1 uncompute  →  t0 uncompute  →  `}`.
    // Wait — this is the reverse of what LIFO wants. M8 guarantees t1
    // comes FIRST in its list. We therefore feed t1 first and t0 second,
    // meaning t0 ends up closest to the brace. That puts uncompute calls
    // in reverse-of-forward order in the emitted text, which is exactly
    // LIFO applied to the final source.
    auto t0_pos = fx.bytes_on_disk.find("uncompute_or(t0");
    auto t1_pos = fx.bytes_on_disk.find("uncompute_or(t1");
    CHECK(t0_pos != std::string::npos);
    CHECK(t1_pos != std::string::npos);
    // t1 appears BEFORE t0 in the final text (LIFO: last-in first-out —
    // t1 was the last forward op, so its uncompute comes first).
    CHECK(t1_pos < t0_pos);
}

// ── Entry point ──────────────────────────────────────────────────────────────

int main() {
    test_header_format();
    test_header_path_passthrough();
    test_should_skip_auto_generated();
    test_should_skip_explicit_marker();
    test_should_skip_leading_blank_lines();
    test_should_not_skip_plain_source();
    test_should_not_skip_regular_comment();

    test_golden_snapshot();
    test_idempotency_skip_detection();
    test_multiple_ops_lifo_in_output();

    std::printf("PASS: %d/%d\n", tests_pass, tests_run);
    return tests_pass == tests_run ? 0 : 1;
}
