// test_baseline_gate_counts.cpp -- sturm-a3t4.1 P0
//
// Captures a gate-count baseline for `lib_add_mod_dsl`,
// `lib_mul_mod_dsl`, and `lib_pow_mod_dsl` at register widths n=8 and
// n=16, both bare (no enclosing WHEN) and inside a single `WHEN(c)`
// scope where `c` is a one-qubit superposed control.  The numbers
// captured here are the pre-refactor reference point for the
// sturm-a3t4 epic ("depth-1 control stack invariant"); after the
// refactor lands, this file is re-run and the deltas relative to the
// committed baseline at `tests/control/baseline_gate_counts.txt` show
// whether the depth-1 lift pattern actually reduced the gate cost.
//
// Method (issue body):
//   - Run each primitive in `STURM_MODE_COUNT_ONLY` mode with the
//     minimal harness needed (allocate the input/output registers from
//     `QubitPool`, mark every owner as superposed so classicality
//     specialisation doesn't short-circuit the dispatch, install a
//     fresh `BackendContext`, and bracket the call with
//     `sturm_gate_count` reads).
//   - For the WHEN(c) variant, wrap the call in a `WHEN(c)` whose
//     control qbool is a freshly-allocated superposed flag (the same
//     pattern used by `tests/transpiler/test_gate_equivalence.cpp` for
//     control-stack tests).
//
// Coverage caveats:
//   - `lib_mul_mod_dsl` and `lib_pow_mod_dsl` cap their internal arrays
//     at `kMaxN = 8` (see the assert at the head of each header), so
//     the n=16 row of the baseline only applies to `lib_add_mod_dsl`
//     (whose `kMaxN = 32`).  The mul_mod / pow_mod n=16 cells of the
//     baseline file are written as `N/A (kMaxN=8)` so the artifact
//     still has a complete row layout.
//   - At n=8 `lib_pow_mod_dsl` peaks at 4·W² + 2W + 8 = 280 transient
//     ancillas above the 4·W=32 input qubits — beyond the default
//     STURM_ANCILLA_CAPACITY=256.  The test target compiles with
//     STURM_ANCILLA_CAPACITY=512 so the pow_mod n=8 cell can be
//     captured.
//
// Out of scope (per issue body): optimisation, golden-file updates.
// The committed baseline is regenerated by re-running this test and
// piping `BUILD/tests/control/baseline_gate_counts.txt` over
// `tests/control/baseline_gate_counts.txt` once the refactor lands.

#define STURM_BACKEND_ENABLED 1
#include "sturm/detail/lib/add_mod_dsl.hpp"
#include "sturm/detail/lib/mul_mod_dsl.hpp"
#include "sturm/detail/lib/pow_mod_dsl.hpp"
#include "sturm/detail/qtypes/bit_proxy.hpp"
#include "sturm/qtypes/qbool.hpp"
#include "sturm/control/when.hpp"
#include "sturm/core/context.hpp"
#include "sturm/core/core.h"
#include "sturm/core/qubit_pool.hpp"
#include "sturm/backend/orkan_bridge.hpp"

#include <cassert>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

// ── BackendContext harness (COUNT_ONLY mode, no simulator state) ────────────
// COUNT_ONLY only increments ctx.gate_count on each execute_gate; no Orkan
// state is required.  We still set max_qubits high enough to clear the cap
// check inside the lib primitives.
struct CountCtx {
    sturm_backend_context_t* ctx;
    sturm_backend_context_t* prev;
    explicit CountCtx(uint32_t max_q = 1024u) {
        ctx = sturm_backend_create(STURM_MODE_COUNT_ONLY, max_q);
        assert(ctx);
        prev = sturm_get_thread_context();
        sturm_set_thread_context(ctx);
    }
    ~CountCtx() {
        sturm_set_thread_context(prev);
        sturm_backend_destroy(ctx);
    }
};

// ── Register builder ────────────────────────────────────────────────────────
// Allocates `n` qubits from the pool, builds n owning qbool views with
// super_mask = 1 (so classicality specialisation does NOT skip dispatch),
// and projects them through BitProxy so the lib_*_mod_dsl templates accept
// them.  Owners and indices live in the caller's vectors so they outlive
// the BitProxy array.
struct Reg {
    std::vector<int>              qi;
    std::vector<sturm::qbool>     owners;   // non-owning, mask=1
    std::vector<sturm::BitProxy>  bits;
};

static Reg make_reg(std::size_t n) {
    Reg r;
    r.qi.resize(n);
    r.owners.resize(n);
    r.bits.resize(n);
    for (std::size_t i = 0; i < n; ++i) {
        r.qi[i]    = sturm::QubitPool::instance().allocate();
        r.owners[i] = sturm::qbool::make_non_owning(
            r.qi[i], /*val=*/0, /*mask=*/1ULL);
        r.bits[i]  = sturm::BitProxy(r.owners[i]);
    }
    return r;
}

static void release_reg(Reg& r) {
    // LIFO release.
    for (std::size_t i = r.qi.size(); i-- > 0;) {
        sturm::QubitPool::instance().release(r.qi[i]);
    }
    r.qi.clear();
    r.owners.clear();
    r.bits.clear();
}

// ── Per-primitive measurement entry points ─────────────────────────────────

// Returns the number of execute_gate calls emitted by lib_add_mod_dsl at
// width n.  When `wrap_in_when` is true the entire call site sits inside
// a `WHEN(c)` whose control is a freshly-allocated superposed qbool.
static uint64_t measure_add_mod(std::size_t n, bool wrap_in_when) {
    sturm::QubitPool::instance().reset_for_testing();
    CountCtx cc;
    Reg a = make_reg(n);
    Reg b = make_reg(n);
    Reg nm = make_reg(n);
    Reg r = make_reg(n);

    // Optional WHEN(c) wrapper.  Build the control qbool BEFORE we read
    // the pre-call gate count so the prepare gate emitted by the
    // probabilistic constructor (if any) doesn't pollute the delta.
    sturm::qbool c;
    int c_idx = -1;
    if (wrap_in_when) {
        c_idx = sturm::QubitPool::instance().allocate();
        c     = sturm::qbool::make_non_owning(c_idx, /*val=*/0, /*mask=*/1ULL);
    }

    const uint64_t before = sturm_gate_count(cc.ctx);
    if (wrap_in_when) {
        WHEN(c) {
            sturm::lib_add_mod_dsl<sturm::BitProxy>(
                a.bits.data(), b.bits.data(),
                nm.bits.data(), n, r.bits.data());
        }
    } else {
        sturm::lib_add_mod_dsl<sturm::BitProxy>(
            a.bits.data(), b.bits.data(),
            nm.bits.data(), n, r.bits.data());
    }
    const uint64_t after = sturm_gate_count(cc.ctx);

    if (wrap_in_when) sturm::QubitPool::instance().release(c_idx);
    release_reg(r); release_reg(nm); release_reg(b); release_reg(a);
    return after - before;
}

static uint64_t measure_mul_mod(std::size_t n, bool wrap_in_when) {
    sturm::QubitPool::instance().reset_for_testing();
    CountCtx cc;
    Reg a = make_reg(n);
    Reg b = make_reg(n);
    Reg nm = make_reg(n);
    Reg r = make_reg(n);

    sturm::qbool c;
    int c_idx = -1;
    if (wrap_in_when) {
        c_idx = sturm::QubitPool::instance().allocate();
        c     = sturm::qbool::make_non_owning(c_idx, /*val=*/0, /*mask=*/1ULL);
    }

    const uint64_t before = sturm_gate_count(cc.ctx);
    if (wrap_in_when) {
        WHEN(c) {
            sturm::lib_mul_mod_dsl<sturm::BitProxy>(
                a.bits.data(), b.bits.data(),
                nm.bits.data(), n, r.bits.data());
        }
    } else {
        sturm::lib_mul_mod_dsl<sturm::BitProxy>(
            a.bits.data(), b.bits.data(),
            nm.bits.data(), n, r.bits.data());
    }
    const uint64_t after = sturm_gate_count(cc.ctx);

    if (wrap_in_when) sturm::QubitPool::instance().release(c_idx);
    release_reg(r); release_reg(nm); release_reg(b); release_reg(a);
    return after - before;
}

static uint64_t measure_pow_mod(std::size_t n, bool wrap_in_when) {
    sturm::QubitPool::instance().reset_for_testing();
    CountCtx cc;
    Reg base = make_reg(n);
    Reg exp = make_reg(n);
    Reg nm = make_reg(n);
    Reg r = make_reg(n);

    sturm::qbool c;
    int c_idx = -1;
    if (wrap_in_when) {
        c_idx = sturm::QubitPool::instance().allocate();
        c     = sturm::qbool::make_non_owning(c_idx, /*val=*/0, /*mask=*/1ULL);
    }

    const uint64_t before = sturm_gate_count(cc.ctx);
    if (wrap_in_when) {
        WHEN(c) {
            sturm::lib_pow_mod_dsl<sturm::BitProxy>(
                base.bits.data(), exp.bits.data(),
                nm.bits.data(), n, r.bits.data());
        }
    } else {
        sturm::lib_pow_mod_dsl<sturm::BitProxy>(
            base.bits.data(), exp.bits.data(),
            nm.bits.data(), n, r.bits.data());
    }
    const uint64_t after = sturm_gate_count(cc.ctx);

    if (wrap_in_when) sturm::QubitPool::instance().release(c_idx);
    release_reg(r); release_reg(nm); release_reg(exp); release_reg(base);
    return after - before;
}

// ── Artifact writer ────────────────────────────────────────────────────────
// Writes the captured numbers into a small text file the orchestrator can
// commit alongside the test source.  The path is the test's first argv
// entry when present, otherwise `baseline_gate_counts.txt` in the cwd of
// the running test (CTest sets cwd to the binary directory of the test
// target by default).
struct Row {
    const char* op;
    std::size_t n;
    uint64_t    bare;
    uint64_t    when;
    bool        skipped;
    const char* skip_reason;
};

int main(int argc, char** argv) {
    std::printf("sturm-a3t4.1 P0 baseline gate counts (depth-1 refactor):\n");

    std::vector<Row> rows;

    // n = 8 -- all three primitives.
    rows.push_back({"lib_add_mod_dsl", 8u,
                    measure_add_mod(8u, /*when=*/false),
                    measure_add_mod(8u, /*when=*/true),
                    false, ""});
    rows.push_back({"lib_mul_mod_dsl", 8u,
                    measure_mul_mod(8u, /*when=*/false),
                    measure_mul_mod(8u, /*when=*/true),
                    false, ""});
    rows.push_back({"lib_pow_mod_dsl", 8u,
                    measure_pow_mod(8u, /*when=*/false),
                    measure_pow_mod(8u, /*when=*/true),
                    false, ""});

    // n = 16 -- only add_mod (mul_mod / pow_mod cap at kMaxN=8).
    rows.push_back({"lib_add_mod_dsl", 16u,
                    measure_add_mod(16u, /*when=*/false),
                    measure_add_mod(16u, /*when=*/true),
                    false, ""});
    rows.push_back({"lib_mul_mod_dsl", 16u, 0u, 0u,
                    true, "kMaxN=8 in mul_mod_dsl.hpp"});
    rows.push_back({"lib_pow_mod_dsl", 16u, 0u, 0u,
                    true, "kMaxN=8 in pow_mod_dsl.hpp"});

    // ── Print human-readable table ─────────────────────────────────────────
    std::printf("%-18s  %4s  %14s  %14s\n",
                "primitive", "n", "bare_gates", "when_gates");
    std::printf("%-18s  %4s  %14s  %14s\n",
                "---------", "-", "----------", "----------");
    for (const Row& r : rows) {
        if (r.skipped) {
            std::printf("%-18s  %4zu  %14s  %14s   # %s\n",
                        r.op, r.n, "N/A", "N/A", r.skip_reason);
        } else {
            std::printf("%-18s  %4zu  %14llu  %14llu\n",
                        r.op, r.n,
                        static_cast<unsigned long long>(r.bare),
                        static_cast<unsigned long long>(r.when));
        }
    }

    // ── Write the artifact ─────────────────────────────────────────────────
    // Plain text, two-column "primitive,n,bare,when" format that grep/diff
    // can pick up without a parser.
    const char* out_path = (argc > 1) ? argv[1] : "baseline_gate_counts.txt";
    std::FILE* fp = std::fopen(out_path, "w");
    if (!fp) {
        std::fprintf(stderr, "warning: could not open %s for writing\n",
                     out_path);
    } else {
        std::fprintf(fp, "# sturm-a3t4.1 P0 baseline gate counts.\n");
        std::fprintf(fp, "# Captured by tests/control/test_baseline_gate_counts.cpp.\n");
        std::fprintf(fp, "# Format: <primitive> <n> <bare_gates> <when_gates>\n");
        std::fprintf(fp, "# bare_gates  : sturm_gate_count delta with no enclosing WHEN.\n");
        std::fprintf(fp, "# when_gates  : sturm_gate_count delta inside a single WHEN(c).\n");
        std::fprintf(fp, "# 'N/A' rows  : primitive's kMaxN cap forbids that width.\n");
        for (const Row& r : rows) {
            if (r.skipped) {
                std::fprintf(fp, "%s %zu N/A N/A # %s\n",
                             r.op, r.n, r.skip_reason);
            } else {
                std::fprintf(fp, "%s %zu %llu %llu\n",
                             r.op, r.n,
                             static_cast<unsigned long long>(r.bare),
                             static_cast<unsigned long long>(r.when));
            }
        }
        std::fclose(fp);
        std::printf("wrote artifact: %s\n", out_path);
    }

    // ── Smoke assertions ───────────────────────────────────────────────────
    // The numerical baseline is captured in the artifact above; this test
    // additionally pins three structural invariants that the refactor must
    // not break:
    //   1. every measured row emits at least one gate (we are measuring a
    //      non-empty primitive);
    //   2. wrapping in WHEN(c) never DECREASES the gate count vs. bare
    //      (an extra control flag should at minimum do as much work as
    //      bare, since the lift pattern preserves operation count);
    //   3. add_mod n=16 emits more gates than add_mod n=8 (sanity that
    //      the width parameter is actually flowing through).
    for (const Row& r : rows) {
        if (r.skipped) continue;
        assert(r.bare > 0 && "bare gate count must be non-zero");
        assert(r.when > 0 && "WHEN gate count must be non-zero");
        assert(r.when >= r.bare
               && "WHEN(c) wrapper should not reduce gate count");
    }
    {
        uint64_t add_n8  = 0, add_n16 = 0;
        for (const Row& r : rows) {
            if (std::strcmp(r.op, "lib_add_mod_dsl") == 0) {
                if (r.n == 8u)  add_n8  = r.bare;
                if (r.n == 16u) add_n16 = r.bare;
            }
        }
        assert(add_n8  > 0 && "add_mod n=8 baseline must be measured");
        assert(add_n16 > 0 && "add_mod n=16 baseline must be measured");
        assert(add_n16 > add_n8
               && "add_mod gate count must scale up with width");
    }

    std::printf("All sturm-a3t4.1 baseline checks passed.\n");
    return 0;
}
