# run_plugin_smoke.cmake — PM1-7 plugin-mode smoke probe.
#
# Invoked by tests/transpiler/CMakeLists.txt with:
#   -DCLANGXX=<abs path>      — host clang++ next to the LLVM we linked
#   -DPLUGIN=<abs path>       — libsturm-transpile-plugin.{so,dylib}
#   -DSOURCE=<abs path>       — tests/smoke/minimal_or.cpp
#   -DPREAMBLE=<abs path>     — tests/transpiler/plugin_smoke/preamble.hpp
#   -DOUTPUT_DIR=<abs path>   — scratch dir for the .o + plugin dump
#   -DNM=<abs path>           — llvm-nm (optional; we fall back to system nm)
#
# Contract (PM1-7 acceptance):
#   Compiling tests/smoke/minimal_or.cpp with the plugin attached must
#   succeed AND the resulting .o must carry the gate sequence expected
#   for `uncompute_or(tmp, a, b);` — evidenced by an UNDEFINED reference
#   to `sturm::uncompute_or(sturm::qbool&, sturm::qbool const&,
#   sturm::qbool const&)` in the object file's symbol table. The call
#   site only lands in the .o if the M7 matcher fired during the
#   plugin's parent parse AND the nested EmitObjAction codegen'd the
#   rewritten buffer — so this one assertion covers the whole pipeline.
#
# Additional assertions:
#   - The defined symbol table contains `_Z1fv` (the fixture's `f()`),
#     proving codegen actually ran and produced code for the user
#     function — not an empty object with just the undefined
#     reference.
#   - The plugin's `dump-to=<path>` mirror lands on disk and starts
#     with the `// AUTO-GENERATED by sturm-transpile` sentinel, AND
#     contains the textual `uncompute_or(tmp, a, b);` call — a
#     belt-and-suspenders sanity check that the rewritten buffer
#     wasn't silently empty.
#
# Script exits 0 on success, FATAL_ERROR on any contract violation.

foreach(var CLANGXX PLUGIN SOURCE PREAMBLE OUTPUT_DIR)
    if(NOT DEFINED ${var})
        message(FATAL_ERROR "run_plugin_smoke: ${var} not set")
    endif()
endforeach()

foreach(path "${CLANGXX}" "${PLUGIN}" "${SOURCE}" "${PREAMBLE}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "run_plugin_smoke: required file missing: ${path}")
    endif()
endforeach()

# Fresh scratch dir — a stale .o from a previous run must not mask a
# real regression in the current build.
file(REMOVE_RECURSE "${OUTPUT_DIR}")
file(MAKE_DIRECTORY "${OUTPUT_DIR}")

set(_obj  "${OUTPUT_DIR}/minimal_or.o")
set(_dump "${OUTPUT_DIR}/minimal_or.transpiled.cpp")

# ── Step 1: drive clang++ with -fplugin= over the fixture ──────────────────
# Why `-Xclang -plugin-arg-sturm-transpile -Xclang dump-to=<path>` (the
# cc1 pair) rather than `-fplugin-arg-sturm-transpile-dump-to=<path>`?
# The driver splits the latter at the FIRST hyphen after
# `-fplugin-arg-`, so our hyphenated plugin name `sturm-transpile`
# is mis-parsed (plugin="sturm", arg="transpile-dump-to=..."). The cc1
# pair bypasses that split. See transpiler/src/plugin.cpp's header for
# the full lesson.
execute_process(
    COMMAND "${CLANGXX}"
            -std=c++20
            -include "${PREAMBLE}"
            "-fplugin=${PLUGIN}"
            -Xclang -plugin-arg-sturm-transpile -Xclang "dump-to=${_dump}"
            -c "${SOURCE}"
            -o "${_obj}"
    RESULT_VARIABLE _compile_rc
    OUTPUT_VARIABLE _compile_out
    ERROR_VARIABLE  _compile_err)

if(NOT _compile_rc EQUAL 0)
    message(FATAL_ERROR
        "run_plugin_smoke: plugin compile FAILED (rc=${_compile_rc}).\n"
        "  clang++: ${CLANGXX}\n"
        "  plugin:  ${PLUGIN}\n"
        "  source:  ${SOURCE}\n"
        "stdout:\n${_compile_out}\n"
        "stderr:\n${_compile_err}")
endif()

if(NOT EXISTS "${_obj}")
    message(FATAL_ERROR
        "run_plugin_smoke: compile exited 0 but .o is missing at ${_obj}.\n"
        "stderr:\n${_compile_err}")
endif()

# ── Step 2: dump-to mirror exists + has header + has injected call ─────────
if(NOT EXISTS "${_dump}")
    message(FATAL_ERROR
        "run_plugin_smoke: plugin dump-to= mirror missing at ${_dump}. "
        "The `-Xclang -plugin-arg-sturm-transpile -Xclang dump-to=<path>` "
        "flag did not reach the plugin or the plugin failed to open the "
        "output path.")
endif()

file(READ "${_dump}" _dump_contents)

string(FIND "${_dump_contents}"
            "// AUTO-GENERATED by sturm-transpile" _hdr_pos)
if(NOT _hdr_pos EQUAL 0)
    message(FATAL_ERROR
        "run_plugin_smoke: plugin dump-to= output ${_dump} is missing the "
        "AUTO-GENERATED sentinel at offset 0 (found at ${_hdr_pos}). "
        "PM1-7 requires the plugin dump to match the standalone emitter "
        "byte-for-byte so a re-transpile is idempotent.")
endif()

string(REGEX MATCH
    "uncompute_or[ \t]*\\([ \t]*tmp[ \t]*,[ \t]*a[ \t]*,[ \t]*b[ \t]*\\)"
    _call_hit "${_dump_contents}")
if(NOT _call_hit)
    message(FATAL_ERROR
        "run_plugin_smoke: plugin dump-to= output ${_dump} does not contain "
        "the expected `uncompute_or(tmp, a, b)` call. The M7 matcher did "
        "not fire on the minimal_or fixture through the plugin parent "
        "parse — likely a regression in the matcher pool or in the "
        "plugin's TranspileConsumer EmissionMode wiring.")
endif()

# ── Step 3: object-file symbol table inspection ────────────────────────────
# We use the LLVM/clang nm that ships with the toolchain we linked
# against. Fall back to whatever `nm` is on PATH; both emit the
# Itanium-mangled symbols we match on. The `-u` flag filters to
# undefined references only — the `uncompute_or` call site is a
# relocation against an undefined external.
if(NOT DEFINED NM OR NM STREQUAL "" OR NOT EXISTS "${NM}")
    find_program(_NM_FALLBACK NAMES llvm-nm nm)
    if(NOT _NM_FALLBACK)
        message(FATAL_ERROR
            "run_plugin_smoke: no nm tool found. Pass -DNM=<abs path> or "
            "install llvm-nm / binutils nm.")
    endif()
    set(NM "${_NM_FALLBACK}")
endif()

execute_process(
    COMMAND "${NM}" "${_obj}"
    RESULT_VARIABLE _nm_rc
    OUTPUT_VARIABLE _nm_out
    ERROR_VARIABLE  _nm_err)

if(NOT _nm_rc EQUAL 0)
    message(FATAL_ERROR
        "run_plugin_smoke: `${NM} ${_obj}` exited ${_nm_rc}.\n"
        "stderr:\n${_nm_err}")
endif()

# Defined `f()` — the fixture's only function. Its Itanium mangling is
# `_Z1fv` ("_Z" + length "1" + "f" + parameter list "v" = void).
string(FIND "${_nm_out}" "_Z1fv" _f_pos)
if(_f_pos LESS 0)
    message(FATAL_ERROR
        "run_plugin_smoke: object file ${_obj} does not define `f()` "
        "(mangled `_Z1fv`). Either the nested EmitObjAction produced no "
        "code or the fixture body was deleted by the rewrite pass.\n"
        "nm output:\n${_nm_out}")
endif()

# Undefined `sturm::uncompute_or(qbool&, const qbool&, const qbool&)`.
# Itanium mangling: _ZN5sturm12uncompute_orERNS_5qboolERKS0_S3_
#   N5sturm = "sturm::"  12uncompute_or = name
#   E (end of nested)  R = &   NS_5qbool = sturm::qbool  E (end of nested)
#   R K S0_ = `const qbool&` (S0_ substitutes `NS_5qboolE`)
#   S3_ = fourth substitution = `const qbool&`
# The presence of this as an UNDEFINED reference is the PM1-7 positive
# signal: the matcher fired, the rewrite added the call, and the nested
# codegen emitted a relocation against the runtime library's copy.
string(FIND "${_nm_out}"
            "_ZN5sturm12uncompute_orERNS_5qboolERKS0_S3_" _unc_pos)
if(_unc_pos LESS 0)
    message(FATAL_ERROR
        "run_plugin_smoke: object file ${_obj} has no reference to "
        "`sturm::uncompute_or(qbool&, const qbool&, const qbool&)` "
        "(mangled `_ZN5sturm12uncompute_orERNS_5qboolERKS0_S3_`). This "
        "means the transpiler-injected `uncompute_or(tmp, a, b);` call "
        "did not survive into codegen. Either the matcher did not fire, "
        "the rewrite was lost between ExecuteAction and the nested "
        "CompilerInvocation, or the preamble declaration of "
        "`sturm::uncompute_or` is not being picked up by ADL from the "
        "fixture's `using sturm::qbool;` TU shape.\n"
        "nm output:\n${_nm_out}")
endif()

message(STATUS
    "run_plugin_smoke: OK — ${_obj} defines f() and references "
    "sturm::uncompute_or; dump-to mirror has header + injected call.")
