// emitter.hpp — M9 C++ emitter (clang::Rewriter based).
//
// Purpose
// -------
// The emitter closes the transpiler pipeline:
//
//   M7 matcher  →  M8 uncompute_pass  →  M9 emitter  →  disk
//
// Given the SourceManager + Rewriter bound to the user's source file and
// the flat list of UncomputeInsertion records produced by M8, the emitter
//
//   1. Calls clang::Rewriter::InsertTextBefore at each insertion's anchor
//      SourceLocation (the originating scope's `close_brace`), dropping
//      the exact source text M8 prepared.
//   2. Serializes the rewritten buffer into a std::string.
//   3. Prepends the idempotency header (see idempotency_header() below) so
//      the transpiler can recognize its own output on a second run.
//   4. Writes the final bytes to `<output_dir>/<relpath-of-source>` via
//      the M4 io.cpp helpers (write_file / resolve_output_path).
//
// Contract
// --------
// - The Rewriter's lifetime must be at least the duration of this call.
//   The emitter does not take ownership, does not reset the Rewriter, and
//   leaves the in-memory edit state in place so callers can inspect it.
// - Insertions are applied in the order they appear in `insertions`. M8's
//   reverse-iteration (LIFO) ordering is preserved here — Rewriter merges
//   multiple insertions at the same location in call order, so the last
//   call's text ends up closest to the anchor location. This is exactly
//   what the uncompute pass wants: the most recently computed
//   intermediate's uncompute call lands first, closest to `}`.
// - `source_path` is embedded in the idempotency header verbatim. Callers
//   pass whatever path they want the header to carry (typically the
//   user-supplied input path, relative or absolute, however it appeared
//   on the command line). No normalization happens here.
// - On I/O failure (`write_file` returns false) the emitter returns
//   false. A best-effort diagnostic is written to stderr.
//
// Helpers exported for M5 / tests
// -------------------------------
// The idempotency_header() and should_skip() helpers logically belong to
// the (not-yet-implemented) M5 skip module. We declare them here because
// the MVP needs them on the M9 path (header prepending for the golden
// snapshot, and M9's idempotency test treats a re-run on prior output as
// a pass-through). When M5 lands in its own module, it will either factor
// these out into `skip.hpp` or keep them here — either is a pure-rename
// refactor and breaks no external API.
//
// LOC budget: this header stays small; the .cpp carries the implementation.

#ifndef STURM_TRANSPILE_EMITTER_HPP
#define STURM_TRANSPILE_EMITTER_HPP

#include "sturm/transpile/uncompute_pass.hpp"

#include "clang/Basic/SourceManager.h"
#include "clang/Rewrite/Core/Rewriter.h"

#include <string>
#include <string_view>
#include <vector>

namespace sturm::transpile {

/// Build the two-line AUTO-GENERATED / Source: comment block the emitter
/// prepends to every transpiled output.
///
/// The exact byte-for-byte shape is (no trailing blank line):
///
///     // AUTO-GENERATED by sturm-transpile -- do not edit
///     // Source: <source_path>
///
/// The em-dash character in the original PRD excerpt is rendered as two
/// ASCII hyphens here so the file is clean 7-bit source and no locale /
/// editor will accidentally transcode it.
std::string idempotency_header(std::string_view source_path);

/// Return true if `head` (the first ~512 bytes of a file) indicates the
/// file must be passed through verbatim. Two cases:
///
///   - "// sturm-transpile: skip" on the first non-blank line (magic
///     opt-out, per PRD §"Opt-Out Mechanism").
///   - The AUTO-GENERATED sentinel on the first non-blank line (marks
///     already-transpiled output, enforcing idempotency per PRD §AC #5).
///
/// Leading blank lines / whitespace-only lines are tolerated. The check
/// is strict line-prefix matching once those are stripped.
bool should_skip(std::string_view head);

/// Full MVP emit step.
///
/// Inputs:
///   - `sm`            : the SourceManager bound to the parsed user source.
///   - `rw`            : a Rewriter constructed against `sm`.
///   - `insertions`    : M8 output, in LIFO-within-scope order.
///   - `source_path`   : path to embed in the idempotency header.
///   - `output_dir`    : directory under which the output is placed; the
///                       relative path of `source_path` is mirrored under
///                       it (via `resolve_output_path` from M4).
///
/// Behavior:
///   1. Apply every `rw.InsertTextBefore(ins.insert_before, ins.code)`.
///   2. Fetch the rewrite buffer for the main file; serialize to string.
///   3. Prepend `idempotency_header(source_path)`.
///   4. Write the result to `resolve_output_path(source_path, output_dir)`.
///
/// Returns true on success, false on any I/O or Rewriter failure.
bool emit(const clang::SourceManager& sm,
          clang::Rewriter& rw,
          const std::vector<UncomputeInsertion>& insertions,
          std::string_view source_path,
          std::string_view output_dir);

} // namespace sturm::transpile

#endif // STURM_TRANSPILE_EMITTER_HPP
