// skip.hpp — M5 skip marker + idempotency header helpers.
//
// Two orthogonal pass-through cases:
//
//   1. Skip marker (PRD §"Opt-Out Mechanism", AC #6). A file whose first
//      non-blank line is `// sturm-transpile: skip` is copied verbatim by
//      the driver. Transpilation is suppressed for that translation unit.
//
//   2. Idempotency header (PRD AC #5). Every transpiled output begins with
//      the two-line sentinel
//
//          // AUTO-GENERATED by sturm-transpile -- do not edit
//          // Source: <original path>
//
//      A subsequent run whose input already starts with the sentinel is
//      also treated as pass-through, so running the transpiler on its own
//      output produces a byte-identical file.
//
// Contract
// --------
// These are PURE STRING FUNCTIONS. They do not open files, they do not
// touch LibTooling, and they introduce no dependency on LLVM/Clang. The
// driver reads the first ~512 bytes of the input file and hands them to
// should_skip(); the M9 emitter prepends idempotency_header() to its
// output. Two call sites, one module, zero LibTooling coupling — which is
// why this header lives outside the emitter's dependency graph.
//
// The em-dash from the PRD excerpt is rendered here as two ASCII hyphens
// so the file is clean 7-bit source and no locale / editor will
// accidentally transcode it.
//
// LOC budget: header ≤ 30 lines. Implementation in src/skip.cpp.

#ifndef STURM_TRANSPILE_SKIP_HPP
#define STURM_TRANSPILE_SKIP_HPP

#include <string>
#include <string_view>

namespace sturm::transpile {

/// Build the two-line AUTO-GENERATED / Source: comment block the emitter
/// prepends to every transpiled output. The exact byte-for-byte shape is
/// (no trailing blank line):
///
///     // AUTO-GENERATED by sturm-transpile -- do not edit
///     // Source: <source_path>
std::string idempotency_header(std::string_view source_path);

/// Return true if `head` (the first ~512 bytes of a file) indicates the
/// file must be passed through verbatim. Two cases:
///
///   - `// sturm-transpile: skip` on the first non-blank line.
///   - The AUTO-GENERATED sentinel on the first non-blank line.
///
/// Leading blank / whitespace-only lines are tolerated. Partial or garbled
/// markers are treated as non-skip so users do not get mystery
/// pass-throughs.
bool should_skip(std::string_view head);

} // namespace sturm::transpile

#endif // STURM_TRANSPILE_SKIP_HPP
