#!/usr/bin/env python3
"""lint_public_headers.py — STURM Epic E2.M2 (sturm-nalq.2).

Walks every public header under ``include/sturm/`` (everything outside
``include/sturm/detail/``) and parses each ``#include`` line. Fails on:
non-existent project paths; ``sturm/detail/...`` reaches not in
``DETAIL_ALLOWLIST``; quoted non-``sturm/`` includes not in
``VENDOR_ALLOWLIST``. ``<system>`` headers are accepted. Each violation
prints ``path:line: <msg>``; the script exits non-zero. LOC <= 150.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# DETAIL_ALLOWLIST: pre-existing transitions inherited from the E2.M1
# detail/ move where a public template header inlines a detail/ DSL or
# proxy for instantiation. A future PRD §3.3 split should hoist these
# into thin shims that defer to detail-only TUs, shrinking this map.
DETAIL_ALLOWLIST: dict[str, set[str]] = {
    "include/sturm/qtypes/qint_arith_v3.hpp": {
        "sturm/detail/qtypes/bit_proxy.hpp",
        "sturm/detail/lib/adder_dsl.hpp",
        "sturm/detail/lib/mul_dsl.hpp",
        "sturm/detail/lib/div_dsl.hpp",
        "sturm/detail/lib/mod_dsl.hpp",
    },
    "include/sturm/qtypes/qint_arith_backend.hpp": {
        "sturm/detail/lib/mod_dsl.hpp",
    },
    "include/sturm/qtypes/qint_bitwise_backend.hpp": {
        "sturm/detail/qtypes/bit_proxy.hpp",
    },
    "include/sturm/qtypes/qint_bitwise_v3.hpp": {
        "sturm/detail/qtypes/bit_proxy.hpp",
    },
    "include/sturm/qtypes/qint_compare.hpp": {
        "sturm/detail/qtypes/bit_proxy.hpp",
    },
    "include/sturm/qtypes/qint_compare_v3.hpp": {
        "sturm/detail/lib/compare_dsl.hpp",
    },
    "include/sturm/ops/qint_modular.hpp": {
        "sturm/detail/lib/add_mod_dsl.hpp",
        "sturm/detail/lib/mul_mod_dsl.hpp",
        "sturm/detail/lib/pow_mod_dsl.hpp",
        "sturm/detail/qtypes/bit_proxy.hpp",
    },
    # Conditional under STURM_BACKEND_ENABLED — see the ifdef in qint.hpp.
    "include/sturm/qtypes/qint.hpp": {
        "sturm/detail/qtypes/lossy_oop.hpp",
    },
    # Conditional under STURM_BACKEND_ENABLED — see uncompute_api.hpp.
    "include/sturm/uncompute/uncompute_api.hpp": {
        "sturm/detail/lib/compare_dsl.hpp",
    },
}

# VENDOR_ALLOWLIST: quoted includes outside include/sturm/. Currently
# only the orkan vendor header, which is resolved on the include path
# between a vendored stub and an installed copy at configure time.
VENDOR_ALLOWLIST: dict[str, set[str]] = {
    "include/sturm/backend/exec_simulate.hpp": {"orkan/orkan.hpp"},
    "include/sturm/backend/orkan_bridge.hpp": {"orkan/orkan.hpp"},
}

INCLUDE_RE = re.compile(r'^\s*#\s*include\s*([<"])([^>"]+)[>"]')


def public_headers(include_root: Path):
    """Yield every public header (excludes include/sturm/detail/)."""
    detail = (include_root / "detail").resolve()
    for path in sorted(include_root.rglob("*")):
        if not path.is_file() or path.suffix not in (".hpp", ".h", ".in"):
            continue
        if detail in path.resolve().parents:
            continue
        yield path


def lint_file(path: Path, repo_root: Path) -> list[str]:
    """Return violation strings for one public header."""
    rel = path.relative_to(repo_root).as_posix()
    allowed_detail = DETAIL_ALLOWLIST.get(rel, set())
    allowed_vendor = VENDOR_ALLOWLIST.get(rel, set())
    violations: list[str] = []
    for lineno, line in enumerate(
        path.read_text(encoding="utf-8", errors="replace").splitlines(), 1
    ):
        m = INCLUDE_RE.match(line)
        if not m:
            continue
        bracket, target = m.group(1), m.group(2)
        is_sturm = target.startswith("sturm/")
        if not is_sturm:
            if bracket == "<":
                continue  # system header
            if target in allowed_vendor:
                continue
            violations.append(
                f'{rel}:{lineno}: include "{target}" is outside include/sturm/'
            )
            continue
        if target.startswith("sturm/detail/") and target not in allowed_detail:
            violations.append(
                f"{rel}:{lineno}: public header reaches into detail/: "
                f"'{target}' (not in DETAIL_ALLOWLIST for {rel})"
            )
            continue
        # version.hpp is generated by configure_file; accept without
        # an on-disk check.
        if target == "sturm/version.hpp":
            continue
        resolved = repo_root / "include" / target
        if not resolved.is_file():
            violations.append(
                f"{rel}:{lineno}: include '{target}' does not exist "
                f"(expected {resolved.relative_to(repo_root).as_posix()})"
            )
    return violations


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--repo-root", type=Path, default=None)
    args = parser.parse_args(argv)
    repo_root = (args.repo_root or Path(__file__).resolve().parents[1]).resolve()
    include_root = repo_root / "include" / "sturm"
    if not include_root.is_dir():
        print(f"error: {include_root} not found", file=sys.stderr)
        return 2
    violations: list[str] = []
    for header in public_headers(include_root):
        violations.extend(lint_file(header, repo_root))
    for v in violations:
        print(v)
    if violations:
        print(f"\nlint_public_headers: {len(violations)} violation(s).",
              file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
