# cmake/SturmTranspile.cmake — the add_quantum_executable() helper.
#
# Defines one public function, `add_quantum_executable(target src1 src2 ...)`,
# which is the documented build-system entry point for downstream consumers of
# the STURM transpiler pipeline.
#
# Two modes (PM1-5)
# -----------------
# The helper ships two paths, selected by the STURM_TRANSPILE_MODE cache
# variable:
#
#   * "plugin" (default) — each quantum source goes through a single
#     `clang++ -fplugin=$<TARGET_FILE:sturm-transpile-plugin> -c <src> -o
#     <src>.o` compile. The Clang plugin registered by
#     transpiler/src/plugin.cpp runs the shared TranspileConsumer under a
#     ReplaceAction, then drives a nested CompilerInvocation +
#     EmitObjAction over the rewritten buffer to produce the object file.
#     No intermediate source file is required on disk — the rewrite lives
#     in memory. To keep the injected-observability CTests (which grep
#     the rewritten buffer for injected `uncompute_*` calls) working
#     unchanged, we additionally pass
#       -Xclang -plugin-arg-sturm-transpile -Xclang dump-to=<path>
#     per-source so the plugin mirrors the rewritten buffer onto disk at
#     the same `${CMAKE_BINARY_DIR}/sturm_gen/<relpath>` path the legacy
#     "dump" mode writes. The `-fplugin=...` option uses a cc1-level
#     `-Xclang -plugin-arg-...` pair rather than the driver-level
#     `-fplugin-arg-<name>-<arg>` spelling because the driver splits the
#     latter at the FIRST hyphen and our plugin name "sturm-transpile"
#     does not survive that split intact (see transpiler/src/plugin.cpp
#     header comment).
#
#   * "dump" — legacy fallback. Each quantum source goes through a
#     per-source `add_custom_command` that invokes the standalone
#     `sturm-transpile` binary with `--output-dir
#     ${CMAKE_BINARY_DIR}/sturm_gen` and writes a rewritten sibling on
#     disk at `${CMAKE_BINARY_DIR}/sturm_gen/<relpath-of-source>`. That
#     generated file carries the `// AUTO-GENERATED by sturm-transpile`
#     idempotency header (the in-memory plugin path does not) and the
#     generated file becomes the compile unit rather than the raw source.
#     This path is what the `transpiler_idempotent_example_*` CTests
#     exercise — re-running the standalone binary on the already-emitted
#     sibling must produce a byte-identical file. "dump" is also the
#     right choice for a developer-diagnostic workflow where the
#     rewritten .cpp on disk IS the artifact under inspection.
#
# Behavior (shared between modes)
# -------------------------------
# Every source file is routed through the selected path. In "plugin" mode
# the rewritten buffer is mirrored to `${CMAKE_BINARY_DIR}/sturm_gen/<relpath-of-source>`
# via the plugin's `dump-to=` flag (for injected-test observability) and
# also fed to the nested codegen; in "dump" mode the rewritten file at
# that same path is the compile unit itself.
#
# Idempotency
# -----------
# The helper uses an include-guard pattern so multiple includes in the
# same CMake run are harmless. This matters because root CMakeLists.txt
# and downstream FetchContent users may both pull the file in.

if(DEFINED _STURM_TRANSPILE_CMAKE_INCLUDED)
    return()
endif()
set(_STURM_TRANSPILE_CMAKE_INCLUDED ON)

# ── Mode selector ─────────────────────────────────────────────────────────
# Cache variable with STRINGS metadata so the GUI offers the two legal
# values. Any other value hard-errors below — a silent typo here would
# silently fall into the wrong path.
set(STURM_TRANSPILE_MODE "plugin" CACHE STRING
    "Sturm transpile flow: 'plugin' (in-memory, default) or 'dump' \
(write rewritten .cpp sibling, legacy path used by idempotency CTests).")
set_property(CACHE STURM_TRANSPILE_MODE PROPERTY STRINGS "plugin" "dump")

if(NOT (STURM_TRANSPILE_MODE STREQUAL "plugin" OR
        STURM_TRANSPILE_MODE STREQUAL "dump"))
    message(FATAL_ERROR
        "STURM_TRANSPILE_MODE='${STURM_TRANSPILE_MODE}' is not one of "
        "{plugin, dump}. Reconfigure with -DSTURM_TRANSPILE_MODE=plugin "
        "(default) or -DSTURM_TRANSPILE_MODE=dump.")
endif()

# ── Public entry point ────────────────────────────────────────────────────
# Usage:
#     add_quantum_executable(<target>
#         <source> [<source> ...]
#         [PLUGINS <path> [<path> ...]])
#
# Accepts one or more source files. Relative paths are resolved against
# CMAKE_CURRENT_SOURCE_DIR. Absolute paths are respected verbatim.
#
# PLUGINS (PM4-5 / `sturm-4oyr.6`)
# --------------------------------
# Optional multi-value keyword accepting a list of absolute shared-library
# paths (or $<TARGET_FILE:...> generator expressions resolving to same).
# Each entry is threaded to the Clang plugin at parse time as a
# per-source cc1 arg pair of EXACTLY:
#
#     -Xclang -plugin-arg-sturm-transpile -Xclang load=<abs-path>
#
# so `plugin.cpp`'s `ParseArgs` sees a `load=<abs-path>` token, dlopen's
# the given `.so` / `.dylib` with `RTLD_LOCAL | RTLD_NOW`, validates the
# plugin's Clang version against the host's `CLANG_VERSION_STRING`, and
# queues its `sturm_register_plugin_v1` entry for the per-consumer
# `Registry` drain.
#
# Why the cc1 spelling? The driver-level `-fplugin-arg-<plugin>-<arg>`
# flag splits on the FIRST hyphen after `-fplugin-arg-`, so our
# hyphenated plugin name "sturm-transpile" does not survive the
# driver-level spelling (the driver sees plugin "sturm" + arg
# "transpile-<rest>"). Going through `-Xclang -plugin-arg-sturm-transpile
# -Xclang <arg>` sidesteps that split and delivers the arg verbatim.
# This matches the existing `dump-to=<path>` plumbing below.
#
# PLUGINS is PLUGIN-MODE ONLY. In dump mode the transpile step runs the
# standalone `sturm-transpile` binary, not a Clang plugin, so there is
# no `-plugin-arg-sturm-transpile` slot to thread `load=<path>` through.
# Passing PLUGINS with -DSTURM_TRANSPILE_MODE=dump is a configuration
# error and fails the helper with a FATAL_ERROR.
#
# Side effects (common to both modes):
#   - Defines an executable target `<target>`.
#   - Links `<target>` against `sturm` PRIVATE if that target exists.
#   - Registers a dependency on either `sturm-transpile` (dump mode) or
#     `sturm-transpile-plugin` (plugin mode).
function(add_quantum_executable target)
    # cmake_parse_arguments peels off keyword arguments BEFORE ARGN is
    # iterated. The PLUGINS list is MULTI_VALUE so the user can pass
    # several paths; everything not claimed by PLUGINS stays in
    # STURM_AQE_UNPARSED_ARGUMENTS as the positional source list.
    #
    # `PARSE_ARGV 1` skips the `target` positional so ${ARGN} alone is
    # parsed. OPTIONS_LIST / ONE_VALUE_LIST are both empty — today
    # only PLUGINS is supported; future keywords (e.g. SOURCES) can be
    # added without breaking callers because positional sources remain
    # the default path.
    set(_options "")
    set(_one_value "")
    set(_multi_value PLUGINS)
    cmake_parse_arguments(PARSE_ARGV 1 STURM_AQE
        "${_options}" "${_one_value}" "${_multi_value}")

    # Positional sources survive in STURM_AQE_UNPARSED_ARGUMENTS. Every
    # pre-PM4-5 call site passed only source paths, so the contract is
    # byte-identical for those callers.
    set(sources ${STURM_AQE_UNPARSED_ARGUMENTS})
    if(NOT sources)
        message(FATAL_ERROR
            "add_quantum_executable(${target}): no source files provided. "
            "Pass one or more .cpp files after the target name.")
    endif()

    # STURM_ANCILLA_CAPACITY must match the value baked into the rest of
    # the build (root CMakeLists.txt add_compile_definitions) and the
    # value exposed to out-of-tree find_package(sturm) consumers via
    # sturmConfig.cmake (which sets this variable before include()ing
    # this file). Referencing ${STURM_ANCILLA_CAPACITY} here keeps the
    # transpile pass and the compile pass in sync, preventing divergent
    # macro-driven template instantiations.
    if(NOT DEFINED STURM_ANCILLA_CAPACITY)
        message(FATAL_ERROR
            "add_quantum_executable(${target}): STURM_ANCILLA_CAPACITY "
            "is not defined. In-tree builds set it in the top-level "
            "CMakeLists.txt; find_package(sturm) consumers receive it "
            "from sturmConfig.cmake. If you are including "
            "SturmTranspile.cmake directly, set STURM_ANCILLA_CAPACITY "
            "before the include().")
    endif()

    # PLUGINS is a plugin-mode-only feature. Forwarding it to dump mode
    # would silently drop the paths because the dump-mode path invokes
    # the standalone `sturm-transpile` binary (no `-plugin-arg-` slot),
    # so fail loudly here with an actionable reconfigure hint.
    if(STURM_AQE_PLUGINS AND NOT (STURM_TRANSPILE_MODE STREQUAL "plugin"))
        message(FATAL_ERROR
            "add_quantum_executable(${target}): PLUGINS argument is only "
            "supported under STURM_TRANSPILE_MODE=plugin (the default). "
            "The dump-mode path invokes the standalone `sturm-transpile` "
            "binary and has no Clang-plugin `-plugin-arg-` slot to thread "
            "`load=<path>` through. Reconfigure with "
            "-DSTURM_TRANSPILE_MODE=plugin or drop the PLUGINS argument.")
    endif()

    if(STURM_TRANSPILE_MODE STREQUAL "plugin")
        _sturm_add_quantum_executable_plugin(${target}
            SOURCES ${sources}
            PLUGINS ${STURM_AQE_PLUGINS})
    else()
        _sturm_add_quantum_executable_dump(${target} ${sources})
    endif()

    # Link the STURM interface library if it is available. It is the
    # standard way a consumer gains access to `<sturm/sturm.hpp>` and the
    # public compile-feature set (C++20). Shared between modes.
    if(TARGET sturm)
        target_link_libraries(${target} PRIVATE sturm)
    else()
        message(STATUS
            "add_quantum_executable(${target}): `sturm` target not found; "
            "skipping target_link_libraries. Consumers should link `sturm` "
            "manually or provide a find_package(sturm) wrapper.")
    endif()
endfunction()

# ── Plugin-mode implementation (default) ──────────────────────────────────
# Each quantum source becomes a compile unit directly — the plugin does
# the rewrite in-memory and drives the nested EmitObjAction. A
# `dump-to=<path>` plugin arg is threaded per-source so the rewritten
# buffer is ALSO mirrored to `${CMAKE_BINARY_DIR}/sturm_gen/<relpath>`
# for the injected-observability CTests that grep that file for
# transpiler-injected `uncompute_*` calls.
#
# PM4-5: This helper additionally accepts `PLUGINS` — a list of absolute
# shared-library paths that get threaded to the plugin's `ParseArgs` as
# per-source `load=<path>` cc1 arg pairs. The outer public entry point
# (`add_quantum_executable`) does the keyword parsing; we forward the
# parsed SOURCES + PLUGINS lists through named keyword arguments here so
# future helper-internal keyword additions do not collide with the list
# positions.
function(_sturm_add_quantum_executable_plugin target)
    set(_options "")
    set(_one_value "")
    set(_multi_value SOURCES PLUGINS)
    cmake_parse_arguments(PARSE_ARGV 1 STURM_AQE_PLUGIN
        "${_options}" "${_one_value}" "${_multi_value}")

    # SOURCES is the primary payload; a caller that failed to pass any
    # would have tripped the outer helper's no-sources check, but
    # belt-and-suspenders matters here because this helper is also
    # reachable from a future find_package(sturm) consumer that copies
    # the dispatch shape.
    set(sources ${STURM_AQE_PLUGIN_SOURCES})
    set(plugins ${STURM_AQE_PLUGIN_PLUGINS})

    # The plugin must be a known target before we reference its
    # TARGET_FILE. Both the in-tree build (transpiler/CMakeLists.txt
    # ALIAS) and find_package(sturm) consumers (sturmConfig.cmake.in
    # IMPORTED) register `sturm::transpile-plugin`; we prefer the
    # namespaced spelling so installed-prefix users hit the same code
    # path as in-tree builds (sturm-vr0v.1 / PRD §3.5).
    if(NOT TARGET sturm::transpile-plugin)
        message(FATAL_ERROR
            "add_quantum_executable(${target}): the "
            "`sturm::transpile-plugin` target is not defined. Ensure the "
            "STURM transpiler subdirectory is added "
            "(add_subdirectory(transpiler) or find_package(sturm)) "
            "before calling add_quantum_executable, OR reconfigure with "
            "-DSTURM_TRANSPILE_MODE=dump to use the legacy path.")
    endif()

    add_executable(${target} ${sources})

    # Target-wide: load the plugin. The flag is idempotent — Clang
    # ignores duplicate `-fplugin=` entries — so appending here and
    # again per-source would be safe, but target-wide is cleaner.
    #
    # CXX-only gate (sturm-8pas): `-fplugin=<path>` is a Clang plugin
    # flag, but `target_compile_options` propagates to every language
    # the target compiles. When a user target (or a transitively-pulled
    # core source like `src/sturm/core/gate_kind.c`) contains a `.c`
    # file, CMake routes it through the configured C compiler — which
    # under a default Ubuntu install is `gcc` via `/usr/bin/cc`, not
    # the `clang++-17` we set as `CMAKE_CXX_COMPILER`. GCC's plugin
    # loader treats `-fplugin=<path>` as a GCC-plugin request and
    # demands a `plugin_is_GPL_compatible` symbol the Clang plugin TU
    # does not (and should not) export — producing the documented
    # `cc1: fatal error: ... is not licensed under a GPL-compatible
    # license` failure that cascades through every `build_example_*`
    # CTest under a clang++-17 build. Wrapping the flag in a
    # `$<COMPILE_LANGUAGE:CXX>` generator expression keeps it on the
    # C++ compile lines (where the Clang frontend handles it) and off
    # the C compile lines (where GCC chokes). The CXX-only restriction
    # is also semantically correct: the plugin only matches AST shapes
    # that can only appear in C++ sources (`sturm::qbool`,
    # `sturm::qint`, etc.), so loading it on a C compile is wasted
    # work even when the loader is Clang.
    target_compile_options(${target} PRIVATE
        "$<$<COMPILE_LANGUAGE:CXX>:-fplugin=$<TARGET_FILE:sturm::transpile-plugin>>")

    # STURM_BACKEND_ENABLED has to be visible to the PARENT clang parse
    # (the one that walks the AST and runs the matchers) as well as to
    # the nested invocation. In dump mode the transpiler writes a
    # `#define STURM_BACKEND_ENABLED 1` at the top of the generated
    # file, so the compile pass picks it up naturally. In plugin mode
    # the source file may or may not define it — threading it on the
    # target keeps both the parent parse and the nested codegen in the
    # same configuration as the legacy path used to produce.
    target_compile_definitions(${target} PRIVATE STURM_BACKEND_ENABLED=1)

    # Build-order dependency: when the plugin is rebuilt (e.g. a
    # transpiler matcher source changed), every target using it must
    # recompile. Without this, CMake has no reason to rerun the
    # compile step on an unchanged user source — which would bake in
    # the old plugin's rewrite behavior. `add_dependencies` rejects
    # ALIAS targets, so we resolve the underlying name first via
    # ALIASED_TARGET (in-tree) and fall back to the namespaced spelling
    # for IMPORTED targets registered by sturmConfig.cmake.in.
    get_target_property(_sturm_aliased sturm::transpile-plugin ALIASED_TARGET)
    if(_sturm_aliased)
        add_dependencies(${target} ${_sturm_aliased})
    else()
        # IMPORTED target (find_package consumer): no build step to
        # depend on, the file is shipped pre-built. Skip silently.
    endif()

    # Per-source plumbing: wire a `-Xclang -plugin-arg-sturm-transpile
    # -Xclang dump-to=<path>` pair so the plugin mirrors the rewritten
    # buffer onto disk at the same path layout dump-mode emits. The
    # flag is per-source because the destination path is per-source.
    #
    # Why the cc1 spelling? The user-facing
    # `-fplugin-arg-<plugin>-<arg>` driver flag splits on the FIRST
    # hyphen after `-fplugin-arg-`, so a hyphenated plugin name like
    # "sturm-transpile" is mis-parsed as plugin "sturm" + arg
    # "transpile-<rest>". Going through `-Xclang -plugin-arg-<name>`
    # sidesteps the driver and lets us spell the cc1 arg pair
    # verbatim.
    foreach(src ${sources})
        if(IS_ABSOLUTE "${src}")
            set(abs_src "${src}")
        else()
            set(abs_src "${CMAKE_CURRENT_SOURCE_DIR}/${src}")
        endif()
        get_filename_component(abs_src "${abs_src}" ABSOLUTE)

        # Mirror the path layout of the legacy dump path:
        # <build>/sturm_gen/<relpath-under-CMAKE_SOURCE_DIR>. Sources
        # outside CMAKE_SOURCE_DIR collapse to basename(src) — same
        # rule as the dump-mode fallback and as the transpiler's own
        # resolve_output_path() for absolute inputs.
        file(RELATIVE_PATH rel_src "${CMAKE_SOURCE_DIR}" "${abs_src}")
        if(rel_src MATCHES "^\\.\\.")
            get_filename_component(rel_src "${abs_src}" NAME)
        endif()
        set(dump_path "${CMAKE_BINARY_DIR}/sturm_gen/${rel_src}")
        get_filename_component(dump_dir "${dump_path}" DIRECTORY)

        # The plugin writes `dump-to=<path>` with a plain std::ofstream
        # which will fail if the destination directory does not exist.
        # Create the directory at configure time so the first compile
        # has somewhere to write.
        file(MAKE_DIRECTORY "${dump_dir}")

        # Source-level compile options: per-source because the path
        # differs per source. CMake's source-file COMPILE_OPTIONS
        # append to the command line after the target-level
        # COMPILE_OPTIONS, which is the ordering we want (plugin
        # loaded first, then its args).
        set_property(SOURCE "${abs_src}" APPEND PROPERTY COMPILE_OPTIONS
            "-Xclang"
            "-plugin-arg-sturm-transpile"
            "-Xclang"
            "dump-to=${dump_path}")

        # PM4-5 (`sturm-4oyr.6`): for each PLUGINS entry, append a
        # separate `-Xclang -plugin-arg-sturm-transpile -Xclang
        # load=<abs-path>` cc1 arg pair. Mirrors the dump-to= plumbing
        # above — every plugin arg ride the same cc1 pair shape because
        # the driver mis-parses the hyphenated plugin name under the
        # user-facing `-fplugin-arg-<name>-<arg>` spelling (see the
        # file header for the full lesson). The plugin's `ParseArgs`
        # (transpiler/src/plugin.cpp) collects every `load=<path>`
        # token into a pending-loads list and processes them in order
        # after the full arg scan completes (so `verbose` later in the
        # list still influences earlier `load=` diagnostics).
        #
        # Each plugin path produces its OWN 4-token tuple rather than
        # collapsing into a single `-plugin-arg-` scope — Clang's cc1
        # `-plugin-arg-<name> <arg>` only takes ONE arg token per
        # pair, so two `load=` payloads require two pairs. The order
        # in which the pairs land on the command line matches the
        # PLUGINS list order; `ParseArgs` then registers the plugins
        # in that same order (plan §6: "Execute the queued loads in
        # command-line order").
        foreach(plugin_path ${plugins})
            set_property(SOURCE "${abs_src}" APPEND PROPERTY
                COMPILE_OPTIONS
                "-Xclang"
                "-plugin-arg-sturm-transpile"
                "-Xclang"
                "load=${plugin_path}")
        endforeach()

        # Note on plugin-change invalidation: `add_dependencies` above
        # gives us a target-level build order (the plugin .so is
        # rebuilt before any object compile in ${target}), but CMake's
        # Makefiles generator does NOT let us express a file-level
        # OBJECT_DEPENDS on a `$<TARGET_FILE:...>` generator
        # expression. Touching a transpiler matcher therefore does not
        # force a rebuild of an already-compiled user .o unless the
        # user source itself changes. For the development loop this is
        # a manageable limitation — `cmake --build build --clean-first`
        # or a `touch <src>` gets a fresh compile; production builds
        # always start from a clean tree and pay the full cost anyway.
    endforeach()
endfunction()

# ── Dump-mode implementation (legacy) ─────────────────────────────────────
# Behavior predates PM1-5 and is preserved verbatim for the idempotency-
# check CTests that need an intermediate file on disk to re-transpile.
# Every source file is routed through sturm-transpile. A per-source
# add_custom_command writes the rewritten output to
#   ${CMAKE_BINARY_DIR}/sturm_gen/<relpath-of-source>
# and declares the generated file as the actual compile unit. The
# custom-command's DEPENDS list contains the original source AND the
# sturm-transpile binary, so:
#   - editing the source re-triggers regeneration (normal incremental
#     rebuild behavior);
#   - rebuilding the transpiler (e.g. after touching transpiler/src/*.cpp)
#     re-triggers regeneration of every generated file, which is the
#     right invalidation discipline — a transpiler change CAN alter the
#     output for an unchanged input.
# The GENERATED source-file property is set explicitly so the compile
# step does not complain about a file that does not yet exist at
# configure time.
function(_sturm_add_quantum_executable_dump target)
    set(sources ${ARGN})

    set(compile_units "")
    set(_deps "")

    foreach(src ${sources})
        # Normalize to an absolute path for the custom-command DEPENDS and
        # for computing the relative path under sturm_gen/.
        if(IS_ABSOLUTE "${src}")
            set(abs_src "${src}")
        else()
            set(abs_src "${CMAKE_CURRENT_SOURCE_DIR}/${src}")
        endif()
        # cmake_path(NORMAL_PATH) would be nicer but is 3.20+; we rely on
        # CMake 3.16 here, so use get_filename_component(REALPATH ...) to
        # collapse any "../" segments the caller passed in.
        get_filename_component(abs_src "${abs_src}" ABSOLUTE)

        # sturm::transpiler must be a known target before we wire a
        # custom-command DEPENDS on it. Both the in-tree build (ALIAS in
        # transpiler/CMakeLists.txt) and find_package(sturm) consumers
        # (IMPORTED in sturmConfig.cmake.in) register the namespaced
        # spelling, so checking for it here covers both layouts uniformly
        # (sturm-vr0v.1 / PRD §3.5).
        if(NOT TARGET sturm::transpiler)
            message(FATAL_ERROR
                "add_quantum_executable(${target}): the `sturm::transpiler` "
                "target is not defined. Ensure the STURM transpiler "
                "subdirectory is added (add_subdirectory(transpiler) or "
                "find_package(sturm)) before calling add_quantum_executable.")
        endif()

        # Compute the relpath under CMAKE_SOURCE_DIR so the generated tree
        # mirrors the source tree. Sources that live outside CMAKE_SOURCE_DIR
        # (e.g. in the build tree) still need a deterministic layout — fall
        # back to just the filename in that case, keeping the helper usable
        # from script-generated sources.
        file(RELATIVE_PATH rel_src "${CMAKE_SOURCE_DIR}" "${abs_src}")
        set(_src_outside_source_dir FALSE)
        if(rel_src MATCHES "^\\.\\.")
            get_filename_component(rel_src "${abs_src}" NAME)
            set(_src_outside_source_dir TRUE)
        endif()

        set(gen_src "${CMAKE_BINARY_DIR}/sturm_gen/${rel_src}")
        get_filename_component(gen_dir "${gen_src}" DIRECTORY)

        # The sturm-transpile driver computes the output file layout via
        # resolve_output_path(input, output_dir):
        #   - absolute input  → <output_dir>/<basename(input)>
        #   - relative input  → <output_dir>/<input> (mirrors tree)
        # To make the generated file land at the mirrored location, we
        # invoke the transpiler with a RELATIVE input path and set
        # WORKING_DIRECTORY to CMAKE_SOURCE_DIR for in-tree sources.
        if(_src_outside_source_dir)
            set(_input_for_tool "${abs_src}")
            set(_working_dir "${CMAKE_CURRENT_BINARY_DIR}")
        else()
            set(_input_for_tool "${rel_src}")
            set(_working_dir "${CMAKE_SOURCE_DIR}")
        endif()

        # Propagate the compile context the source actually needs to parse
        # cleanly. sturm-transpile runs Clang via libTooling without a
        # compilation database, so forward the include paths and feature
        # defines explicitly.
        set(_xa_args
            "--extra-arg=-std=c++20"
            "--extra-arg=-I${CMAKE_SOURCE_DIR}/include"
            "--extra-arg=-DSTURM_BACKEND_ENABLED=1"
            "--extra-arg=-DSTURM_ANCILLA_CAPACITY=${STURM_ANCILLA_CAPACITY}")

        # `add_custom_command(DEPENDS ...)` rejects ALIAS targets but
        # accepts the underlying real target name; for IMPORTED targets
        # there is no buildable dependency to express. Resolve once and
        # gate the DEPENDS on the file/target accordingly.
        get_target_property(_sturm_xpile_aliased sturm::transpiler
            ALIASED_TARGET)
        if(_sturm_xpile_aliased)
            set(_sturm_xpile_dep "${_sturm_xpile_aliased}")
        else()
            set(_sturm_xpile_dep "")  # IMPORTED — file ships pre-built.
        endif()

        add_custom_command(
            OUTPUT "${gen_src}"
            COMMAND "${CMAKE_COMMAND}" -E make_directory "${gen_dir}"
            COMMAND $<TARGET_FILE:sturm::transpiler>
                    "${_input_for_tool}"
                    --output-dir "${CMAKE_BINARY_DIR}/sturm_gen"
                    ${_xa_args}
            WORKING_DIRECTORY "${_working_dir}"
            DEPENDS "${abs_src}" ${_sturm_xpile_dep}
            COMMENT "sturm-transpile ${rel_src}"
            VERBATIM)

        # Mark the generated file so CMake does not complain that a source
        # listed in add_executable does not exist on disk at configure time.
        set_source_files_properties("${gen_src}" PROPERTIES GENERATED TRUE)

        list(APPEND compile_units "${gen_src}")
        list(APPEND _deps "${gen_src}")
    endforeach()

    add_executable(${target} ${compile_units})

    # A convenience aggregate custom-target wrapping all generated outputs
    # lets downstream CMake logic (e.g. `make sturm_gen`) force regeneration
    # without having to build the final executable.
    if(_deps)
        add_custom_target(${target}_xpile DEPENDS ${_deps})
        if(NOT TARGET sturm_gen)
            add_custom_target(sturm_gen)
        endif()
        add_dependencies(sturm_gen ${target}_xpile)
    endif()
endfunction()
