// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: compound_nested_mul_and.cpp
// LO-0.3 (sturm-z8pl): nested lossy-op desugar fixture (TARGET shape).
//
// Post-LO-2e desugar of `a *= (b & c);` recurses depth-first: the
// inner `b & c` matches first, so its OOP rewrite —
// `qint __sturm_tmp_and_0; and_oop(b, c, __sturm_tmp_and_0);` —
// emits before the outer `*=` rewrite. The outer `*=` then reads
// the inner tmp as its RHS, producing the §2.1 forward pair
// (`qint __sturm_tmp_mul_1; mul_oop(a, __sturm_tmp_and_0,
// __sturm_tmp_mul_1); swap(a, __sturm_tmp_mul_1);`). At the
// enclosing block's closing brace the uncompute_pass LIFO queue
// runs the cleanups in reverse order: outer first
// (`swap(a, __sturm_tmp_mul_1);
// sturm::invert<&::sturm::lib_mul_dsl>()(a, __sturm_tmp_and_0,
// __sturm_tmp_mul_1);`), inner last
// (`sturm::invert<&::sturm::lib_c_AND_dsl>()(b, c,
// __sturm_tmp_and_0);` — note: no reverse swap for the inner
// because bare `&` did not swap forward; only compound assigns
// swap per §2.3).
//
// Until LO-2a/2b/2c/2e land (sturm-9254 / sturm-yxxa /
// sturm-hbwr / sturm-rry6), the snapshot test built against this
// expected file is in a known-RED state and is therefore not
// registered in tests/transpiler/CMakeLists.txt. LO-2e wires it.
namespace sturm {
template <int W>
class qint_t {
public:
    qint_t() {}
    qint_t(const qint_t&) {}
    qint_t& operator*=(const qint_t&) { return *this; }
};
template <int W>
inline qint_t<W> operator&(const qint_t<W>&, const qint_t<W>&) {
    return qint_t<W>{};
}
} // namespace sturm
using qint = sturm::qint_t<2>;

void demo(qint a, qint b, qint c) {
    #line 38 "compound_nested_mul_and.cpp"
qint __sturm_tmp_and_0;
    #line 38 "compound_nested_mul_and.cpp"
and_oop(b, c, __sturm_tmp_and_0);
    #line 38 "compound_nested_mul_and.cpp"
qint __sturm_tmp_mul_1;
    #line 38 "compound_nested_mul_and.cpp"
mul_oop(a, __sturm_tmp_and_0, __sturm_tmp_mul_1);
    #line 38 "compound_nested_mul_and.cpp"
swap(a, __sturm_tmp_mul_1);

#line 38 "compound_nested_mul_and.cpp"
    swap(a, __sturm_tmp_mul_1);

#line 38 "compound_nested_mul_and.cpp"
    sturm::invert<&::sturm::lib_mul_dsl>()(a, __sturm_tmp_and_0, __sturm_tmp_mul_1);

#line 38 "compound_nested_mul_and.cpp"
    sturm::invert<&::sturm::lib_c_AND_dsl>()(b, c, __sturm_tmp_and_0);

#line 39 "compound_nested_mul_and.cpp"
}
