// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: compound_and_or.cpp
// Phase E / PE-4 input for the sturm-transpile snapshot test.
//
// Depth-2 mirror of the roadmap shape: `qbool r = (b & c) | d;` swaps OR
// for AND in the outer slot and vice-versa. The decomposition order is
// preserved (LHS-first post-order), so `__stu_t0` is the nested AND and
// the outer OR uses it as its LHS operand:
//
//     qbool __stu_t0 = b & c;
//     qbool r = __stu_t0 | d;
//
// and the LIFO uncompute close-brace insertions are
//
//     uncompute_or(r, __stu_t0, d);
//     uncompute_and(__stu_t0, b, c);
//
// The stub is identical to compound_or_and.cpp's — hermetic, no include
// paths required for the sturm-transpile binary to resolve the overloads.
//
// Why the `(void)r;` reader is load-bearing
// -----------------------------------------
// Phase J PJ-4a (dead-ancilla elimination) removes any `qbool` VarDecl
// whose value is never read.  Without a reader, PJ-4a fires before the
// Phase E compound flatten matcher: the entire `qbool r = (b & c) | d;`
// line (and its downstream `__stu_t0` intermediate) would be dropped,
// the function body would collapse, and this snapshot would byte-
// mismatch against the pre-PJ-4a golden.  The explicit `(void)r;` bumps
// the reader count to 1, shutting off PJ-4a so the compound matcher
// runs as intended.  Same rationale — and same textual shape — as
// or_single_runtime.cpp / hoist_or_out_of_for.cpp.
namespace sturm {
class qbool {
public:
    qbool() {}
    qbool(const qbool&) {}
};
inline qbool operator|(const qbool&, const qbool&) { return qbool{}; }
inline qbool operator&(const qbool&, const qbool&) { return qbool{}; }
} // namespace sturm
using sturm::qbool;

void demo(qbool b, qbool c, qbool d) { 
#line 41 "compound_and_or.cpp"
qbool __stu_t0 = b & c;
    #line 41 "compound_and_or.cpp"
qbool r = __stu_t0 | d; (void)r; 
#line 41 "compound_and_or.cpp"
    uncompute_or(r, __stu_t0, d);

#line 41 "compound_and_or.cpp"
    uncompute_and(__stu_t0, b, c);

#line 41 "compound_and_or.cpp"
}
