// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: compound_or_and.cpp
// Phase E / PE-4 input for the sturm-transpile snapshot test.
//
// Exercises the roadmap compound-expression shape
// `qbool r = (b | c) & d;` — a depth-2 mix of OR and AND where the LHS of
// the outer `&` is itself a parenthesized `|` sub-expression. The Phase E
// compound matcher must decompose this into a flat sequence
//
//     qbool __stu_t0 = b | c;
//     qbool r = __stu_t0 & d;
//
// then the LIFO uncompute pass at scope close emits
//
//     uncompute_and(r, __stu_t0, d);
//     uncompute_or(__stu_t0, b, c);
//
// in that order (outermost uncomputed first). Leaves `b`, `c`, `d` are
// bare DeclRefExprs to named qbool parameters.
//
// The stub inlined below mirrors the hermetic shape used by `or_single.cpp`
// so the sturm-transpile binary can resolve qbool's `operator|` and
// `operator&` without any `#include` or include-path arguments.
namespace sturm {
class qbool {
public:
    qbool() {}
    qbool(const qbool&) {}
};
inline qbool operator|(const qbool&, const qbool&) { return qbool{}; }
inline qbool operator&(const qbool&, const qbool&) { return qbool{}; }
} // namespace sturm
using sturm::qbool;

void demo(qbool b, qbool c, qbool d) { qbool __stu_t0 = b | c;
    qbool r = __stu_t0 & d;     uncompute_and(r, __stu_t0, d);
    uncompute_or(__stu_t0, b, c);
}
