// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: dead_ancilla_inside_when.cpp
// Phase J / PJ-4c input for the sturm-transpile snapshot test.
//
// Exercises PJ-4a dead-ancilla elimination scoped to a `WHEN` body.
// A `qbool t = a | b;` decl lives inside a `WHEN(ctrl) { ... }` body
// and has NO reader. The PJ-4a reader-count probe anchors on the
// enclosing `CompoundStmt` returned by `detail::enclosing_scope`,
// which for this shape is the WHEN body's `{ ... }` — NOT the outer
// function body. With `count_readers_in_scope(t, body) == 0`, the
// matcher fires: the decl's range is empty-replaced and pushed into
// `QUnit::eliminated_stmt_ranges`, suppressing any downstream MVP OR
// match on the same decl via `apply_eliminated_stmt_guards`.
//
// Expected transform (see .expected.cpp for the byte-exact golden):
//
//     WHEN(ctrl) {
//         qbool t = a | b;    // eliminated — zero readers inside body
//     }                       // no uncompute_or planted at body close
//
// The WHEN macro itself is not rewritten — the PF-3 WHEN-lift matcher
// only fires on compound arguments, and `WHEN(ctrl)` is already a
// bare DeclRefExpr (short-circuit pass-through). The fixture therefore
// pins PJ-4a's per-scope elimination in isolation: the WHEN body is
// treated as an ordinary CompoundStmt by the reader-count helper, so
// scope-walk correctness translates directly to correct elimination
// under control-flow constructs.
//
// The stub inlined below replicates the Phase F fixtures' hermetic
// shape:
//   - `sturm::qbool` with `operator|` so `a | b` type-checks.
//   - `sturm::detail::materialize_when` / `WhenCapture` /
//     `make_when_guard` stubs so the WHEN macro's three `if` init-stmts
//     type-check without dragging in the runtime's real `WhenGuard`.
//   - The exact three-`if` WHEN macro from
//     `include/sturm/control/when.hpp`.
namespace sturm {

class qbool {
public:
    qbool() {}
    qbool(const qbool&) {}
    qbool& operator=(const qbool&) { return *this; }
    bool should_run() const { return true; }
};

inline qbool operator|(const qbool&, const qbool&) { return qbool{}; }

namespace detail {

inline qbool& materialize_when(qbool& q) { return q; }
inline qbool  materialize_when(qbool&& q) { return static_cast<qbool&&>(q); }

struct WhenCapture { WhenCapture() = default; };
inline qbool& make_when_guard(qbool& q) { return q; }

} // namespace detail
} // namespace sturm

using sturm::qbool;

#define WHEN(expr) \
    if (::sturm::detail::WhenCapture _when_capture_{}; true) \
    if (decltype(auto) _when_val_ = ::sturm::detail::materialize_when(expr); true) \
    if (auto& _when_guard_ = ::sturm::detail::make_when_guard(_when_val_); \
        _when_guard_.should_run())

void demo(qbool a, qbool b, qbool ctrl) {
    WHEN(ctrl) {
        
    }
}
