// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: dead_ancilla_keep_read.cpp
// Phase J / PJ-4c reject input for the sturm-transpile snapshot test.
//
// Exercises the reader-count != 0 branch of the PJ-4a dead-ancilla
// matcher. The `qbool t = a | b;` VarDecl has one reader in its
// enclosing scope (the `x ^= t;` compound-assign RHS), so the
// `detail::count_readers_in_scope(t, ...) == 0` guard fails and PJ-4a
// bails. With elimination rejected, the decl passes through to the
// downstream phases: the MVP OR matcher picks up `qbool t = a | b;`
// and schedules an `uncompute_or(t, a, b);` at scope close, and the
// Phase A PA-3 `^=` matcher picks up `x ^= t;` and emits its
// self-adjoint `x ^= t;` inverse in the same LIFO uncompute block.
//
// Expected transform (see .expected.cpp for the byte-exact golden):
//
//     qbool t = a | b;        // unchanged — reader preserves the decl
//     x ^= t;                 // PA-3 forward
//     x ^= t;                 // PA-3 LIFO self-adjoint inverse
//     uncompute_or(t, a, b);  // MVP OR uncompute at scope close
//
// This fixture pins the "no write-through on reject" invariant for
// `QUnit::eliminated_stmt_ranges`: PJ-4a leaves the list untouched on
// rejection, and every downstream matcher fires as if PJ-4a had not
// run — the runtime path stays intact.
//
// The stub is hermetic; only `operator|`, the copy ctor, and
// `operator^=(const qbool&)` need to resolve for the matchers' AST
// anchors to fire.
namespace sturm {
class qbool {
public:
    qbool() {}
    qbool(const qbool&) {}
    qbool& operator=(const qbool&) { return *this; }
    qbool& operator^=(const qbool&) { return *this; }
};
inline qbool operator|(const qbool&, const qbool&) { return qbool{}; }
} // namespace sturm
using sturm::qbool;

void demo(qbool a, qbool b, qbool x) {
    qbool t = a | b;
    x ^= t;
    x ^= t;
    uncompute_or(t, a, b);
}
