// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: fuse_xor_and_reject_nested_rhs.cpp
// Phase J / PJ-1g reject input for the sturm-transpile snapshot test.
//
// Exercises the nested-init branch of the PJ-1d ccnot-fuse peephole
// matcher. The VarDecl's init is `a & (b & c)` — the outer `&`'s RHS
// (after implicit-cast peel) is itself a CXXOperatorCallExpr on `&`,
// NOT a bare DeclRefExpr. PJ-1d's pattern matcher requires BOTH `&`
// arguments to peel to bare DREs, so it rejects before the callback
// body runs and `unit_.replacements` / `unit_.fused_stmt_ranges` stay
// empty for this VarDecl.
//
// With fuse rejected, the Phase E PE-4 compound-flatten matcher
// handles the nested init per the canonical depth-2 shape: emit a
// fresh `__stu_t0` for the inner `b & c`, rewrite the outer init to
// `__stu_t0 & c` form, and schedule LIFO `uncompute_and` calls at the
// scope close. The Phase A PA-3 `^=` matcher then fires on the
// adjacent `x ^= __t;` stmt (unchanged RHS — still a DRE to `__t`)
// and schedules its self-adjoint inverse.
//
// Expected emission order (see .expected.cpp for byte-exact golden):
//
//     qbool __stu_t0 = b & c;
//     qbool __t = a & __stu_t0;
//     x ^= __t;                        // PA-3 forward
//     x ^= __t;                        // PA-3 LIFO inverse
//     uncompute_and(__t, a, __stu_t0); // PE-4 LIFO for `__t`
//     uncompute_and(__stu_t0, b, c);   // PE-4 LIFO for `__stu_t0`
//
// The stub matches the happy-path fixture (fuse_xor_and.cpp) — the
// `&` / `^=` operator overloads are all that need to resolve.
namespace sturm {
class qbool {
public:
    qbool() {}
    qbool(const qbool&) {}
    qbool& operator=(const qbool&) { return *this; }
    qbool& operator^=(const qbool&) { return *this; }
};
inline qbool operator&(const qbool&, const qbool&) { return qbool{}; }
} // namespace sturm
using sturm::qbool;

void demo(qbool a, qbool b, qbool c, qbool x) {
    
#line 43 "fuse_xor_and_reject_nested_rhs.cpp"
qbool __stu_t0 = b & c;
    #line 43 "fuse_xor_and_reject_nested_rhs.cpp"
qbool __t = a & __stu_t0;
    x ^= __t;

#line 44 "fuse_xor_and_reject_nested_rhs.cpp"
    x ^= __t;

#line 43 "fuse_xor_and_reject_nested_rhs.cpp"
    uncompute_and(__t, a, __stu_t0);

#line 43 "fuse_xor_and_reject_nested_rhs.cpp"
    uncompute_and(__stu_t0, b, c);

#line 45 "fuse_xor_and_reject_nested_rhs.cpp"
}
