// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: fuse_xor_and_reject_classical_rhs.cpp
// Phase J / PJ-1g reject input for the sturm-transpile snapshot test.
//
// Exercises the "next sibling is `x ^= <literal>`, not `x ^= __t`"
// branch of the PJ-1d ccnot-fuse peephole matcher. The `^=` overload
// selected here is the classical-RHS form (`operator^=(int)`), so the
// adjacent next-sibling stmt's RHS (after peel) is an IntegerLiteral,
// NOT a DeclRefExpr. The matcher's `match_xor_assign_consumer` helper
// bails on the `peel_to_dre(rhs)` step — an IntegerLiteral peels to
// `nullptr` — and the pair is not fused.
//
// With fuse rejected, the Phase A PA-4 classical `^=` matcher picks
// up `x ^= 1;` and schedules a self-adjoint `x ^= 1;` at scope close.
// The `qbool __t = a & b;` VarDecl is unmatched (bare-DRE `&`-init is
// fuse territory only; compound flatten wants at least one nested
// op-call argument), so it passes through unchanged.
//
// Expected emission (see .expected.cpp for the byte-exact golden):
//
//     qbool __t = a & b;   // unchanged
//     x ^= 1;              // PA-4 forward
//     x ^= 1;              // PA-4 LIFO inverse at scope close
//
// The stub drops `operator^=(const qbool&)` and uses `operator^=(int)`
// only — that overload is the one the matcher's classical-RHS gate
// inspects.
//
// Why the `(void)__t;` reader is load-bearing
// -------------------------------------------
// Phase J PJ-4a (dead-ancilla elimination) removes any `qbool` VarDecl
// whose value is never read.  Without a reader, PJ-4a fires before
// every downstream matcher (PJ-1d ccnot-fuse, PA-4 classical `^=`,
// etc.), deleting the `qbool __t = a & b;` line entirely and the
// fixture stops exercising PJ-1g's reject branch.  The explicit
// `(void)__t;` bumps the reader count to 1, shutting off PJ-4a so the
// fuse matcher runs, inspects the next-sibling `x ^= 1;` shape, and
// rejects the fuse as intended — the PA-4 classical `^=` matcher then
// picks up `x ^= 1;` unchanged.  Same rationale — and same textual
// shape — as or_single_runtime.cpp / hoist_or_out_of_for.cpp.
namespace sturm {
class qbool {
public:
    qbool() {}
    qbool(const qbool&) {}
    qbool& operator=(const qbool&) { return *this; }
    qbool& operator^=(int) { return *this; }
};
inline qbool operator&(const qbool&, const qbool&) { return qbool{}; }
} // namespace sturm
using sturm::qbool;

void demo(qbool a, qbool b, qbool x) {
    qbool __t = a & b;
    (void)__t;
    x ^= 1;

#line 54 "fuse_xor_and_reject_classical_rhs.cpp"
    x ^= 1;

#line 55 "fuse_xor_and_reject_classical_rhs.cpp"
}
