// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: hoist_or_out_of_for.cpp
// Phase J / PJ-3f input for the sturm-transpile snapshot test.
//
// Canonical uncompute-hoisting shape: `qbool t = a | b;` declared inside
// a `for (...)` body where BOTH operands are outer-scoped parameters and
// neither is written inside the body. The PJ-3d matcher
// (`register_hoist_invariant_matcher`) fires on the loop-body scope,
// verifies `classify_scope_kind == LoopBody`, confirms every operand is
// loop-invariant (decl lives outside the body AND no write is reachable
// inside), and sets `op.hoist_to_override` to the function-body close
// brace + `op.insert_before_override` to the `for` begin loc.
//
// Expected transform (see .expected.cpp for the byte-exact golden):
//
//     for (int i = 0; i < 3; ++i) {
//         qbool t = a | b;           // forward stays in loop body (PJ-3d
//         (void)t;                    //  only moves the uncompute anchor;
//     }                               //  forward text-move is PJ-3g+)
//     uncompute_or(t, a, b);          // uncompute hoisted OUT of the loop
//
// Net effect: the uncompute call lands AFTER the loop's closing brace,
// NOT immediately before it. This is the load-bearing PJ-3d semantic —
// `hoist_to_override` takes precedence over `scope.close_brace` in
// `uncompute_pass.cpp`'s anchor-selection ladder.
//
// The `(void)t;` reader is required: without it, the PJ-4a dead-ancilla
// eliminator would remove the decl entirely before the PJ-3d hoist
// matcher runs (hoist runs LAST), and there would be nothing to hoist.
//
// The stub inlined below is hermetic — the sturm-transpile binary runs
// with a FixedCompilationDatabase that carries no include paths, so
// every symbol the matcher probes must resolve against the fixture's
// own source. Only `operator|` need resolve for the MVP OR matcher to
// fire on the VarDecl initializer.
namespace sturm {
class qbool {
public:
    qbool() {}
    qbool(const qbool&) {}
    qbool& operator=(const qbool&) { return *this; }
};
inline qbool operator|(const qbool&, const qbool&) { return qbool{}; }
} // namespace sturm
using sturm::qbool;

void demo(qbool a, qbool b) {
    for (int i = 0; i < 3; ++i) {
        qbool t = a | b;
        (void)t;
    }

#line 47 "hoist_or_out_of_for.cpp"
    uncompute_or(t, a, b);
}
