// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: hoist_reject_branch_not_loop.cpp
// Phase J / PJ-3f reject input for the sturm-transpile snapshot test.
//
// Negative fixture: the enclosing scope is an `if (cond) { ... }`
// branch body, NOT a for/while loop. `detail::classify_scope_kind`
// returns `ScopeKind::BranchBody` (not `LoopBody`) for this anchor, so
// the PJ-3d hoist matcher short-circuits before even inspecting the
// op's operands. The uncompute stays INSIDE the branch body at
// `scope.close_brace` — identical to Phase H `if_then_intermediate_or.cpp`'s
// behaviour (branch-local per-execution uncomputation).
//
// Expected transform (see .expected.cpp for the byte-exact golden):
//
//     if (cond) {
//         qbool t = a | b;
//         (void)t;
//         uncompute_or(t, a, b);       // stays IN the if-body
//     }
//
// Rationale for this fixture: `LoopBody` is the ONLY scope kind that
// can benefit from uncompute hoisting. Branch bodies execute at most
// once per containing-scope visit, so hoisting a decl-producing op
// out of a branch would both:
//   (a) be a semantic no-op (one iteration = one uncompute, same total
//       cost), and
//   (b) expose the decl's name to the enclosing scope if the branch
//       was taken (and leave it undefined if the branch was skipped —
//       a use-before-init hazard).
// The PJ-3d `classify_scope_kind == LoopBody` gate on line 367-370
// of `matcher_hoist_invariant.cpp` is the correctness guard this
// fixture pins.
//
// The `(void)t;` reader keeps the decl alive past PJ-4a dead-ancilla
// elimination; without it the whole VarDecl would vanish, suppressing
// the OR op before the hoist matcher ever sees it.
//
// The stub is hermetic; only `operator|` need resolve for the MVP OR
// matcher to fire.
namespace sturm {
class qbool {
public:
    qbool() {}
    qbool(const qbool&) {}
    qbool& operator=(const qbool&) { return *this; }
};
inline qbool operator|(const qbool&, const qbool&) { return qbool{}; }
} // namespace sturm
using sturm::qbool;

void demo(qbool a, qbool b, bool cond) {
    if (cond) {
        qbool t = a | b;
        (void)t;
        uncompute_or(t, a, b);
}
}
