// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: hoist_reject_operand_written_in_loop.cpp
// Phase J / PJ-3f reject input for the sturm-transpile snapshot test.
//
// Negative fixture: one operand (`a`) is WRITTEN inside the loop body
// (`a = b;`), so `expr_is_loop_invariant` returns false for that
// operand and the PJ-3d hoist matcher rejects the whole op. The
// uncompute stays INSIDE the loop body at `scope.close_brace` — the
// default Phase H behaviour from PH-4 / `for_intermediate_or.cpp`
// (per-iteration uncomputation).
//
// Expected transform (see .expected.cpp for the byte-exact golden):
//
//     for (int i = 0; i < 3; ++i) {
//         a = b;                        // outer-var write — disqualifies
//         qbool t = a | b;              //                   `a` from
//         (void)t;                      //                   invariance
//         uncompute_or(t, a, b);        // uncompute stays IN the loop
//     }
//
// Net effect: `op.hoist_to_override` stays invalid on the OR op, and
// `uncompute_pass.cpp`'s anchor-selection ladder falls through to
// `scope.close_brace` — i.e. the `}` of the `for`-body CompoundStmt.
//
// The `a = b;` assignment is a classical-DSL write to a qbool — the
// MVP's `operator=` overload (`return *this;`) is a no-op at runtime
// but structurally it IS a DRE-write to `a`, which is what
// `loop_invariant_detail::WriteFinder` detects (via
// BinaryOperator::isAssignmentOp + DeclRefExpr pattern).
//
// The `(void)t;` reader keeps the decl alive past PJ-4a dead-ancilla
// elimination so the OR op reaches the hoist matcher at all.
//
// The stub is hermetic; `operator|` and `operator=` must resolve for
// the MVP OR matcher and the write-finder respectively.
namespace sturm {
class qbool {
public:
    qbool() {}
    qbool(const qbool&) {}
    qbool& operator=(const qbool&) { return *this; }
};
inline qbool operator|(const qbool&, const qbool&) { return qbool{}; }
} // namespace sturm
using sturm::qbool;

void demo(qbool a, qbool b) {
    for (int i = 0; i < 3; ++i) {
        a = b;
        qbool t = a | b;
        (void)t;
        uncompute_or(t, a, b);
}
}
