// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: hoist_multi_op_same_loop.cpp
// Phase J / PJ-3f input for the sturm-transpile snapshot test.
//
// Multi-op LIFO ordering: two independent decl-producing ops in the
// SAME loop body, both loop-invariant. The PJ-3d matcher sets
// `hoist_to_override` on BOTH ops, and the M8 synthesis pass
// (uncompute_pass.cpp) iterates the scope's ops in REVERSE source
// order to emit their uncomputes — producing a LIFO schedule at the
// post-loop anchor.
//
// Expected transform (see .expected.cpp for the byte-exact golden):
//
//     for (int i = 0; i < 3; ++i) {
//         qbool r1 = a | b;           // forward 1 (source order)
//         qbool r2 = c | d;           // forward 2 (source order)
//         (void)r1;
//         (void)r2;
//     }
//     uncompute_or(r2, c, d);         // uncompute r2 FIRST (LIFO)
//     uncompute_or(r1, a, b);         // uncompute r1 SECOND (LIFO)
//
// Rationale: `synthesize()` in `uncompute_pass.cpp` calls
// `std::stable_sort` on the ops by `stmt_range.getBegin()`, then
// iterates with a reverse_iterator. Two ops with distinct begin
// locs sort into source order, and the reverse walk emits them
// in reverse source order — the canonical LIFO schedule P9's
// manual-adjoint convention pins.
//
// Forward compute text move is a FUTURE phase concern (PJ-3g+).
// Today PJ-3d only moves the UNCOMPUTE anchor; both forwards stay
// inside the loop body in source order — which happens to match
// the roadmap's "forwards in source order pre-loop" ideal once the
// forward text-move lands (the relative order among the forwards
// is already correct; only their anchoring shifts from inside-loop
// to pre-loop).
//
// The `(void)r1; (void)r2;` readers keep both decls alive past
// PJ-4a dead-ancilla elimination.
//
// The stub is hermetic; only `operator|` need resolve for the MVP OR
// matcher to fire on both VarDecl initializers.
namespace sturm {
class qbool {
public:
    qbool() {}
    qbool(const qbool&) {}
    qbool& operator=(const qbool&) { return *this; }
};
inline qbool operator|(const qbool&, const qbool&) { return qbool{}; }
} // namespace sturm
using sturm::qbool;

void demo(qbool a, qbool b, qbool c, qbool d) {
    for (int i = 0; i < 3; ++i) {
        qbool r1 = a | b;
        qbool r2 = c | d;
        (void)r1;
        (void)r2;
    }

#line 55 "hoist_multi_op_same_loop.cpp"
    uncompute_or(r2, c, d);

#line 54 "hoist_multi_op_same_loop.cpp"
    uncompute_or(r1, a, b);
}
