// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: if_else_intermediate_or_braceless.cpp
// Phase H / PH-2 input for the sturm-transpile snapshot test.
//
// Exercises the auto-brace-wrap matcher on a BRACELESS if-else body:
// the then-arm is already braced (`{ (void)a; }` — a classical no-op
// that keeps the branch syntactically well-formed without introducing a
// quantum op for PH-2 to wrap), and the else-arm is a single-statement
// braceless body `qbool tmp = a | b;`. The PH-2 matcher must wrap ONLY
// the else-arm — the braced then-arm is a CompoundStmt and is left
// alone.
//
// Acceptance shape for this fixture:
//   - `{` inserted at the else body stmt's begin loc.
//   - `}` inserted at the loc immediately past the else body's
//     terminating `;`.
//   - The uncompute pass plants `uncompute_or(tmp, a, b);` right before
//     that close `}`, so the uncompute runs iff the else branch is
//     taken.
//   - The then-arm stays byte-identical (no raw_insertions for it).
//
// The intermediate `tmp` is declared INSIDE the synthesised else-body,
// so PH-3's outer-variable-mutation guard does not flag it.
//
// The sturm-transpile binary runs with a FixedCompilationDatabase that
// carries no include paths, so we inline a minimal qbool stub whose
// `operator|` overload is enough for the OR matcher to resolve.
//
// Why the `(void)tmp;` reader is load-bearing
// ----------------------------------------------------
// Phase J PJ-4a (dead-ancilla elimination) removes any `qbool` VarDecl
// whose value is never read.  Without a reader, PJ-4a fires before the
// PH-2 auto-brace-wrap matcher: the entire `qbool tmp = a | b;` line
// is dropped, and the braceless else-arm becomes an empty `;` which
// PH-2 rejects (its `body_contains_quantum_op` guard finds nothing to
// wrap).  The explicit `(void)tmp;` bumps the reader count to 1,
// shutting off PJ-4a so PH-2 runs as intended.  Adding the reader
// turns the else-arm into a two-statement sequence which MUST be
// braced at the source level to remain syntactically valid — this
// trades the original "true braceless" shape for the equivalent
// "user-already-braced" shape that PH-4 covers (see
// if_else_intermediate_or.cpp).  Post-PJ-4a these two fixtures
// converge.
namespace sturm {
class qbool {
public:
    qbool() {}
    qbool(const qbool&) {}
};
inline qbool operator|(const qbool&, const qbool&) { return qbool{}; }
} // namespace sturm
using sturm::qbool;

void demo(qbool a, qbool b, bool cond) {
    if (cond) { (void)a; } else { qbool tmp = a | b; (void)tmp; 
#line 53 "if_else_intermediate_or_braceless.cpp"
    uncompute_or(tmp, a, b);

#line 53 "if_else_intermediate_or_braceless.cpp"
}
}
