// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: main_lifecycle_basic.cpp
// Frontend simpl. P7 (sturm-e3ru): basic main_lifecycle fixture (input).
//
// Exercises the matcher_main_lifecycle (Phase 7 of
// docs/impl_plan_frontend_simplification.md) for the simplest shape:
// `int main()` body with one user statement. The matcher must:
//
//   1. Detect the unique `int main()` FunctionDecl
//      (forms allowed: `int main()`, `int main(int, char**)`,
//      `int main(int, char**, char**)`). The GCC trailing-return form
//      `auto main() -> int` is OUT OF SCOPE per PRD §5.4 / sturm-e3ru.
//   2. Confirm STURM_NO_AUTO_LIFECYCLE is NOT defined (escape hatch).
//   3. Confirm STURM_UMBRELLA_INCLUDED is defined (sentinel set by
//      the umbrella in include/sturm.h).
//   4. Source-rewrite the body into the IIFE form (PRD §5.4 listing).
//
// The fixture defines STURM_UMBRELLA_INCLUDED inline because the
// transpiler's FixedCompilationDatabase does not carry include paths
// — we cannot `#include "sturm.h"` here and have the matcher see the
// sentinel through the preprocessor. Defining the macro inline is
// equivalent: the matcher only checks `Preprocessor::isMacroDefined`,
// not the source location of the definition.
#define STURM_UMBRELLA_INCLUDED 1

int main() {
    sturm_backend_context_t* __sturm_ctx = sturm_backend_create(STURM_MODE_DEFAULT);
    sturm_set_thread_context(__sturm_ctx);
    int __sturm_rc = ([&]() -> int {
    int x = 42;
    (void)x;
    return 0;
})();
    sturm_set_thread_context(nullptr);
    sturm_backend_destroy(__sturm_ctx);
    return __sturm_rc;
}
