// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: modular_compound_collapse.cpp
// sturm-qzab.3 (P5 beat 5.3) input — `r = a + b; r %= n;` compound
// peephole-collapsed AddMod rewrite.
//
// Plan §7.2 #2 / §7.4 beat 5.3: when the user writes the addition and
// the modular reduction as TWO adjacent statements (the "peephole-
// collapsed" form left in place by `matcher_peephole_reorder` after it
// has had a chance to reshuffle the surrounding gates), the modular-op
// matcher (matcher_modular_op.cpp) must still recognise the pair and
// collapse it into a single `::sturm::add_mod(a, b, n)` call against a
// fresh `qint_t<W>` declaration — semantically identical to the
// in-initializer form pinned by the sturm-qzab.1 (beat 5.1)
// `modular_add_op` fixture.
//
// AST shape recognised here:
//
//   DeclStmt
//     VarDecl r init = CXXOperatorCallExpr('+')
//                        a (DeclRefExpr, qint_t<W>)
//                        b (DeclRefExpr, qint_t<W>)
//   ExprStmt
//     CXXOperatorCallExpr('%=')
//       r (DeclRefExpr to the VarDecl above)
//       n (DeclRefExpr, qint_t<W>)
//
// The two statements MUST be immediate siblings in one CompoundStmt;
// any intervening statement that reads `r` falls back to the wide
// path (the stand-alone LO-2a `%=` desugar plus the user's own
// `qint r = a + b;` decl land verbatim — semantically correct, just
// not collapsed). See `modular_compound_collapse_intervening.cpp`-
// style negative coverage in `transpiler/tests/test_matcher_modular_op.cpp`.
//
// The hermetic `qint_t<W>` stub below mirrors the sturm-qzab.1
// `modular_add_op.cpp` fixture so the matcher resolves the
// `CXXOperatorCallExpr` shape without an `#include <sturm/sturm.hpp>`
// (the transpiler's FixedCompilationDatabase carries no include paths).
namespace sturm {
template <int W>
class qint_t {
public:
    qint_t() {}
    qint_t(const qint_t&) {}
    qint_t& operator=(const qint_t&) { return *this; }
    qint_t& operator%=(const qint_t&) { return *this; }
};
template <int W>
inline qint_t<W> operator+(const qint_t<W>&, const qint_t<W>&) {
    return qint_t<W>{};
}
} // namespace sturm
using qint = sturm::qint_t<2>;

void demo(qint a, qint b, qint n) {
    
#line 53 "modular_compound_collapse.cpp"
sturm::qint_t<2> r = ::sturm::add_mod(a, b, n);
    (void)r;
}
