// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: modular_mul_op.cpp
// sturm-r5pn.4 (Phase 0.4) input — identity snapshot for the upcoming
// `(a * b) % n` modular-mul rewrite.
//
// Sister fixture to `modular_add_op.cpp` — same hermetic-stub shape,
// different inner binary operator. With the modular-op matcher /
// emitter SHELL empty, this round-trips byte-identical to the input
// (modulo the AUTO-GENERATED header). Phase 5 / beat 5.2 (sturm-r5pn
// epic) overwrites the `.expected.cpp` with the post-rewrite golden,
// at which point this snapshot becomes the Phase 5.2 regression. See
// `modular_add_op.cpp`'s header for the full rationale.
namespace sturm {
template <int W>
class qint_t {
public:
    qint_t() {}
    qint_t(const qint_t&) {}
    qint_t& operator=(const qint_t&) { return *this; }
};
template <int W>
inline qint_t<W> operator*(const qint_t<W>&, const qint_t<W>&) {
    return qint_t<W>{};
}
template <int W>
inline qint_t<W> operator%(const qint_t<W>&, const qint_t<W>&) {
    return qint_t<W>{};
}
} // namespace sturm
using qint = sturm::qint_t<2>;

void demo(qint a, qint b, qint n) {
    
#line 31 "modular_mul_op.cpp"
sturm::qint_t<2> r = ::sturm::mul_mod(a, b, n);
    (void)r;
}
