// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: modular_pow_op_flag.cpp
// sturm-r5pn.4 (Phase 0.4) input — identity snapshot for the upcoming
// `pow(a, x) % n` rewrite under the FLAG-ON (`STURM_MODULAR_POW=ON`)
// build configuration.
//
// Plan §2.2 / §7.2 #3: when the gating CMake option is ON, the
// modular-op matcher folds `pow(a, x) % n` into a single
// `lib_pow_mod_dsl(a, x, n, r)` call (no wide intermediate). With the
// matcher SHELL empty under sturm-r5pn.4, this fixture currently
// round-trips byte-identical to the input — the same behavior the
// sister `modular_pow_op_default.cpp` fixture pins under the OFF
// configuration. Phase 5 / beat 5.5 (sturm-r5pn epic) overwrites this
// `.expected.cpp` with the post-rewrite golden, at which point the
// two fixtures' expected files diverge and the snapshot pair pins
// the matcher's flag-conditional behavior.
//
// Why a separate fixture instead of reusing the default one: the
// `STURM_MODULAR_POW` propagation contract pinned by the
// `cmake_modular_pow_flag` ctest is binary-level (driver target is
// rebuilt with a different compile-time flag, NOT a runtime
// argument), so the flag-on golden is built against the
// `STURM_MODULAR_POW=ON` configuration. Carrying both fixtures in
// the source tree lets a CI matrix run one ctest invocation per
// configuration — under the current SHELL build both pass; under
// Phase 5 the two fixtures' goldens diverge and the same matrix
// catches a missing or accidental rewrite in either direction.
//
// The hermetic stub layout mirrors `modular_pow_op_default.cpp`
// byte-for-byte except for this header text and the file name in the
// AUTO-GENERATED `Source:` line — keeping the body identical means
// the SHELL identity contract is the same in both flag modes (no
// rewrite ⇒ no diff), and Phase 5 only has to swap the `.expected`
// goldens to introduce the per-mode behavior split.
namespace sturm {
template <int W>
class qint_t {
public:
    qint_t() {}
    qint_t(const qint_t&) {}
    qint_t& operator=(const qint_t&) { return *this; }
};
template <int W>
inline qint_t<W> operator%(const qint_t<W>&, const qint_t<W>&) {
    return qint_t<W>{};
}
template <int W>
inline qint_t<W> pow(const qint_t<W>&, const qint_t<W>&) {
    return qint_t<W>{};
}
} // namespace sturm
using qint = sturm::qint_t<2>;

void demo(qint a, qint x, qint n) {
    qint r = sturm::pow(a, x) % n;
    (void)r;
}
