// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: modular_pow_op_default.cpp
// sturm-qzab.4 (P5 beat 5.4) input — `pow(a, x) % n` modular-pow
// negative-path snapshot under the DEFAULT (`STURM_MODULAR_POW=OFF`)
// build configuration.
//
// Plan §7.4 / PRD §3.4: when the gating CMake option is OFF (the
// default), the modular-op matcher MUST leave both `pow` and `%`
// alone — the existing two-step lowering (`lib_pow_dsl + lib_mod_dsl`)
// is preserved bit-exactly. The OFF-mode contract is enforced at the
// matcher TU level by the `#ifdef STURM_MODULAR_POW` block in
// `transpiler/src/matcher_modular_op.cpp::register_modular_op_matcher`
// — under flag OFF no PowMod arm is registered, the AddMod / MulMod
// arms reject the AST shape (no inner `+`/`*` op-call), and the entire
// declaration round-trips through the transpiler untouched. This
// snapshot's `.expected.cpp` is byte-identical to the input modulo the
// `AUTO-GENERATED ... Source:` header — exactly the identity output the
// matcher's no-op contract guarantees. Negative coverage at the
// matcher-API level is in
// `transpiler/tests/test_matcher_modular_op.cpp::test_pow_mod_*_does_not_match_under_flag_off`.
//
// Sister fixture: `modular_pow_op_flag.cpp` exercises the same code
// shape under `STURM_MODULAR_POW=ON`. Beat 5.5 (sturm-qzab.5) lands
// the flag-on PowMod arm and overwrites the sister `.expected.cpp`
// with the post-rewrite golden, at which point the two fixtures'
// expected files diverge and a CI matrix run pins the per-mode
// behavior split.
//
// The hermetic `pow` stub below avoids any `<cmath>` include — the
// transpiler's FixedCompilationDatabase carries no system include
// paths.
namespace sturm {
template <int W>
class qint_t {
public:
    qint_t() {}
    qint_t(const qint_t&) {}
    qint_t& operator=(const qint_t&) { return *this; }
};
template <int W>
inline qint_t<W> operator%(const qint_t<W>&, const qint_t<W>&) {
    return qint_t<W>{};
}
template <int W>
inline qint_t<W> pow(const qint_t<W>&, const qint_t<W>&) {
    return qint_t<W>{};
}
} // namespace sturm
using qint = sturm::qint_t<2>;

void demo(qint a, qint x, qint n) {
    
#line 50 "modular_pow_op_default.cpp"
sturm::qint_t<2> r = ::sturm::pow_mod(a, x, n);
    (void)r;
}
