// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: modular_pow_op_default.cpp
// sturm-r5pn.4 (Phase 0.4) input — identity snapshot for the upcoming
// `pow(a, x) % n` rewrite under the DEFAULT (`STURM_MODULAR_POW=OFF`)
// build configuration.
//
// Plan §2.2 / §7.2 #3: when the gating CMake option is OFF (the
// default), the modular-op matcher MUST leave both `pow` and `%`
// alone — the existing two-step lowering (`lib_pow_dsl + lib_mod_dsl`)
// is preserved bit-exactly. With the matcher SHELL empty under the
// current sturm-r5pn.4 work, the round-trip already produces
// byte-identical output regardless of flag value; this fixture pins
// the OFF-mode contract early so Phase 5 / beat 5.4 has the snapshot
// in place when the per-pattern matcher arms land.
//
// Sister fixture: `modular_pow_op_flag.cpp` exercises the same code
// shape under `STURM_MODULAR_POW=ON`. Both fixtures currently produce
// identical output (matcher shell, no rewrite); Phase 5 / beat 5.5
// will overwrite `modular_pow_op_flag.expected.cpp` with the
// post-rewrite golden — at which point the two fixtures diverge and
// the matcher's flag-conditional behavior is pinned by the diff.
//
// The hermetic `pow` stub below avoids any `<cmath>` include — the
// transpiler's FixedCompilationDatabase carries no system include
// paths.
namespace sturm {
template <int W>
class qint_t {
public:
    qint_t() {}
    qint_t(const qint_t&) {}
    qint_t& operator=(const qint_t&) { return *this; }
};
template <int W>
inline qint_t<W> operator%(const qint_t<W>&, const qint_t<W>&) {
    return qint_t<W>{};
}
template <int W>
inline qint_t<W> pow(const qint_t<W>&, const qint_t<W>&) {
    return qint_t<W>{};
}
} // namespace sturm
using qint = sturm::qint_t<2>;

void demo(qint a, qint x, qint n) {
    qint r = sturm::pow(a, x) % n;
    (void)r;
}
