// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: or_assign_qint.cpp
// LO-0.1 (sturm-nw7c): bare-scope `|=` desugar fixture (input).
//
// Exercises the PRD §2.2 desugar of the qint RHS form of OR_ASSIGN on a
// qint_t: `a |= b;` must be paired with the LO emission
// `qint __sturm_tmp_or_0; or_oop(a, b, __sturm_tmp_or_0);
// swap(a, __sturm_tmp_or_0);` plus the matching scope-exit cleanup
// `swap(a, __sturm_tmp_or_0);
// sturm::invert<&::sturm::lib_or_dsl>()(a, b, __sturm_tmp_or_0);`. The
// RHS `b` is a bare DeclRefExpr to a second qint_t parameter — no
// converting constructor fires, so the matcher sees a qint-qint
// CXXOperatorCallExpr with a plain identifier on the right. See plan §2
// and PRD §2.2 / §2.4.
namespace sturm {
template <int W>
class qint_t {
public:
    qint_t() {}
    qint_t(const qint_t&) {}
    qint_t& operator|=(const qint_t&) { return *this; }
};
} // namespace sturm
using qint = sturm::qint_t<1>;

void demo(qint a, qint b) { 
#line 24 "or_assign_qint.cpp"
qint __sturm_tmp_or_0;

#line 24 "or_assign_qint.cpp"
or_oop(a, b, __sturm_tmp_or_0);

#line 24 "or_assign_qint.cpp"
swap(a, __sturm_tmp_or_0); 
#line 24 "or_assign_qint.cpp"
    swap(a, __sturm_tmp_or_0);

#line 24 "or_assign_qint.cpp"
    sturm::invert<&::sturm::lib_or_dsl>()(a, b, __sturm_tmp_or_0);

#line 24 "or_assign_qint.cpp"
}
