// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: or_single_backend.cpp
// LP3 RED fixture for the sturm-transpile conversion-wrapped-path
// snapshot test.
//
// The MVP matcher (M8) matches the EAGER initializer shape — where
// `operator|` returns a bare `qbool`. Historically, under
// `STURM_BACKEND_ENABLED=1` (examples/or_circuit.cpp, pre-PK-2),
// `operator|` instead returned an expression-template wrapper that
// was materialized to `qbool` via a user-defined conversion.  The MVP
// matcher did not peel this chain and therefore failed to inject
// `uncompute_or(...)` on the real example. (Phase K PK-2 has since
// retired those qbool-level wrappers, but this hermetic fixture
// preserves the shape so the matcher-widening regression remains
// testable — see notes below.)
//
// This hermetic fixture reproduces that historical shape minimally
// (defining its own local `OrExpr` wrapper below) so the regression is
// visible without depending on backend headers. LP2's AST calibration
// confirmed the call-site tree here is byte-identical to the tree the
// pre-PK-2 backend header produced — see the notes on issue sturm-ea7.
//
// LP3 lands this fixture with a PLACEHOLDER expected file; LP4 widens
// the matcher and freezes the real golden output. While LP3 is on
// HEAD and LP4 is not yet landed, `ctest -R snapshot_or_single_backend`
// MUST fail — that failure is the RED signal LP4 flips to GREEN.
//
// Why the `(void)tmp;` reader is load-bearing
// -------------------------------------------
// Phase J PJ-4a (dead-ancilla elimination) removes any `qbool` VarDecl
// whose value is never read.  Without a reader, PJ-4a fires before the
// LP4 backend-shape uncompute-injection matcher: the entire
// `qbool tmp = a | b;` line is dropped, the function body collapses to
// empty, and this snapshot byte-mismatches against the pre-PJ-4a
// golden.  The explicit `(void)tmp;` bumps the reader count to 1,
// shutting off PJ-4a so the LP4 matcher runs as intended.  Same
// rationale — and same textual shape — as or_single_runtime.cpp /
// hoist_or_out_of_for.cpp.
namespace sturm {
class qbool {
public:
    qbool() {}
    qbool(const qbool&) {}
};

template<class T>
struct OrExpr {
    const T& a;
    const T& b;
    OrExpr(const T& a_, const T& b_) : a(a_), b(b_) {}
    operator T() const { return T{}; }   // user-defined conversion
};

inline OrExpr<qbool> operator|(const qbool& a, const qbool& b) {
    return OrExpr<qbool>{a, b};
}
} // namespace sturm
using sturm::qbool;

void demo(qbool a, qbool b) { qbool tmp = a | b; (void)tmp; 
#line 58 "or_single_backend.cpp"
    uncompute_or(tmp, a, b);

#line 58 "or_single_backend.cpp"
}
