// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: or_single.cpp
// PRD-MVP input for the sturm-transpile snapshot test (M11).
//
// The demo function below is the canonical hello-world quantum routine from
// the transpiler PRD (docs/prd_transpiler_uncompute.md, lines 150-158):
// a single `qbool tmp = a | b;` that the uncompute pass must pair with an
// explicit `uncompute_or(tmp, a, b);` call before the scope closes.
//
// The sturm-transpile binary runs with a FixedCompilationDatabase that
// carries no include paths, so we cannot `#include <sturm/sturm.hpp>` here
// and expect type resolution to succeed. Instead we inline a minimal
// qbool stub — identical in shape to the one test_emitter.cpp uses for its
// golden snapshot — so the AST matcher can resolve the `operator|` call.
// The stub is part of the fixture's source-of-truth: the expected snapshot
// must contain it verbatim, because Clang's Rewriter preserves the original
// byte stream outside its own insertions.
//
// Why the `(void)tmp;` reader is load-bearing
// -------------------------------------------
// Phase J PJ-4a (dead-ancilla elimination) removes any `qbool` VarDecl
// whose value is never read.  Without a reader, PJ-4a fires before the
// M7 uncompute-injection matcher: the entire `qbool tmp = a | b;` line
// is dropped, the function body collapses to empty, and this snapshot
// byte-mismatches against the pre-PJ-4a golden.  The explicit
// `(void)tmp;` bumps the reader count to 1, shutting off PJ-4a so the
// M7 matcher runs as intended.  Same rationale — and same textual
// shape — as or_single_runtime.cpp / hoist_or_out_of_for.cpp.
namespace sturm {
class qbool {
public:
    qbool() {}
    qbool(const qbool&) {}
};
inline qbool operator|(const qbool&, const qbool&) { return qbool{}; }
} // namespace sturm
using sturm::qbool;

void demo(qbool a, qbool b) { qbool tmp = a | b; (void)tmp; 
#line 37 "or_single.cpp"
    uncompute_or(tmp, a, b);

#line 37 "or_single.cpp"
}
