// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: reorder_overlap_rejected.cpp
// Phase M / PM5-8 input for the sturm-transpile end-to-end snapshot
// test — "overlap rejected" case.
//
// Companion to reorder_disjoint_qbool.cpp exercising Gate 3 of the
// PM5-5 peephole reorder matcher: when B's footprint OVERLAPS A's
// result (or any of C's other operands / result), the reorder is
// refused — even when A and C otherwise match the trigger shape.
// This is the PM5 plan §2 "bit-overlap" branch: commuting B past C
// would change the semantics because B and the moved-C now share a
// qubit at a different sequencing, and footprint-only analysis
// cannot prove that the underlying quantum state is preserved.
//
// Shape exercised here:
//   qbool r = (a & b) | c;   // PE-4 pushes AND(__stu_t0, a, b) +
//                            //             OR(r, __stu_t0, c)
//   x ^= r;                   // B — XOR_ASSIGN(x, r). B's operand `r`
//                             //     OVERLAPS PE-4's outer OR target.
//   y ^= r;                   // C' — operand is `r`, not `__stu_t0`,
//                             //      so Gate 1 rejects at the name
//                             //      check, but conceptually B's `r`
//                             //      read would also trip Gate 3.
//   (void)r;
//
// Through the current pipeline PM5 does not fire — no AND op with
// `__stu_t` prefix lands adjacent to a matching XOR_ASSIGN (the PE-4
// outer OR always wedges between the inner AND and any subsequent
// stmt in scope.ops). The snapshot captures the pre-reorder pipeline
// emission so any future relaxation of the matcher produces a
// visible delta here.
namespace sturm {
class qbool {
public:
    qbool() {}
    qbool(const qbool&) {}
    qbool& operator=(const qbool&) { return *this; }
    qbool& operator^=(const qbool&) { return *this; }
};
inline qbool operator&(const qbool&, const qbool&) { return qbool{}; }
inline qbool operator|(const qbool&, const qbool&) { return qbool{}; }
} // namespace sturm
using sturm::qbool;

void demo(qbool a, qbool b, qbool c, qbool x, qbool y) {
    
#line 44 "reorder_overlap_rejected.cpp"
qbool __stu_t0 = a & b;
    #line 44 "reorder_overlap_rejected.cpp"
qbool r = __stu_t0 | c;
    x ^= r;
    y ^= r;
    (void)r;

#line 46 "reorder_overlap_rejected.cpp"
    y ^= r;

#line 45 "reorder_overlap_rejected.cpp"
    x ^= r;

#line 44 "reorder_overlap_rejected.cpp"
    uncompute_or(r, __stu_t0, c);

#line 44 "reorder_overlap_rejected.cpp"
    uncompute_and(__stu_t0, a, b);

#line 48 "reorder_overlap_rejected.cpp"
}
