// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: reorder_bitproxy_nonconst.cpp
// Phase M / PM5-8 input for the sturm-transpile end-to-end snapshot
// test — "BitProxy non-constant index" case.
//
// Companion to reorder_bitproxy_const.cpp but the BitProxy subscript
// uses a RUNTIME index `arr[i]`. The PM5-3 extractor's
// `peel_bitproxy_constant` returns `std::nullopt` when
// `Expr::EvaluateAsInt` fails, falling back to the full-width
// `{name="arr", bit_range=[0, W)}` footprint. That full-width
// footprint IS bit-disjoint from a qbool footprint (different name),
// so `may_overlap()` still reports disjointness — the matcher would
// fire in the PM5 plan §12 sharp-edge-1 sense.
//
// In practice, however, the B statement here is NOT a matcher-driven
// op-push that lands a QOperation with a BitProxy operand — `arr[i]
// = 1;` hits the PA-3-adjacent pathway only when the matchers
// recognize BitProxy writes. Current MVP does not model BitProxy
// subscript assignment as a QOp of any kind, so the B stmt produces
// no QOperation at all. scope.ops therefore has only the PE-4 ops
// + the user's XOR_ASSIGN(x, r). PM5 observes the same triple shape
// as the sibling fixtures and refuses at Gate 1's operand-name
// check — the reorder does not fire.
//
// This fixture pins the "runtime-index BitProxy falls back to full-
// width footprint, which is still bit-disjoint, but no B op-push
// happens so the triple is structurally absent" behaviour. A future
// BitProxy subscript matcher that pushed a QOp would flip this
// fixture's expected output.
#include <cstddef>
namespace sturm {
class qbool {
public:
    qbool() {}
    qbool(const qbool&) {}
    qbool& operator=(const qbool&) { return *this; }
    qbool& operator^=(const qbool&) { return *this; }
};
inline qbool operator&(const qbool&, const qbool&) { return qbool{}; }
inline qbool operator|(const qbool&, const qbool&) { return qbool{}; }

class BitProxy {
public:
    BitProxy() {}
    BitProxy& operator=(int) { return *this; }
};

template <std::size_t W>
class qint_t {
public:
    qint_t() {}
    qint_t(const qint_t&) {}
    // NOLINTNEXTLINE(google-explicit-constructor)
    qint_t(long long) {}
    qint_t& operator=(const qint_t&) { return *this; }
    BitProxy operator[](std::size_t) { return BitProxy{}; }
};
} // namespace sturm
using sturm::qbool;
using qint4_t = sturm::qint_t<4>;

void demo(qbool a, qbool b, qbool c, qbool x, int i) {
    qint4_t arr = 0;
    
#line 62 "reorder_bitproxy_nonconst.cpp"
qbool __stu_t0 = a & b;
    #line 62 "reorder_bitproxy_nonconst.cpp"
qbool r = __stu_t0 | c;
    arr[i] = 1;
    x ^= r;
    (void)r;
    (void)arr;

#line 64 "reorder_bitproxy_nonconst.cpp"
    x ^= r;

#line 62 "reorder_bitproxy_nonconst.cpp"
    uncompute_or(r, __stu_t0, c);

#line 62 "reorder_bitproxy_nonconst.cpp"
    uncompute_and(__stu_t0, a, b);

#line 67 "reorder_bitproxy_nonconst.cpp"
}
