// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: reversible_return_style_qbool.cpp
// reversible_return_style_qbool.cpp — Phase Q / Q-3 (sturm-5kgu.4)
// positive fixture pinning the canonical return-style `qbool` forward
// shape that Q-A (`return_to_out_param.cpp`, sturm-5kgu.2) normalizes
// into an out-param twin.
//
// Canonical PRD §4.1 / §5.1 item 1 shape
// --------------------------------------
// `qbool marked(qint x, int T) { return x >= T; }` is the return-style
// forward the PRD uses to motivate out-param normalization (P9a). Per
// PRD §4.1 the user MAY declare the routine in either of two equivalent
// shapes:
//
//   (a) return-style — this fixture:
//         qbool marked(qint x, int T) { return x >= T; }
//   (b) out-param-style — see reversible_out_param_canonical.cpp:
//         void marked(qbool& a, qint x, int T) { a ^= (x >= T); }
//
// Q-A's job (already landed per sturm-5kgu.2) is to synthesize the
// (b)-shaped twin source text from the (a)-shaped forward so the
// downstream straight-line adjoint emitter (R-A, sturm-88d7.2) has a
// canonical target to reverse. The canonical name the Q-A module emits
// for this forward is `__marked_out` — see the golden companion
// `transpiler/tests/fixtures/return_to_out_param_1.expected.cpp`.
//
// Q-A / Q-B wiring status — PASS-THROUGH
// ---------------------------------------
// As of Phase Q the Q-A / Q-B matchers are NOT yet wired into the
// production `transpile_consumer.cpp` driver (R-C's `DriveOptions`
// hook is still null per the TODO(backend) around
// `matcher_reversible_drive.cpp`). Running `sturm-transpile` on this
// fixture therefore PASSES TODAY as a pure pass-through: the driver
// prepends the `AUTO-GENERATED by sturm-transpile -- do not edit` /
// `Source: reversible_return_style_qbool.cpp` header, copies the body
// verbatim, exits zero, emits nothing on stderr. The `.expected.cpp`
// golden differs from this input only by the two header lines.
//
// When Q-A's out-param twin emission wires into the consumer, the
// golden upgrades in place: the emitter appends the synthesized
// `__marked_out` twin text (matching the Q-A unit-test golden at
// `transpiler/tests/fixtures/return_to_out_param_1.expected.cpp`) plus
// the matching `STURM_REGISTER_ADJOINT` call once R-A's adjoint body
// emission also wires in. The fixture source itself does NOT change
// — the scope-flip happens entirely in the golden on the snapshot
// side.
//
// Stub qint + qbool
// -----------------
// `sturm-transpile` runs Clang with a FixedCompilationDatabase that
// carries no include paths, so we inline a minimal `qint` / `qbool`
// stub whose `>=` overload is sufficient for the parser to accept
// the comparison in the return expression. The stub mirrors the
// shape used by the Q-A unit-test fixture
// `transpiler/tests/fixtures/return_to_out_param_1.cpp` so the Q-A
// module's twin emission operates against the identical AST shape
// on both paths.
namespace sturm {
class qbool {
public:
    qbool() = default;
    qbool(bool) {}
    qbool(const qbool&) = default;
    qbool& operator=(const qbool&) = default;
    qbool& operator^=(const qbool&) { return *this; }
};
class qint {
public:
    qint() = default;
    qbool operator>=(int) const { return qbool{}; }
};
} // namespace sturm
using sturm::qbool;
using sturm::qint;

// Canonical return-style reversible forward (PRD §4.1).
//
// Q-A will machine-emit the sibling twin:
//
//     [[clang::annotate("sturm::reversible")]]
//     void __marked_out(qint x, int T, qbool& __marked_out) {
//         __marked_out ^= x >= T;
//     }
//
// as shown in `return_to_out_param_1.expected.cpp`. The forward
// itself stays unchanged in the rewritten buffer — P9a's pledge that
// return-style and out-param-style are two surfaces over the same
// semantic shape is honoured by LEAVING the return-style source
// intact and adding the twin alongside it.
[[clang::annotate("sturm::reversible")]]
qbool marked(qint x, int T) { return x >= T; }
