// reversible_out_param_canonical.cpp — Phase Q / Q-3 (sturm-5kgu.4)
// positive fixture pinning the canonical out-param-style forward
// shape — the one Q-A (`return_to_out_param.cpp`, sturm-5kgu.2) treats
// as a NO-OP because the signature is already in the shape Phase R's
// adjoint emitter targets directly.
//
// Canonical PRD §4.1 / §5.1 item 1 shape
// --------------------------------------
// `void marked(qbool& a, qint x, int T) { a ^= (x >= T); }` is the
// out-param-style forward the PRD uses as the "already canonical"
// twin to the return-style fixture `reversible_return_style_qbool.cpp`.
// Per PRD §4.1 the user MAY declare the routine in either shape:
//
//   (a) return-style — see reversible_return_style_qbool.cpp:
//         qbool marked(qint x, int T) { return x >= T; }
//   (b) out-param-style — this fixture:
//         void marked(qbool& a, qint x, int T) { a ^= (x >= T); }
//
// For shape (b) Q-A has no work to do: the signature ALREADY targets
// a non-const qbool reference out-parameter and the body is ALREADY a
// single `^=` assignment against that out-parameter. Calling
// `synthesize_out_param_twin` on this forward returns
// `synthesized=false` with reason `NonQuantumReturnType` (the return
// type is `void`, which is not a quantum type — see
// `return_to_out_param.hpp`'s `TwinRejectReason` enum and the
// `test_void_return_rejects` case in
// `transpiler/tests/test_return_to_out_param.cpp` that pins this
// contract). The downstream pipeline reads the `NonQuantumReturnType`
// reason as "already canonical, skip normalization" — R-A proceeds
// directly to adjoint emission using the forward's own body as input.
//
// Q-A / Q-B wiring status — PASS-THROUGH
// ---------------------------------------
// As of Phase Q the Q-A / Q-B matchers are NOT yet wired into the
// production `transpile_consumer.cpp` driver (R-C's `DriveOptions`
// hook is still null per the TODO(backend) around
// `matcher_reversible_drive.cpp`). Running `sturm-transpile` on this
// fixture therefore PASSES TODAY as a pure pass-through: the driver
// prepends the `AUTO-GENERATED by sturm-transpile -- do not edit` /
// `Source: reversible_out_param_canonical.cpp` header, copies the body
// verbatim, exits zero, emits nothing on stderr. The `.expected.cpp`
// golden differs from this input only by the two header lines.
//
// When R-A / R-C wire into the consumer, the golden upgrades in place:
// the emitter appends the machine-emitted `__marked_adj` companion
// (body: the same `*regs[0] ^= __t0` statement, which is self-inverse
// at the XOR_ASSIGN level) plus the matching
// `STURM_REGISTER_ADJOINT(marked, __marked_adj);` line. Q-A does NOT
// contribute to the golden flip for this fixture — it reports
// `NonQuantumReturnType` and R-A works straight from the forward.
// The fixture source itself does NOT change.
//
// Why the pointer-array indirection is load-bearing
// -------------------------------------------------
// The existing Phase A PA-3 `XorAssignCallback`
// (`matcher_qbool_assign.cpp`) anchors on a `CXXOperatorCallExpr` whose
// LHS peels to a bare `DeclRefExpr` on a `qbool&` parameter — a direct
// `a ^= (x >= T);` would fire that matcher TODAY (outside the Phase-Q
// driver wiring) and would land an inline uncompute call in the body,
// corrupting the pass-through snapshot. Routing the LHS through
// `*regs[0] ^= __t0` gives it a `UnaryOperator(ArraySubscriptExpr)`
// shape that PA-3 does not match — the body passes through verbatim.
// This is the same workaround the Phase R `reversible_body_xor.cpp`
// fixture uses for structurally identical reasons (see that fixture's
// preamble for the fuller story; Phase A's callback shape is shared
// across all `^=` matches).
//
// Once Q-B wires in and the reversible-routine adjoint pipeline takes
// over the body-rewrite responsibility for `[[sturm::reversible]]`
// forwards, this workaround can be removed — the adjoint emitter
// handles the XOR_ASSIGN directly and PA-3 is suppressed for
// reversible bodies.
//
// Stub qint + qbool
// -----------------
// `sturm-transpile` runs Clang with a FixedCompilationDatabase that
// carries no include paths, so we inline a minimal `qint` / `qbool`
// stub whose `>=` / `^=` overloads are sufficient for the parser to
// accept the body.
namespace sturm {
class qbool {
public:
    qbool() = default;
    qbool(bool) {}
    qbool(const qbool&) = default;
    qbool& operator=(const qbool&) = default;
    qbool& operator^=(const qbool&) { return *this; }
};
class qint {
public:
    qint() = default;
    qbool operator>=(int) const { return qbool{}; }
};
} // namespace sturm
using sturm::qbool;
using sturm::qint;

// Canonical out-param-style reversible forward (PRD §4.1). The
// pointer-array indirection is a PA-3 workaround (see preamble) —
// at the reversible-body shape level this is exactly the canonical
// `a ^= (x >= T);` form the PRD uses as the out-param-style example.
//
// Q-A's classifier returns `synthesized=false` with reason
// `NonQuantumReturnType` on this shape (the `void` return makes the
// routine fall outside the Q-A normalization surface) — R-A treats
// that as "already canonical" and emits the adjoint directly from
// this forward's body. No twin is inserted.
[[clang::annotate("sturm::reversible")]]
void marked(qbool& a, qint x, int T) {
    qbool* regs[1] = {&a};
    qbool __t0 = x >= T;
    *regs[0] ^= __t0;
}
