// reversible_return_style_qint.cpp — Phase Q / Q-3 (sturm-5kgu.4)
// positive fixture pinning the canonical return-style `qint` forward
// shape that Q-A (`return_to_out_param.cpp`, sturm-5kgu.2) normalizes
// into an out-param twin.
//
// Canonical PRD §4.1 / §5.1 item 1 shape
// --------------------------------------
// `qint echo(const qint& x) { return x; }` is a degenerate-but-real
// return-style forward whose return type is `qint` (the quantum-integer
// surface, as opposed to the `qbool` surface pinned by the sibling
// fixture `reversible_return_style_qbool.cpp`). Per PRD §4.1 the `qint`
// return case rides the same Q-A machinery as `qbool`: the out-param
// twin is synthesized by rewriting the return expression into an `^=`
// XOR-assign against a freshly-appended `qint&` out-parameter, keeping
// the forward's parameter list verbatim.
//
// The canonical twin text Q-A produces for this forward is:
//
//     [[clang::annotate("sturm::reversible")]]
//     void __echo_out(const qint& x, qint& __echo_out) {
//         __echo_out ^= x;
//     }
//
// This matches the unit-test golden
// `transpiler/tests/fixtures/return_to_out_param_3.expected.cpp`
// — the Q-A unit-test harness compiles the same source shape and
// diffs the emitted twin string against that golden.
//
// Q-A / Q-B wiring status — PASS-THROUGH
// ---------------------------------------
// As of Phase Q the Q-A / Q-B matchers are NOT yet wired into the
// production `transpile_consumer.cpp` driver. Running `sturm-transpile`
// on this fixture therefore PASSES TODAY as a pure pass-through: the
// driver prepends the `AUTO-GENERATED by sturm-transpile -- do not edit`
// / `Source: reversible_return_style_qint.cpp` header, copies the body
// verbatim, exits zero, emits nothing on stderr. The `.expected.cpp`
// golden differs from this input only by the two header lines.
//
// When Q-A's out-param twin emission wires into the consumer, the
// golden upgrades in place: the emitter appends the synthesized
// `__echo_out` twin text plus the matching `STURM_REGISTER_ADJOINT`
// call once R-A's adjoint body emission also wires in. The fixture
// source itself does NOT change — the scope-flip happens entirely
// in the golden on the snapshot side.
//
// Why `const qint&` (not `qint&`)
// -------------------------------
// P9b (PRD §9) locks constness-declares-input-mutability. The forward
// reads `x` but does NOT mutate it — the function is a pure wrap of
// the input into the out-slot. `const qint&` is the right spelling
// because (i) it signals read-only intent to the reader, (ii) it is
// the signature shape Q-B's constness matcher accepts without
// diagnostic, and (iii) it is the shape PRD §5.3's parameter-capture
// contract tolerates because there is nothing to capture (the input
// does not mutate).
//
// Stub qint
// ---------
// `sturm-transpile` runs Clang with a FixedCompilationDatabase that
// carries no include paths, so we inline a minimal `qint` stub whose
// `operator=` / `operator^=` / copy-constructor surface is sufficient
// for the parser to accept the identity `return x;` body. The stub
// mirrors the shape used by the Q-A unit-test fixture
// `transpiler/tests/fixtures/return_to_out_param_3.cpp` so the Q-A
// module's twin emission operates against the identical AST shape
// on both paths.
namespace sturm {
class qint {
public:
    qint() = default;
    qint(const qint&) = default;
    qint& operator=(const qint&) = default;
    qint& operator^=(const qint&) { return *this; }
};
} // namespace sturm

using sturm::qint;

// Canonical return-style reversible forward returning `qint` — same
// shape as the PRD §4.1 `qbool marked(...)` example, just widened from
// the bool quantum surface to the qint surface. Q-A treats the two
// surfaces symmetrically because the twin's synthesis only needs the
// return type's spelling (recovered verbatim via `clang::Lexer::
// getSourceText`); the in-language semantics of the return-type
// record does not enter the twin synthesis at all.
[[clang::annotate("sturm::reversible")]]
qint echo(const qint& x) { return x; }
