// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: reversible_loop_bit_reversal.cpp
// reversible_loop_bit_reversal.cpp — Phase S / S-3 (sturm-ha2k.4) positive
// loop fixture for the bit-reversal reversed-iteration synthesis contract.
//
// Canonical PRD §5.2 reversible shape
// -----------------------------------
// The routine carries `[[clang::annotate("sturm::reversible")]]` and its
// body is a single canonical forward for-loop whose body performs the
// standard three-statement XOR-swap identity:
//
//     for (int i = 0; i < 2; ++i) {
//         int j = 3 - i;
//         *regs[i] ^= *regs[j];
//         *regs[j] ^= *regs[i];
//         *regs[i] ^= *regs[j];
//     }
//
// This is the bit-reversal shape pinned by PRD §5.2: iteration i swaps
// cells i and (N-1-i) in place via the XOR-triple identity.  The swaps
// are pairwise disjoint (iter 0 touches q0/q3, iter 1 touches q1/q2) so
// at the state level either iteration direction lands the same result,
// but the B11 contract still demands a reversed-iteration adjoint —
// this fixture pins that contract regardless of commutativity.
//
// Why the pointer-array indirection is load-bearing
// -------------------------------------------------
// See `reversible_loop_ripple.cpp` for the full rationale.  The short
// version: anchoring the LHS as `*regs[i] ^= *regs[j]` makes it a
// UnaryOperator(ArraySubscriptExpr) rather than a DeclRefExpr, so PH-3
// does not match and no diagnostic fires under the current (pre-R-2)
// transpiler.  The snapshot golden is therefore a clean byte-for-byte
// pass-through of the input.
//
// R-2 status (auto_register_emitter)
// ----------------------------------
// Same pass-through posture as the ripple fixture.  When R-2 lands and
// the Phase S driver wires `loop_reversal` into the emission path, the
// golden upgrades to also carry the synthesised `bit_reversal_adj`
// companion: loop header reversed (`for (int i = 1; i >= 0; --i)`) and
// the three body statements in reversed source order.  Because the
// XOR-swap triple is symmetric around its middle statement the
// reversed triple is textually the same, but the iteration-order
// reversal is the load-bearing contract.
//
// Stub qbool — same minimal shape as the ripple fixture.
namespace sturm {
class qbool {
public:
    qbool() {}
    qbool(const qbool&) {}
    qbool& operator=(const qbool&) { return *this; }
    qbool& operator^=(const qbool&) { return *this; }
};
} // namespace sturm
using sturm::qbool;

[[clang::annotate("sturm::reversible")]]
void bit_reversal(qbool& q0, qbool& q1, qbool& q2, qbool& q3) {
    qbool* regs[4] = {&q0, &q1, &q2, &q3};
    for (int i = 0; i < 2; ++i) {
        int j = 3 - i;
        *regs[i] ^= *regs[j];
        *regs[j] ^= *regs[i];
        *regs[i] ^= *regs[j];
    }
}

void __bit_reversal_adj(qbool& q0, qbool& q1, qbool& q2, qbool& q3) {
}


STURM_REGISTER_ADJOINT(bit_reversal, __bit_reversal_adj);
