// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: routine_inside_when.cpp
// Phase I / PI-5 input for the sturm-transpile snapshot test.
//
// Exercises a user-routine call that sits inside a `WHEN(c) { ... }`
// body with a locally-declared output. PI-3 classifies `tmp` as
// `Intermediate` relative to the WHEN body (the two share the same
// enclosing CompoundStmt — the innermost block the WHEN macro wraps),
// so the M8 uncompute pass plants the inverse at THAT block's close
// brace — i.e. inside the WHEN body, not after it. This is the Phase F
// `insert_before_override` anchor the PI-3 / PI-4 rewrite inherits for
// routine calls.
//
// The stub below replicates the WHEN macro shape from
// include/sturm/control/when.hpp so the call site parses without the
// real runtime headers (the transpiler runs with an empty compilation
// database — same rule every other fixture follows).
namespace sturm {

class qbool {
public:
    qbool() {}
    qbool(const qbool&) {}
    qbool& operator=(const qbool&) { return *this; }
    bool should_run() const { return true; }
};

namespace _detail {
template <typename FnPtr>
struct adjoint_of;
} // namespace _detail

template <typename R, typename... Args>
constexpr auto invert(R (*fn)(Args...)) noexcept {
    (void)fn;
    return _detail::adjoint_of<R (*)(Args...)>::value;
}

namespace detail {

inline qbool& materialize_when(qbool& q) { return q; }
inline qbool  materialize_when(qbool&& q) { return static_cast<qbool&&>(q); }

struct WhenCapture { WhenCapture() = default; };
inline qbool& make_when_guard(qbool& q) { return q; }

} // namespace detail
} // namespace sturm

#define STURM_REGISTER_ADJOINT(fn, adj)                                        \
    namespace sturm {                                                          \
    namespace _detail {                                                        \
    template <>                                                                \
    struct adjoint_of<decltype(&::fn)> {                                       \
        static constexpr auto value = &::adj;                                  \
    };                                                                         \
    }                                                                          \
    }

void my_rotate(sturm::qbool& out, const sturm::qbool& in, int k) {
    (void)in; (void)k; (void)out;
}

void my_rotate_adj(sturm::qbool& out, const sturm::qbool& in, int k) {
    (void)in; (void)k; (void)out;
}

STURM_REGISTER_ADJOINT(my_rotate, my_rotate_adj)

using sturm::qbool;

#define WHEN(expr) \
    if (::sturm::detail::WhenCapture _when_capture_{}; true) \
    if (decltype(auto) _when_val_ = ::sturm::detail::materialize_when(expr); true) \
    if (auto& _when_guard_ = ::sturm::detail::make_when_guard(_when_val_); \
        _when_guard_.should_run())

void demo(qbool c, const qbool& in) {
    WHEN(c) {
        qbool tmp;
        my_rotate(tmp, in, 3);
    
#line 79 "routine_inside_when.cpp"
    sturm::invert<&my_rotate>()(tmp, in, 3);

#line 80 "routine_inside_when.cpp"
}
}
