// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: routine_inside_loop.cpp
// Phase I / PI-5 input for the sturm-transpile snapshot test.
//
// Exercises a user-routine call that sits inside a `for (...)` body
// where the output slot is a qbool declared INSIDE the same loop
// body. PI-3 classifies `tmp` as `Intermediate` relative to the
// for-body's CompoundStmt, so the M8 uncompute pass plants the
// inverse at the loop body's close brace — i.e. INSIDE the loop,
// invoked once per iteration. This is the Phase H-style
// per-iteration placement the PI-3/PI-4 rewrite inherits for routine
// calls.
namespace sturm {
class qbool {
public:
    qbool() {}
    qbool(const qbool&) {}
};

namespace _detail {
template <typename FnPtr>
struct adjoint_of;
} // namespace _detail

template <typename R, typename... Args>
constexpr auto invert(R (*fn)(Args...)) noexcept {
    (void)fn;
    return _detail::adjoint_of<R (*)(Args...)>::value;
}
} // namespace sturm

#define STURM_REGISTER_ADJOINT(fn, adj)                                        \
    namespace sturm {                                                          \
    namespace _detail {                                                        \
    template <>                                                                \
    struct adjoint_of<decltype(&::fn)> {                                       \
        static constexpr auto value = &::adj;                                  \
    };                                                                         \
    }                                                                          \
    }

void my_rotate(sturm::qbool& out, const sturm::qbool& in, int k) {
    (void)in; (void)k; (void)out;
}

void my_rotate_adj(sturm::qbool& out, const sturm::qbool& in, int k) {
    (void)in; (void)k; (void)out;
}

STURM_REGISTER_ADJOINT(my_rotate, my_rotate_adj)

using sturm::qbool;

void demo(const qbool& in) {
    for (int i = 0; i < 3; ++i) {
        qbool tmp;
        my_rotate(tmp, in, i);
    
#line 55 "routine_inside_loop.cpp"
    invert(my_rotate)(tmp, in, i);

#line 56 "routine_inside_loop.cpp"
}
}
