// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: routine_single_out_escapes.cpp
// Phase I / PI-5 input for the sturm-transpile snapshot test.
//
// Exercises PI-3's `Final` classification: the output slot is a
// function parameter of `demo`, so the value escapes through the
// caller and the transpiler MUST NOT inject any inverse. Unlike the
// PH-3 skip path, no diagnostic is emitted — the user's intent to
// return the mutated value is perfectly valid (P9). The generated
// file is therefore byte-identical to the input (modulo the
// AUTO-GENERATED header the emitter prepends).
namespace sturm {
class qbool {
public:
    qbool() {}
    qbool(const qbool&) {}
};

namespace _detail {
template <typename FnPtr>
struct adjoint_of;
} // namespace _detail

template <typename R, typename... Args>
constexpr auto invert(R (*fn)(Args...)) noexcept {
    (void)fn;
    return _detail::adjoint_of<R (*)(Args...)>::value;
}
} // namespace sturm

#define STURM_REGISTER_ADJOINT(fn, adj)                                        \
    namespace sturm {                                                          \
    namespace _detail {                                                        \
    template <>                                                                \
    struct adjoint_of<decltype(&::fn)> {                                       \
        static constexpr auto value = &::adj;                                  \
    };                                                                         \
    }                                                                          \
    }

void my_rotate(sturm::qbool& out, const sturm::qbool& in, int k) {
    (void)in; (void)k; (void)out;
}

void my_rotate_adj(sturm::qbool& out, const sturm::qbool& in, int k) {
    (void)in; (void)k; (void)out;
}

STURM_REGISTER_ADJOINT(my_rotate, my_rotate_adj)

using sturm::qbool;

void demo(qbool& out, const qbool& in) {
    my_rotate(out, in, 3);
}
