// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: routine_multiple_lifo.cpp
// Phase I / PI-5 input for the sturm-transpile snapshot test.
//
// Exercises LIFO inverse ordering for two DISTINCT user-routine
// calls in the SAME CompoundStmt. The M8 uncompute pass walks each
// scope's op list in reverse, so the injected inverses appear in
// reverse source order: the second call's adjoint fires first, then
// the first call's adjoint. This is the load-bearing invariant for
// any multi-routine compute block — without strict LIFO the ancilla
// pool would not return to its pre-compute state.
//
// The two routines deliberately carry DIFFERENT signatures
// (`rot_a(qbool&, const qbool&)` vs
// `rot_b(qbool&, const qbool&, int)`) so the
// `decltype(&::rot_a)` and `decltype(&::rot_b)` function-pointer
// types the STURM_REGISTER_ADJOINT macro keys on are distinct —
// otherwise both `adjoint_of` specializations would collapse onto
// the same template instance and only one registration would
// survive in the PI-1 registry.
namespace sturm {
class qbool {
public:
    qbool() {}
    qbool(const qbool&) {}
};

namespace _detail {
template <typename FnPtr>
struct adjoint_of;
} // namespace _detail

template <typename R, typename... Args>
constexpr auto invert(R (*fn)(Args...)) noexcept {
    (void)fn;
    return _detail::adjoint_of<R (*)(Args...)>::value;
}
} // namespace sturm

#define STURM_REGISTER_ADJOINT(fn, adj)                                        \
    namespace sturm {                                                          \
    namespace _detail {                                                        \
    template <>                                                                \
    struct adjoint_of<decltype(&::fn)> {                                       \
        static constexpr auto value = &::adj;                                  \
    };                                                                         \
    }                                                                          \
    }

void rot_a(sturm::qbool& out, const sturm::qbool& in) {
    (void)in; (void)out;
}

void rot_a_adj(sturm::qbool& out, const sturm::qbool& in) {
    (void)in; (void)out;
}

void rot_b(sturm::qbool& out, const sturm::qbool& in, int k) {
    (void)in; (void)out; (void)k;
}

void rot_b_adj(sturm::qbool& out, const sturm::qbool& in, int k) {
    (void)in; (void)out; (void)k;
}

STURM_REGISTER_ADJOINT(rot_a, rot_a_adj)
STURM_REGISTER_ADJOINT(rot_b, rot_b_adj)

using sturm::qbool;

void demo(const qbool& in) {
    qbool t0;
    qbool t1;
    rot_a(t0, in);
    rot_b(t1, in, 3);

#line 73 "routine_multiple_lifo.cpp"
    invert(rot_b)(t1, in, 3);

#line 72 "routine_multiple_lifo.cpp"
    invert(rot_a)(t0, in);

#line 74 "routine_multiple_lifo.cpp"
}
