// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: top_level_lossy_in_main.cpp
// LO-0.2 (sturm-iz9d): main-exception desugar fixture (TARGET shape).
//
// Post-LO-2d desugar pins the §4.3 main-exception rule. The first
// `&=` (line 41) sits in `main`'s outermost CompoundStmt: the §2.2
// forward pair (qint tmp / and_oop / swap) IS emitted, but the
// `LossyScopeExitEmitter` detects the enclosing FunctionDecl is
// `main` and the matched block is its body, then suppresses cleanup
// registration with the uncompute_pass LIFO queue (PRD §4.3,
// plan §4 LO-2d row). No reverse swap, no invert call.
//
// The second `&=` (line 43) sits inside a lambda body whose
// CompoundStmt is a CHILD block of main — the suppression rule does
// NOT fire, so the §2.3 cleanup pair lands before the lambda body's
// closing brace. This negative half is what plan §9's risk register
// flagged: a naive "enclosing block is some FunctionDecl::body"
// check would also match the lambda. LO-2d's correct check walks to
// the nearest enclosing FunctionDecl, confirms its identifier is
// `main`, AND confirms the matched CompoundStmt is its body itself.
//
// Consumer: LO-2d (sturm-wva7). Until LO-2a/2b/2c/2d land, this
// expected file is RED and is not wired in CMakeLists.txt.
namespace sturm {
template <int W>
class qint_t {
public:
    qint_t() {}
    qint_t(const qint_t&) {}
    qint_t& operator&=(const qint_t&) { return *this; }
};
} // namespace sturm
using qint = sturm::qint_t<2>;

int main() {
    qint a, b;
    #line 41 "top_level_lossy_in_main.cpp"
qint __sturm_tmp_and_0;
    #line 41 "top_level_lossy_in_main.cpp"
and_oop(a, b, __sturm_tmp_and_0);
    #line 41 "top_level_lossy_in_main.cpp"
swap(a, __sturm_tmp_and_0);
    auto inner = [](qint x, qint y) {
        #line 43 "top_level_lossy_in_main.cpp"
qint __sturm_tmp_and_1;
        #line 43 "top_level_lossy_in_main.cpp"
and_oop(x, y, __sturm_tmp_and_1);
        #line 43 "top_level_lossy_in_main.cpp"
swap(x, __sturm_tmp_and_1);

#line 43 "top_level_lossy_in_main.cpp"
    swap(x, __sturm_tmp_and_1);

#line 43 "top_level_lossy_in_main.cpp"
    sturm::invert<&::sturm::lib_c_AND_dsl>()(x, y, __sturm_tmp_and_1);

#line 44 "top_level_lossy_in_main.cpp"
};
    (void)inner;
    return 0;
}
