// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: when_nested_passthrough.cpp
// Phase F / PF-5 input for the sturm-transpile snapshot test.
//
// Exercises the nested `WHEN` shape:
//
//     WHEN(a) {              // outer: bare DeclRefExpr → named-passthrough
//         WHEN(b | c) {      // inner: compound lift fires
//             (void)d;
//         }
//     }
//
// Two `WHEN` invocations produce two independent three-`if` towers; the
// PF-2 matcher fires on each middle `_when_val_` IfStmt independently:
//   - The outer hits the named-passthrough short-circuit (peeled payload
//     is a bare `DeclRefExpr` to `a`) — no rewrite scheduled.
//   - The inner flattens `b | c` into `__stu_t0`, rewrites the macro
//     argument in-place, and plants an `uncompute_or(__stu_t0, b, c);`
//     call immediately after the inner body's closing brace.
//
// The load-bearing identity invariant this fixture pins is that the
// per-WHEN post-body brace is keyed off the unique `_when_val_` VarDecl
// of the matched tower (via `compute_post_body_brace` descending
// `when_if->getThen()` twice). A naive implementation that tracked the
// "latest" post-body brace across matcher invocations would anchor the
// inner lift's `uncompute_or` after the OUTER body's `}` and the byte-
// compare would fail. This fixture is a regression guard for that.
//
// No matcher changes are expected from PF-5 — PF-3/PF-4 already drive
// the per-IfStmt identity through `when_if->getThen()` descent. The
// fixture doubles as the canonical nested-WHEN snapshot for Phase F.
//
// The stub inlined below replicates the structure the matcher inspects:
//   - `sturm::qbool` with `operator|` so `b | c` type-checks inside the
//     inner `WHEN(...)` arg.
//   - `sturm::detail::materialize_when` overload set the WHEN macro's
//     middle `if` calls in its init-stmt.
//   - The exact three-`if` WHEN macro from
//     `include/sturm/control/when.hpp:293`. A no-op `WhenCapture` /
//     `make_when_guard` pair keeps the init-stmts type-checked without
//     dragging in the full runtime's `WhenGuard` / `QubitPool`.
//
// The sturm-transpile binary runs with a FixedCompilationDatabase that
// carries no include paths, so this file must be hermetic — same rule
// the Phase A..E snapshot fixtures follow.
namespace sturm {

class qbool {
public:
    qbool() {}
    qbool(const qbool&) {}
    qbool& operator=(const qbool&) { return *this; }
    bool should_run() const { return true; }
};

inline qbool operator|(const qbool&, const qbool&) { return qbool{}; }
inline qbool operator&(const qbool&, const qbool&) { return qbool{}; }

namespace detail {

inline qbool& materialize_when(qbool& q) { return q; }
inline qbool  materialize_when(qbool&& q) { return static_cast<qbool&&>(q); }

struct WhenCapture { WhenCapture() = default; };
inline qbool& make_when_guard(qbool& q) { return q; }

} // namespace detail
} // namespace sturm

using sturm::qbool;

#define WHEN(expr) \
    if (::sturm::detail::WhenCapture _when_capture_{}; true) \
    if (decltype(auto) _when_val_ = ::sturm::detail::materialize_when(expr); true) \
    if (auto& _when_guard_ = ::sturm::detail::make_when_guard(_when_val_); \
        _when_guard_.should_run())

void demo(qbool a, qbool b, qbool c, qbool d) {
    WHEN(a) {
        #line 78 "when_nested_passthrough.cpp"
qbool __stu_t0 = b | c;
WHEN(__stu_t0) { (void)d; }
#line 78 "when_nested_passthrough.cpp"
    uncompute_or(__stu_t0, b, c);

    }
}
