// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: when_compound.cpp
// Phase F / PF-4 input for the sturm-transpile snapshot test.
//
// Exercises the compound WHEN lift against the exact roadmap example:
// `WHEN((b | c) & d) { body }`. The matcher recurses through
// `detail::flatten_arg` (reused from Phase E PF-0) to decompose the nested
// expression into two flat temps, rewrites the macro argument to reference
// the outermost temp, and plants two `uncompute_*` calls in LIFO order
// immediately after the WHEN body's closing brace:
//
//     qbool __stu_t0 = b | c;
//     qbool __stu_t1 = __stu_t0 & d;
//     WHEN(__stu_t1) { (void)a; }    uncompute_and(__stu_t1, __stu_t0, d);
//     uncompute_or(__stu_t0, b, c);
//
// The LIFO order — AND first, then OR — is the load-bearing assertion of
// this fixture. Both ops share the same `stmt_range` (the WHEN-expansion
// range of the macro argument), so a naive `std::sort` keyed by stmt_range
// would not deterministically produce AND-then-OR; Phase F PF-4 switches
// the uncompute pass to `std::stable_sort` so the callback-append order
// (innermost-first → outermost-last) becomes the source-order tiebreaker,
// and the reverse walk produces outermost-first (AND) then innermost-last
// (OR). This fixture pins that ordering as a byte-level golden.
//
// The stub inlined below replicates the structure the matcher inspects:
//   - `sturm::qbool` with `operator|` and `operator&` so both compound
//     kinds type-check on the argument expression.
//   - `sturm::detail::materialize_when` overload set the WHEN macro's
//     middle `if` calls in its init-stmt.
//   - The exact three-`if` WHEN macro from
//     `include/sturm/control/when.hpp:293`. A no-op `WhenCapture` /
//     `make_when_guard` pair keeps the init-stmts type-checked without
//     dragging in the full runtime's `WhenGuard` / `QubitPool`.
//
// The sturm-transpile binary runs with a FixedCompilationDatabase that
// carries no include paths, so this file must be hermetic — same rule
// the Phase A..E snapshot fixtures follow.
namespace sturm {

class qbool {
public:
    qbool() {}
    qbool(const qbool&) {}
    qbool& operator=(const qbool&) { return *this; }
    bool should_run() const { return true; }
};

inline qbool operator|(const qbool&, const qbool&) { return qbool{}; }
inline qbool operator&(const qbool&, const qbool&) { return qbool{}; }

namespace detail {

inline qbool& materialize_when(qbool& q) { return q; }
inline qbool  materialize_when(qbool&& q) { return static_cast<qbool&&>(q); }

struct WhenCapture { WhenCapture() = default; };
inline qbool& make_when_guard(qbool& q) { return q; }

} // namespace detail
} // namespace sturm

using sturm::qbool;

#define WHEN(expr) \
    if (::sturm::detail::WhenCapture _when_capture_{}; true) \
    if (decltype(auto) _when_val_ = ::sturm::detail::materialize_when(expr); true) \
    if (auto& _when_guard_ = ::sturm::detail::make_when_guard(_when_val_); \
        _when_guard_.should_run())

void demo(qbool a, qbool b, qbool c, qbool d) {
    qbool __stu_t0 = b | c;
qbool __stu_t1 = __stu_t0 & d;
WHEN(__stu_t1) { (void)a; }
#line 70 "when_compound.cpp"
    uncompute_and(__stu_t1, __stu_t0, d);

#line 70 "when_compound.cpp"
    uncompute_or(__stu_t0, b, c);

}
