// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: when_lossy_and_assign.cpp
// LO-0.4 (sturm-0j3a): WHEN-lifted lossy `&=` desugar fixture (TARGET shape).
//
// Post-LO-2 desugar: the matcher (sturm-9254) + emitter family
// (sturm-yxxa / sturm-hbwr) replace the user's `a &= b;` inside the WHEN
// body with the §2.2 forward pair, and the §2.3 scope-exit cleanup is
// planted at the WHEN body's closing brace via the existing uncompute_pass
// LIFO queue. Inside `WHEN(ctrl)`, the four lifted points (forward
// `and_oop`, forward `swap`, reverse `swap`, `invert(lib_c_AND_dsl)`) each
// consult the active control stack and emit per-bit Fredkin / controlled
// CCX as PRD §5 specifies. Until LO-2 lands, the snapshot test built
// against this fixture is in a known-RED state. See bd sturm-9254.
namespace sturm {
template <int W>
class qint_t {
public:
    qint_t() {}
    qint_t(const qint_t&) {}
    qint_t& operator&=(const qint_t&) { return *this; }
};
class qbool {
public:
    qbool() {}
    qbool(const qbool&) {}
    qbool& operator=(const qbool&) { return *this; }
    bool should_run() const { return true; }
};
namespace detail {
inline qbool& materialize_when(qbool& q) { return q; }
inline qbool  materialize_when(qbool&& q) { return static_cast<qbool&&>(q); }
struct WhenCapture { WhenCapture() = default; };
inline qbool& make_when_guard(qbool& q) { return q; }
} // namespace detail
} // namespace sturm
using qint = sturm::qint_t<2>;
using sturm::qbool;
#define WHEN(expr) \
    if (::sturm::detail::WhenCapture _when_capture_{}; true) \
    if (decltype(auto) _when_val_ = ::sturm::detail::materialize_when(expr); true) \
    if (auto& _when_guard_ = ::sturm::detail::make_when_guard(_when_val_); \
        _when_guard_.should_run())

void demo(qbool ctrl, qint a, qint b) {
    WHEN(ctrl) {
        #line 44 "when_lossy_and_assign.cpp"
qint __sturm_tmp_and_0;
        #line 44 "when_lossy_and_assign.cpp"
and_oop(a, b, __sturm_tmp_and_0);
        #line 44 "when_lossy_and_assign.cpp"
swap(a, __sturm_tmp_and_0);

#line 44 "when_lossy_and_assign.cpp"
    swap(a, __sturm_tmp_and_0);

#line 44 "when_lossy_and_assign.cpp"
    sturm::invert<&::sturm::lib_c_AND_dsl>()(a, b, __sturm_tmp_and_0);

#line 45 "when_lossy_and_assign.cpp"
}
}
