// AUTO-GENERATED by sturm-transpile -- do not edit
// Source: xor_single.cpp
// Phase A / PA-2 input for the sturm-transpile snapshot test.
//
// Exercises the two-operand self-inverse form: `qbool tmp = a ^ b;` must
// be paired with `tmp ^= a;` then `tmp ^= b;` injected before the scope's
// close brace. XOR is self-inverse because (a^b)^a^b == 0, so applying
// the same operands via `^=` to the result qubit uncomputes it without
// any additional library helper.
//
// The sturm-transpile binary runs with a FixedCompilationDatabase that
// carries no include paths, so we inline a minimal qbool stub whose
// `operator^` overload is sufficient for the matcher to resolve the
// binary XOR call.
//
// Why the `(void)tmp;` reader is load-bearing
// -------------------------------------------
// Phase J PJ-4a (dead-ancilla elimination) removes any `qbool` VarDecl
// whose value is never read.  Without a reader, PJ-4a fires before the
// M7 uncompute-injection matcher: the entire `qbool tmp = a ^ b;` line
// is dropped, the function body collapses to empty, and this snapshot
// byte-mismatches against the pre-PJ-4a golden.  The explicit
// `(void)tmp;` bumps the reader count to 1, shutting off PJ-4a so the
// M7 matcher runs as intended.  Same rationale — and same textual
// shape — as or_single_runtime.cpp / hoist_or_out_of_for.cpp.
namespace sturm {
class qbool {
public:
    qbool() {}
    qbool(const qbool&) {}
};
inline qbool operator^(const qbool&, const qbool&) { return qbool{}; }
} // namespace sturm
using sturm::qbool;

void demo(qbool a, qbool b) { qbool tmp = a ^ b; (void)tmp; 
#line 34 "xor_single.cpp"
    tmp ^= a;
    tmp ^= b;

#line 34 "xor_single.cpp"
}
